; addr = 8D05

BOTTOM_SPRITES:
		db 0, 14h, 0
		db 1, 2, 65h, 0Bh, 0Ch,	0Dh, 0Eh, 0Fh, 0Bh dup(1Ah), 2Bh
		db 2Ch,	0Bh dup(1Ah), 0Eh, 0Fh,	1Bh, 1Ch, 1Dh, 65h, 1Eh
		db 1Fh,	0, 15h,	0, 3, 4, 41h, 47h, 48h,	49h, 4Ah, 2 dup(4Bh)
		db 4Fh,	50h, 51h, 52h, 53h, 4Bh, 4Eh, 4Dh, 4Ch,	44h, 2Dh
		db 2Eh,	65h, 2Fh, 30h, 2Fh, 30h, 2Fh, 30h, 2Fh,	30h, 2Fh
		db 30h,	2Fh, 30h, 2Fh, 30h, 65h
		db 65h,	20h, 21h, 0, 16h, 0, 5,	6
     	db 'BcdddddddddddeeeEeeeeeeee12e56e9:e=>"#',0
		db 17h,	0, 7, 8, 43h, 54h, 55h,	56h, 57h, 58h, 59h, 5Ah
		db 5Bh,	5Ch, 5Dh, 5Eh, 5Fh, 60h, 61h, 62h, 46h,	65h, 6 dup(10h)
		db 65h,	33h, 34h, 65h, 37h, 38h, 65h, 3Bh, 3Ch,	65h, 3Fh
		db 40h,	24h, 25h, 0, 18h, 0, 9,	0Ah, 65h, 0Bh, 0Ch, 0Dh
		db 0Eh,	0Fh, 9 dup(1Ah), 65h, 28h, 2 dup(29h), 2Ah, 65h
		db 9 dup(1Ah), 0Eh, 0Fh, 1Bh, 1Ch, 1Dh,	65h, 26h, 27h
		db 0FFh
		