; GRAPHIX BANK 2
; addr = 69AC
GRBANK2:
		db 11h dup(0), 38h, 0, 0EEh, 1, 3Bh, 1, 4Eh, 5, 0C3h
		db 5, 0F0h, 17h, 0FCh, 17h, 0FFh, 2 dup(0), 0C0h, 0, 0B0h
		db 0, 0ECh, 0, 0BBh, 0,	0EEh, 0, 3Bh, 80h, 0C2h, 0C0h
		db 17h,	0FEh, 5Fh, 0FBh, 5Fh, 0FEh, 5Fh, 0FBh, 5Fh, 0EEh
		db 5Fh,	0FBh, 5Fh, 0EEh, 5Fh, 0FBh, 0B8h, 0, 0E0h, 0, 0B0h
		db 0, 0E0h, 0, 0B0h, 0,	0C0h, 0, 80h, 0, 0C0h, 0, 5Fh
		db 0EEh, 5Fh, 0FBh, 5Fh, 0EEh, 5Fh, 0FBh, 5Fh, 0EEh, 5Fh
		db 0FBh, 1Fh, 0EEh, 1Fh, 0FBh, 80h, 0, 0C0h, 0,	80h, 0
		db 0C0h, 0, 80h, 0, 0C0h, 0, 80h, 0, 0C0h, 0, 1Fh, 0FEh
		db 7, 0FBh, 7, 0FEh, 7,	0FFh, 1, 0FEh, 1, 0FFh,	0, 7Fh
		db 0, 7Fh, 0B0h, 0, 0E0h, 0, 0B0h, 0, 0ECh, 0, 0B8h, 0
		db 0ECh, 0, 0BBh, 0, 0EEh, 2 dup(0), 1Fh, 0, 7,	0, 1, 0Ah dup(0)
		db 0FBh, 80h, 0FEh, 0C0h, 0BFh,	0B0h, 0EEh, 0E0h, 3Bh
		db 0B8h, 0Eh, 0ECh, 3, 0BBh, 0,	2Eh, 7 dup(0), 2 dup(0FFh)
		db 2 dup(0), 55h, 6 dup(0), 0Fh, 0C0h, 0F0h, 3Ch, 5, 43h
		db 2 dup(55h), 5, 41h, 50h, 14h, 5, 40h, 5 dup(0), 0FCh
		db 0FFh, 17h, 55h, 17h,	55h, 17h, 0, 54h, 3 dup(0), 44h
		db 11h,	99h, 6,	66h, 19h, 99h, 26h, 66h, 19h, 99h, 6, 66h
		db 1, 11h, 44h,	0, 99h,	10h, 66h, 60h, 99h, 98h, 66h, 64h
		db 99h,	90h, 66h, 40h, 88h, 0, 0Fh, 0F0h, 0Ah dup(3Ch)
		db 0Fh,	0F0h, 2	dup(0),	3, 0C0h, 0Fh, 0C0h, 3, 0C0h, 3
		db 0C0h, 3, 0C0h, 3, 0C0h, 0Fh,	0F0h, 2	dup(0),	0Fh, 0F0h
		db 30h,	3Ch, 0,	3Ch, 3,	0F0h, 0Fh, 0, 3Ch, 0Ch,	3Fh, 0FCh
		db 2 dup(0), 0Fh, 0F0h,	30h, 3Ch, 0, 3Ch, 3, 0F0h, 0, 3Ch
		db 30h,	3Ch, 0Fh, 0F0h,	2 dup(0), 3Ch, 0, 3Ch, 0F0h, 3Ch
		db 0F0h, 3Fh, 0FCh, 0, 0F0h, 0,	0F0h, 3, 0FCh, 2 dup(0)
		db 3Fh,	0FCh, 3Ch, 0, 3Fh, 0F0h, 0, 3Ch, 0, 3Ch, 30h, 3Ch
		db 0Fh,	0F0h, 2	dup(0),	0Fh, 0F0h, 3 dup(3Ch), 0, 3Fh
		db 0F0h, 4 dup(3Ch), 0Fh, 0F0h,	2 dup(0), 3Fh, 0FCh, 30h
		db 3Ch,	0, 3Ch,	0, 0F0h, 3, 0C0h, 3, 0C0h, 3, 0C0h, 2 dup(0)
		db 0Fh,	0F0h, 4	dup(3Ch), 0Fh, 0F0h, 4 dup(3Ch), 0Fh, 0F0h
		db 2 dup(0), 0Fh, 0F0h,	4 dup(3Ch), 0Fh, 0FCh, 0, 3 dup(3Ch)
		db 0Fh,	0F0h, 8	dup(0),	2 dup(0EEh), 2 dup(88h), 2 dup(22h)
		db 8 dup(0), 3Fh, 0, 0D4h, 0FFh, 54h, 55h, 54h,	55h, 15h
		db 5 dup(0), 3,	0F0h, 3Ch, 0Fh,	0C1h, 50h, 2 dup(55h)
		db 41h,	50h, 14h, 5, 1,	50h, 6 dup(0), 0FFh, 2 dup(0)
		db 0FFh, 55h, 8	dup(0),	3, 0, 0Eh, 0, 3Bh, 0, 0EEh, 0
		db 0BBh
		db 2, 0ECh, 3, 83h, 2Ch, 0, 0BBh, 0, 0ECh, 40h,	0B1h, 40h
		db 0C3h, 50h, 0Fh, 50h,	3Fh, 0D4h, 0BFh, 0D4h, 0, 2Eh
		db 0, 0Bh, 0, 0Eh, 0, 0Bh, 0, 0Eh, 0, 3, 0, 2, 0, 3, 0EFh
		db 0D4h, 0BFh, 0F5h, 0EFh, 0F5h, 0BFh, 0F5h, 0EFh, 0F5h
		db 0BBh, 0F5h, 0EFh, 0F5h, 0BBh, 0F5h, 0, 2, 0,	3, 0, 2
		db 0, 3, 0, 2, 0, 3, 0,	2, 0, 3, 0EFh, 0F5h, 0BBh, 0F5h
		db 0EFh, 0F5h, 0BBh, 0F5h, 0EFh, 0F5h, 0BBh, 0F5h, 0EFh
		db 0F4h, 0BBh, 0F4h, 0,	0Eh, 0,	0Bh, 0,	0Eh, 0,	3Bh, 0
		db 2Eh,	0, 3Bh,	0, 0EEh, 0, 0BBh, 0EFh,	0F4h, 0BFh, 0D0h
		db 0EFh, 0D0h, 0BFh, 0D0h, 0FFh, 40h, 0BFh, 40h, 0FDh
		db 0, 0FDh, 0, 2, 0EFh,	3, 0BFh, 0Eh, 0FEh, 0Bh, 0BBh
		db 2Eh,	0ECh, 3Bh, 0B0h, 0EEh, 0C0h, 0B8h, 0, 0F4h, 0
		db 0D0h, 0, 40h, 0Bh dup(0), 3Fh, 0C0h,	0FFh, 0FCh, 2 dup(0FFh)
		db 0Fh,	0FFh, 33h, 0FFh, 0CCh, 2 dup(0FFh), 0CCh, 33h
		db 30h,	4 dup(0), 4 dup(0FFh), 2 dup(0CCh), 2 dup(33h)
		db 4 dup(0), 0Fh, 0FCh,	5 dup(0FFh), 0CCh, 0FFh, 30h, 2	dup(0CFh)
		db 33h,	0FFh, 3, 3Ch, 0, 0FFh, 0Fh, 0FFh, 3Fh, 0FFh, 3Fh
		db 3, 3Ch, 3, 3Ch, 3, 3Ch, 0Fh,	0FFh, 2	dup(0FCh), 0, 0FFh
		db 0C0h, 0FFh, 0F0h, 3,	0F0h, 0, 0F0h, 0, 0F0h,	0C0h, 0F0h
		db 0FFh, 0FCh, 0FFh, 0F0h, 3Ch,	0F3h, 3, 0FFh, 0, 0CFh
		db 3, 33h, 3, 0C0h, 0, 0F3h, 0,	2 dup(3Fh), 0FCh, 3Ch
		db 0F0h, 0FFh, 0, 0CCh,	0, 33h,	0, 0Fh,	0, 3Ch,	0, 0F0h
		db 4 dup(0), 1,	0, 15h,	0, 55h,	0, 55h,	0, 0AAh, 15h, 55h
		db 4 dup(0), 40h, 0, 4,	0, 51h,	0, 55h,	0, 0AAh, 0, 55h
		db 44h,	2 dup(0), 2 dup(55h), 6Ah, 0AAh, 6Fh, 0FFh, 6Fh
		db 0FFh, 6Fh, 0F0h, 6Fh, 0C0h, 6Fh, 3, 6Fh, 0Fh, 2 dup(55h)
		db 0AAh, 0A9h, 0FFh, 0F9h, 3, 0F9h, 0Fh, 0F9h, 0FFh, 0F9h
		db 0FFh, 0F9h, 0FFh, 0F9h, 6Fh,	0Fh, 6Fh, 3, 6Fh, 0C0h
		db 6Fh,	0F0h, 6Fh, 0FFh, 6Fh, 0FFh, 6Ah, 0AAh, 2 dup(55h)
		db 0FFh, 0F9h, 0FFh, 0F9h, 0FFh, 0F9h, 0Fh, 0F9h, 3, 0F9h
		db 0FFh, 0F9h, 0AAh, 0A9h, 4 dup(55h), 6Ah, 0AAh, 6Fh
		db 0FFh, 6Ch, 3Fh, 6Ch,	0Ch, 6Fh, 0, 6Fh, 0C3h,	6Fh, 0Ch
		db 2 dup(55h), 0AAh, 0A9h, 0FFh, 0F9h, 0FFh, 0F9h, 3Fh
		db 0F9h, 0FFh, 0F9h, 0FFh, 0F9h, 3Fh, 0F9h, 6Fh, 3Ch, 6Fh
		db 0FFh, 6Fh, 0FFh, 6Fh, 0FFh, 6Fh, 0FFh, 6Fh, 0FFh, 6Ah
		db 0AAh, 2 dup(55h), 0Fh, 0F9h,	3, 0F9h, 0C0h, 0F9h, 0F0h
		db 39h,	0FCh, 39h, 0FFh, 0F9h, 0AAh, 0A9h, 4 dup(55h)
		db 6Ah,	0AAh, 6Fh, 0FFh, 6Fh, 0F0h, 6Fh, 0FCh, 6Fh, 0F0h
		db 6Fh,	0C0h, 6Fh, 0, 2	dup(55h), 0AAh,	0A9h, 0FFh, 0F9h
		db 0Fh,	0F9h, 3Fh, 0F9h, 0Fh, 0F9h, 3, 0F9h, 0,	0F9h, 6Fh
		db 0, 6Fh, 0, 6Fh, 0, 6Fh, 0C0h, 6Fh, 0FCh, 6Fh, 0FFh
		db 6Ah,	0AAh, 2	dup(55h), 4, 0F9h, 4, 0F9h, 10h, 0F9h
		db 3, 0F9h, 3Fh, 0F9h, 0FFh, 0F9h, 0AAh, 0A9h, 4 dup(55h)
		db 6Ah,	0AAh, 6Fh, 0FFh, 6Ch, 3Fh, 6Ch,	3, 6Fh,	0C0h, 6Fh
		db 0FCh, 6Fh, 0FFh, 2 dup(55h),	0AAh, 0A9h, 0FFh, 0F9h
		db 0FFh, 0F9h, 0FFh, 0F9h, 0FFh, 0F9h, 3Fh, 0F9h, 0Fh
		db 0F9h, 6Fh, 0FFh, 6Fh, 0FFh, 6Fh, 0FFh, 6Fh, 0FFh, 6Fh
		db 0FFh, 6Fh, 0FFh, 6Ah, 0AAh, 2 dup(55h), 0C3h, 0F9h
		db 0F0h, 0F9h, 0F0h, 0F9h, 0FCh, 39h, 0FCh, 39h, 0FFh
		db 0F9h, 0AAh, 0A9h, 2 dup(55h), 0, 1, 0, 6, 0,	1Ah, 0
		db 6Ah,	1, 0AAh, 4, 0AAh, 1Ah, 2Ah, 6Ah, 8Ah, 6Ah, 0A2h
		db 6Ah,	0A8h
		db 6Ah,	0A8h, 6Ah, 0A8h, 6Ah, 0A8h, 6Ah, 0A8h, 6Ah, 0A8h
		db 6Ah,	0A2h, 6Ah, 8Ah,	1Ah, 2Ah, 4, 0AAh, 1, 0AAh, 0
		db 6Ah,	0, 1Ah,	0, 6, 0, 1, 40h, 0, 90h, 0, 0A4h, 0, 0A9h
		db 0, 0AAh, 40h, 0AAh, 10h, 0A8h, 0A4h,	0A2h, 0A9h, 8Ah
		db 0A9h, 2Ah, 0A9h, 2Ah, 0A9h, 2Ah, 0A9h, 2Ah, 0A9h, 2Ah
		db 0A9h, 2Ah, 0A9h, 8Ah, 0A9h, 0A2h, 0A9h, 0A8h, 0A4h
		db 0AAh, 10h, 0AAh, 40h, 0A9h, 0, 0A4h,	0, 90h,	0, 40h
		db 0, 2	dup(55h), 2 dup(0AAh), 0A8h, 2,	0A8h, 0AAh, 0A8h
		db 0Ah,	0A8h, 0AAh, 0A8h, 3 dup(0AAh), 2 dup(55h), 2 dup(0AAh)
		db 28h,	80h, 28h, 8Ah, 28h, 80h, 28h, 8Ah, 0, 80h, 2 dup(0AAh)
		db 2 dup(55h), 2 dup(0AAh), 20h, 8, 0A2h, 8Ah, 0A0h, 0Ah
		db 0A2h, 2Ah, 22h, 88h,	2 dup(0AAh), 2 dup(55h), 2 dup(0AAh)
		db 2, 0, 8Ah, 28h, 2Ah,	0, 2Ah,	28h, 2,	28h, 2 dup(0AAh)
		db 2 dup(55h), 0Eh dup(0AAh), 2	dup(55h), 2 dup(0AAh)
		db 20h,	0Ah, 22h, 8Ah, 20h, 0Ah, 22h, 8Ah, 22h,	8Ah, 2 dup(0AAh)
		db 2 dup(55h), 2 dup(0AAh), 0, 8Ah, 2Ah, 8Ah, 20h, 8Ah
		db 28h,	8Ah, 0,	80h, 2 dup(0AAh), 2 dup(55h), 2	dup(0AAh)
		db 0A8h, 2, 0A8h, 0A2h,	0A8h, 2, 0A8h, 0A2h, 0A8h, 0A2h
		db 2 dup(0AAh),	2 dup(55h), 2 dup(0AAh), 28h, 80h, 28h
		db 0A2h, 28h, 0A2h, 28h, 0A2h, 82h, 80h, 2 dup(0AAh), 2	dup(55h)
		db 2 dup(0AAh),	8Ah, 20h, 8Ah, 22h, 8Ah, 20h, 8Ah, 22h
		db 2 dup(0A0h),	2 dup(0AAh), 2 dup(55h), 2 dup(0AAh), 8
		db 2, 0A8h, 0A2h, 28h, 2, 0A8h,	8Ah, 8,	0A2h, 2	dup(0AAh)
		db 2 dup(55h), 2 dup(0AAh), 0, 80h, 2Ah, 8Ah, 2, 80h, 2Ah
		db 0AAh, 0, 80h, 2 dup(0AAh), 2	dup(55h), 2 dup(0AAh)
		db 2Ah,	3 dup(0AAh), 2Ah, 0AAh,	2Ah, 0AAh, 2Ah,	5 dup(0AAh)
		db 0, 7	dup(2Ah), 0, 2Ah, 2 dup(0AAh), 2 dup(55h), 3 dup(0AAh)
		db 0A2h, 0AAh, 82h, 0AAh, 0A2h,	0AAh, 0A2h, 0AAh, 80h
		db 2 dup(0AAh),	2 dup(55h), 0Eh	dup(0AAh), 2 dup(55h)
		db 2 dup(0AAh),	0, 2Ah,	0AAh, 2Ah, 0, 2	dup(2Ah), 0AAh
		db 0, 2Ah, 2 dup(0AAh),	2 dup(55h), 3 dup(0AAh), 80h, 3	dup(0AAh)
		db 0A0h, 3 dup(0AAh), 80h, 2 dup(0AAh),	2 dup(55h), 2 dup(0AAh)
		db 0Ah,	0AAh, 8Ah, 0AAh, 0Ah, 0AAh, 8Ah, 0AAh, 0Ah, 3 dup(0AAh)
		db 2 dup(55h), 2 dup(0AAh), 0A2h, 8Ah, 0A2h, 8Ah, 0A0h
		db 2, 0AAh, 8Ah, 0AAh, 2, 2 dup(0AAh), 2 dup(55h), 3 dup(0AAh)
		db 0A8h, 0AAh, 0A8h, 0AAh, 0A8h, 3 dup(0AAh), 0A8h, 2 dup(0AAh)
		db 2 dup(55h), 2 dup(0AAh), 0, 3 dup(0AAh), 0, 0AAh, 0A8h
		db 0AAh, 0, 3 dup(0AAh), 2 dup(55h), 3 dup(0AAh), 0, 0AAh
		db 2Ah,	0AAh, 0, 0AAh, 2Ah, 0AAh, 0, 2 dup(0AAh), 2 dup(55h)
		db 2 dup(0AAh),	2Ah, 3 dup(0AAh), 2Ah, 0AAh, 2Ah, 0AAh
		db 2Ah,	3 dup(0AAh), 2 dup(55h), 2 dup(0AAh), 80h, 0Ah
		db 2 dup(8Ah), 0AAh, 2Ah, 0A8h,	0AAh, 0A8h, 3 dup(0AAh)
		db 2 dup(55h), 3 dup(0AAh), 0A0h, 0AAh,	0A2h, 0AAh, 0A0h
		db 0AAh, 0A2h, 0AAh, 0A0h, 2 dup(0AAh),	2 dup(55h), 2 dup(0AAh)
		db 2, 0AAh, 0A2h, 0AAh,	2, 0AAh, 0A2h, 0AAh, 2,	3 dup(0AAh)
		db 2 dup(55h), 2 dup(0AAh), 0A8h, 0, 3 dup(0A8h), 0, 0AAh
		db 2 dup(0A8h),	0, 2 dup(0AAh),	2 dup(55h), 0F0h, 0, 0F0h
		db 3 dup(0), 2 dup(66h), 2 dup(99h), 2 dup(0), 4 dup(55h)
		db 40h dup(0)

		