; addr = 0x702C

LOCATION_OBJECTS:
		db 8Eh, 2 dup(4), 2	dup(0B3h), 0A9h, 0A8h
		db 0AAh, 2 dup(0ABh), 0B2h, 1, 6, 2, 0,	4, 3, 2	dup(0)
		db 8, 3, 10h dup(8Ah), 8 dup(0F8h), 2 dup(4), 0B0h, 0B1h
		db 2 dup(0B3h),	0AFh, 0AAh, 0ABh, 0AAh,	0, 7, 6, 1, 2 dup(0)
		db 8, 4, 8, 4, 8 dup(0B3h), 2 dup(0AAh), 0ABh, 0AAh, 0ABh
		db 0AAh, 2 dup(0ABh), 1, 2 dup(6), 1, 6, 1, 6, 1, 8 dup(4)
		db 2 dup(7), 0Ah, 0Bh, 0Dh, 0Eh, 0Fh, 11h, 12h,	0, 0Ch
		db 0, 14h, 10h,	13h, 4 dup(0), 9, 6 dup(0), 9, 6 dup(0)
		db 9, 6	dup(0),	9, 6 dup(0), 9,	3 dup(0), 4, 2,	15h, 16h
		db 17h,	18h, 19h, 1Ah, 1Bh, 1Ch, 4, 6, 0EEh, 2 dup(0EFh)
		db 0EEh, 0EFh, 2 dup(0EEh), 0EFh, 0EEh,	2 dup(0EFh), 0EEh
		db 0EFh, 0EEh, 2 dup(0EFh), 0EEh, 0EFh,	0EEh, 2	dup(0EFh)
		db 0EEh, 0EFh, 0EEh, 8,	0Ch, 5 dup(8Ah), 27h, 20h, 0, 2Eh
		db 2Fh,	2Dh, 2Eh, 2Fh, 8Ah, 1Fh, 29h, 3Ch
		db 2 dup(3Ch), 3Dh, 3Eh, 3 dup(1Fh), 3Fh, 40h, 3Fh, 40h
		db 4 dup(1Fh), 4 dup(0), 4 dup(1Fh), 4 dup(0), 4 dup(1Fh)
		db 4 dup(0), 4 dup(1Fh), 4 dup(0), 4 dup(1Fh), 4 dup(0)
		db 4 dup(1Fh), 4 dup(0), 4 dup(1Fh), 4 dup(0), 4 dup(1Fh)
		db 4 dup(0), 4 dup(1Fh), 2 dup(3), 2Ch,	2 dup(8Ah), 0EFh
		db 2Ch,	8Ah, 0EEh, 0EFh, 2Ch, 8, 2, 10h	dup(8Ah), 8, 3
		db 0Bh dup(8Ah), 0F2h, 0F3h, 3 dup(8Ah), 0F2h, 0F3h, 0F2h
		db 3Ch,	44h, 0F3h, 0F2h, 0F3h, 2 dup(1), 26h, 2	dup(1)
		db 28h,	2 dup(3), 2 dup(8Ah), 0F0h, 8Ah, 0F0h, 0EEh, 0F0h
		db 0EEh, 0EFh, 2, 1, 5Bh, 5Ch, 2 dup(3), 0EEh, 3 dup(0EFh)
		db 3 dup(0EEh),	2 dup(0EFh), 10h, 2, 10h dup(0B3h), 2 dup(0AAh)
		db 0ABh, 0AAh, 0ABh, 0AAh, 2 dup(0ABh),	2 dup(0AAh), 0ABh
		db 3 dup(0AAh),	0ABh, 0AAh, 5, 4, 8, 0EFh, 0EEh, 0EFh
		db 0EEh, 0, 8, 2 dup(0EEh), 0EFh, 2 dup(0), 8, 0EFh, 0EEh
		db 3 dup(0), 0EEh, 0EFh, 7, 2, 0Ah, 0Bh, 0Dh, 0Eh, 0Fh
		db 11h,	12h, 0,	0Ch, 0,	14h, 10h, 13h, 0, 8, 1,	8 dup(89h)
		db 1, 8, 1Eh, 1Dh, 5Dh,	1Dh, 1Eh, 1Dh, 5Dh, 1Dh, 8, 4
		db 5Eh,	45h, 3Ah, 43h, 3Ah, 3Bh, 3Ah, 5Fh, 21h,	5, 3Bh
		db 3Ah,	3Bh, 43h, 3Ah, 22h, 2 dup(0), 21h, 5, 45h, 3Ah
		db 5Fh,	5 dup(0), 21h, 22h, 2 dup(0), 8, 3, 21h, 5, 3Bh
		db 45h,	3Bh, 3Ah, 3Bh, 22h, 2 dup(0), 21h, 3Bh,	43h, 5
		db 22h,	4 dup(0), 21h, 22h, 3 dup(0), 2	dup(5),	0EEh, 0EFh
		db 0EEh, 0EFh, 3, 0EEh,	0EFh, 0EEh, 3, 0, 2 dup(0EFh)
		db 3, 2	dup(0),	0EFh, 3, 3 dup(0), 3, 4	dup(0),	6, 4, 2	dup(0)
		db 61h,	60h, 3 dup(0), 61h, 3Bh, 3Ah, 60h, 0, 61h, 3Bh
		db 3Ah,	3Bh, 3Ah, 60h, 5Eh, 3Ah, 2 dup(3Bh), 3Ah, 5Fh
		db 6, 1, 62h, 63h, 2 dup(0), 62h, 63h, 8, 2, 0CBh, 0CCh
		db 0CBh, 0CCh, 0CBh, 0CCh, 0CBh, 0CCh, 8 dup(0CAh), 2
		db 3, 71h, 0, 65h, 66h,	71h, 0,	2 dup(4), 2 dup(0B4h)
		db 0B7h, 0B6h, 3 dup(0B8h), 0B5h, 0E7h,	0F1h, 0E1h, 0
		db 0E8h, 0E1h, 2 dup(0), 2 dup(4), 0ADh, 0AEh, 2 dup(0B4h)
		db 0ACh, 3 dup(0B8h), 0, 0E3h, 0E7h, 0E8h, 2 dup(0), 0E3h
		db 0E8h, 8, 2, 8 dup(0B4h), 8 dup(0B8h), 2 dup(3), 0E2h
		db 0E7h, 0E1h, 0, 0E8h,	2 dup(0), 0E2h,	0, 8, 2, 0F1h
		db 0E7h, 0E8h, 0E7h, 0E8h, 0E7h, 2 dup(0E8h), 0E7h, 0E8h
		db 0F1h, 0E8h, 0F1h, 0E7h, 0E8h, 0E7h, 8, 3, 0E7h, 0F1h
		db 0E7h, 0F1h, 0E8h, 0E7h, 0F1h, 2 dup(0E8h), 0E1h, 0
		db 0E2h, 0E1h, 2 dup(0), 0E2h, 0E1h, 7 dup(0), 5, 3, 0E7h
		db 0F1h, 0E8h, 0E7h, 0E1h, 0F1h, 0E7h, 0F1h, 0E1h, 0, 0E8h
		db 0F1h, 0E1h, 2 dup(0), 5, 3, 0E2h, 0F1h, 0E8h, 0E7h
		db 0E8h, 0, 0E2h, 0F1h,	2 dup(0E8h), 2 dup(0), 0E2h, 0E8h
		db 0E7h, 2 dup(5), 0E8h, 0F1h, 0E8h, 0E7h, 0E8h, 0F1h
		db 0E7h, 2 dup(0E8h), 0F1h, 0E7h, 0E8h,	0E7h, 0E8h, 0E7h
		db 0E8h, 0E7h, 0F1h, 0E7h, 0F1h, 0E7h, 0E8h, 2 dup(0E7h)
		db 0E8h, 2 dup(3), 0E0h, 2 dup(0), 0F1h, 0E0h, 0, 0E7h
		db 0E8h, 0E0h, 2 dup(3), 2 dup(0), 0DFh, 0, 0DFh, 0F1h
		db 0DFh, 0E8h, 0E7h, 5,	4, 2 dup(0), 0DFh, 0E0h, 2 dup(0)
		db 0DFh, 2 dup(0E8h), 2	dup(0),	0E8h, 0E7h, 0E8h, 0E0h
		db 0DFh, 0E7h, 0F1h, 2 dup(0E8h), 2 dup(2), 8Eh, 8Fh, 90h
		db 91h,	2 dup(3), 0DDh,	2 dup(8Ah), 0E7h, 0DDh,	8Ah, 0E8h
		db 0F1h, 0DDh, 2 dup(3), 2 dup(8Ah), 0DCh, 8Ah,	0DCh, 0E7h
		db 0DCh, 0F1h, 0E8h, 2 dup(2), 0DFh, 0E0h, 0E8h, 0E0h
		db 4, 7, 1Ch dup(1Fh), 2 dup(3), 0E7h, 0E8h, 2 dup(0F1h)
		db 0E7h, 0E8h, 0E7h, 0E8h, 0E7h, 8, 2, 0F1h, 0E7h, 0E8h
		db 0E7h, 0E8h, 0E7h, 2 dup(0E8h), 0E2h,	0E1h, 0E2h, 0E1h
		db 0E2h, 0E1h, 0E2h, 0E1h, 1, 8, 8 dup(68h), 3,	8, 6Ah
		db 68h,	69h, 0,	68h, 2 dup(0), 68h, 2 dup(0), 68h, 2 dup(0)
		db 68h,	2 dup(0), 68h, 2 dup(0), 68h, 2	dup(0),	68h, 0
		db 8, 1, 8 dup(0D9h), 8, 2, 0DBh, 0DAh,	0DBh, 0DAh, 0DBh
		db 0DAh, 0DBh, 0DAh, 0E7h, 0E8h, 0F1h, 0E7h, 0E8h, 0E7h
		db 0F1h, 0E8h, 8, 2, 21h, 3Ah, 3Bh, 3Ah, 3Bh, 3Ah, 5, 22h
		db 0, 21h, 5, 21h, 5, 22h, 2 dup(0), 2 dup(1), 3Bh, 2 dup(1)
		db 0BFh, 8, 3, 0D8h, 0D7h, 0D8h, 0D7h, 0D8h, 0D7h, 0D8h
		db 0D7h, 0E8h, 0F1h, 0E7h, 2 dup(0E8h),	0E7h, 0E8h, 0E7h
		db 8 dup(0D9h),	2 dup(5), 4 dup(0), 24h, 3 dup(0), 24h
		db 25h,	2 dup(0), 24h, 2 dup(25h), 0, 24h, 3 dup(25h)
		db 24h,	4 dup(25h), 2 dup(4), 2Ah, 3 dup(0), 25h, 2Ah
		db 2 dup(0), 2 dup(25h), 2Ah, 0, 3 dup(25h), 2Ah, 2 dup(2)
		db 2Bh,	23h, 6Bh, 6Ch, 2, 3, 6Dh, 6Eh, 6Fh, 70h, 71h, 0
		db 8, 7, 2 dup(0), 73h,	72h, 74h, 75h, 2 dup(0), 73h, 72h
		db 4 dup(59h), 74h, 75h, 2 dup(0), 4 dup(54h), 3 dup(0)
		db 55h,	4 dup(54h), 58h, 2 dup(0), 2 dup(54h), 2 dup(5Ah)
		db 2 dup(54h), 2 dup(0), 56h, 54h, 2 dup(5Ah), 54h, 57h
		db 0, 8	dup(0D6h), 3, 2, 0EEh, 0A8h, 0,	2 dup(0EFh), 0A8h
		db 6, 3, 2 dup(51h), 2 dup(0), 2 dup(52h), 51h,	4 dup(53h)
		db 52h,	2 dup(51h), 2 dup(0), 2	dup(52h), 4, 3,	0E4h, 2	dup(0E5h)
		db 0E6h, 3 dup(0C4h), 0C2h, 0C8h, 0C7h,	0C6h, 0C5h, 2 dup(1)
		db 50h,	2, 1, 4Eh, 4Fh,	2 dup(6), 6 dup(0D5h), 6 dup(0D4h)
		db 6 dup(0D5h),	6 dup(0D4h), 6 dup(0D5h), 6 dup(0D4h)
		db 2, 8, 4Ch, 4Dh, 4Ch,	4Dh, 4Ch, 4Dh, 4Ch, 4Dh, 4Ch, 4Dh
		db 4Ch,	4Dh, 4Ch, 4Dh, 4Ch, 4Dh, 4, 1, 49h, 2 dup(4Ah)
		db 4Bh,	5, 2, 2	dup(0),	8 dup(0D3h), 9,	2, 12h dup(0D3h)
		db 0Eh,	2, 0D2h, 0D1h, 0D2h, 0D1h, 0D2h, 0D1h, 0D2h, 0D1h
		db 0D2h, 0D1h, 0D2h, 0D1h, 0D2h, 2 dup(0D1h), 0D2h, 0D1h
		db 0D2h, 0D1h, 0D2h, 0D1h, 0D2h, 0D1h, 0D2h, 0D1h, 0D2h
		db 0D1h, 0D2h, 6, 5, 6 dup(0D5h), 5 dup(0D4h), 0, 3 dup(0D5h)
		db 3 dup(0), 2 dup(0D4h), 4 dup(0), 0D5h, 5 dup(0), 6
		db 5, 6	dup(0D5h), 0, 5	dup(0D4h), 3 dup(0), 3 dup(0D5h)
		db 4 dup(0), 2 dup(0D4h), 5 dup(0), 0D5h, 0Ch, 1, 0Ch dup(0D4h)
		db 8, 2, 0CFh, 0CEh, 0CFh, 0CEh, 0CFh, 0CEh, 0CFh, 2 dup(0CEh)
		db 0CFh, 0CEh, 0CFh, 0CEh, 0CFh, 0CEh, 0CFh, 8,	1, 8 dup(0D0h)
		db 2 dup(3), 0,	8Dh, 0,	0C3h, 8Ch, 8Bh,	46h, 47h, 48h
		db 4, 1, 0C0h, 0C1h, 0C0h, 0C1h, 9, 2, 92h, 3 dup(0), 92h
		db 3 dup(0), 92h, 93h, 3 dup(0), 93h, 3	dup(0),	93h, 2
		db 6, 0FCh, 0FDh, 0FEh,	0FBh, 0FCh, 0FDh, 0FEh,	0FBh, 0FCh
		db 0FDh, 0FEh, 0FBh, 4,	2, 2 dup(0D3h),	2 dup(0), 4 dup(0D3h)
		db 6, 1, 6 dup(0D3h), 5, 6, 0CFh, 0CEh,	94h, 97h, 0, 0CEh
		db 0CFh, 0CEh, 94h, 97h, 0CFh, 0CEh, 94h, 97h, 0, 0CEh
		db 0CFh, 0CEh, 94h, 97h, 0CFh, 0CEh, 94h, 97h, 0, 0CEh
		db 0CFh, 0CEh, 94h, 97h, 5, 6, 0, 96h, 95h, 0CFh, 0CEh
		db 96h,	95h, 0CFh, 0CEh, 0CFh, 0, 96h, 95h, 0CFh, 0CEh
		db 96h,	95h, 0CFh, 0CEh, 0CFh, 0, 96h, 95h, 0CFh, 0CEh
		db 96h,	95h, 0CFh, 0CEh, 0CFh, 8, 1, 8 dup(0CDh), 9, 2
		db 0D2h, 0D1h, 0D2h, 0D1h, 0D2h, 0D1h, 0D2h, 0D1h, 0D2h
		db 0D1h, 0D2h, 0D1h, 0D2h, 0D1h, 0D2h, 0D1h, 0D2h, 0D1h
		db 8, 2, 8Dh, 8Bh, 8Dh,	0, 8Dh,	8Bh, 8Dh, 0, 8Ch, 0C3h
		db 8Ch,	8Bh, 8Ch, 0C3h,	8Ch, 8Bh, 8, 3,	2 dup(35h), 30h
		db 35h,	30h, 35h, 30h, 35h, 8 dup(0A6h), 8 dup(0A2h), 4
		db 3, 39h, 41h,	42h, 30h, 4 dup(0A6h), 0A7h, 3 dup(0A2h)
		db 2 dup(6), 30h, 35h, 30h, 35h, 30h, 35h, 2 dup(30h)
		db 35h,	30h, 35h, 30h, 35h, 2 dup(30h),	35h, 30h, 35h
		db 30h,	35h, 30h, 2 dup(35h), 30h, 35h,	30h, 35h, 30h
		db 35h,	30h, 2 dup(35h), 30h, 35h, 30h,	35h, 2 dup(4)
		db 3 dup(0), 37h, 2 dup(0), 37h, 30h, 0, 37h, 30h, 35h
		db 37h,	35h, 30h, 35h, 2 dup(4), 36h, 3	dup(0),	30h, 36h
		db 2 dup(0), 35h, 30h, 36h, 0, 30h, 35h, 30h, 36h, 2 dup(3)
		db 35h,	30h, 35h, 30h, 35h, 30h, 35h, 2	dup(30h), 2 dup(4)
		db 35h,	30h, 35h, 38h, 30h, 35h, 38h, 0, 35h, 38h
		db 2 dup(0), 38h, 3 dup(0), 2 dup(4), 34h, 30h,	35h, 30h
		db 0, 34h, 30h,	35h, 2 dup(0), 34h, 30h, 3 dup(0), 34h
		db 1, 2, 36h, 30h, 4, 3, 30h, 31h, 32h,	33h, 4 dup(0A6h)
		db 3 dup(0A2h),	0A5h, 8, 3, 8 dup(76h),	8 dup(0A3h), 8 dup(0A4h)
		db 1, 2, 37h, 30h, 1, 2, 2 dup(77h), 1,	2, 2 dup(78h)
		db 4, 6, 4 dup(79h), 7Ah, 2 dup(7Bh), 7Ah, 4 dup(79h)
		db 7Ah,	2 dup(7Bh), 7Ah, 4 dup(79h), 7Ah, 2 dup(7Bh), 7Ah
		db 8, 1, 8 dup(0BFh), 7, 5, 0F1h, 0E7h,	0BDh, 0BEh, 0BDh
		db 0E8h, 0BDh, 0E8h, 0E7h, 0BEh, 0BDh, 0BEh, 0BDh, 0BEh
		db 0E7h, 0F1h, 0BDh, 0BEh, 0BDh, 0F1h, 0BDh, 0E8h, 0E7h
		db 0BEh, 0BDh, 0BEh, 0BDh, 0BEh, 0F1h, 0E8h, 0F1h, 0BEh
		db 0BDh, 0BEh, 0BDh, 7,	5, 0BDh, 0BEh, 0BDh, 0BEh, 0BDh
		db 0E8h, 0F1h, 0BEh, 0BDh, 0BEh, 0E8h, 0BEh, 0E7h, 0F1h
		db 0BDh, 0BEh, 0BDh, 0BEh, 0F1h, 0E7h, 0E8h, 0BEh, 0E7h
		db 0BEh, 0BDh, 0BEh, 0F1h, 0E7h, 0BDh, 0BEh, 0BDh, 0BEh
		db 0BDh, 0E7h, 0E8h, 9,	3, 0BDh, 0BEh, 0BDh, 0BEh, 0BDh
		db 0BEh, 0BDh, 0BEh, 0BDh, 0BEh, 0BDh, 0BEh, 0BDh, 0BEh
		db 0BDh, 0BEh, 0BDh, 0BEh, 7Fh,	0E2h, 7Fh, 0E2h, 2 dup(7Fh)
		db 0E2h, 2 dup(7Fh), 8,	2, 0F5h, 6 dup(0F6h), 0F7h, 0BDh
		db 0BEh, 0BDh, 0BEh, 0BDh, 0BEh, 0BDh, 0BEh, 7,	2, 7 dup(0F9h)
		db 7 dup(0FAh),	3, 4, 9Dh, 2 dup(0), 9Eh, 80h, 0, 9Fh
		db 0A0h, 0A1h, 0BEh, 0BDh, 0BEh, 3, 4, 2 dup(0), 98h, 0
		db 81h,	99h, 9Ch, 9Bh, 9Ah, 0BDh, 0BEh,	0BDh, 8, 1, 0BDh
		db 0BEh, 0BDh, 0BEh, 0BDh, 0BEh, 0BDh, 0BEh, 8,	5, 0F1h
		db 0BEh, 0BDh, 0BEh, 0BDh, 0BEh, 0BDh, 2 dup(0BEh), 0BDh
		db 0BEh, 0BDh, 0BEh, 0BDh, 0BEh, 2 dup(0BDh), 0BEh, 0BDh
		db 0BEh, 0BDh, 0F1h, 0BDh, 2 dup(0BEh),	0BDh, 0BEh, 0BDh
		db 0BEh, 0BDh, 0BEh, 2 dup(0BDh), 0E8h,	0BDh, 0BEh, 0BDh
		db 0BEh, 0BDh, 0BEh, 0Ah, 1, 7Fh, 0E2h,	4 dup(7Fh), 0E2h
		db 7Fh,	0E2h, 7Fh, 4, 2, 8 dup(8Ah), 7,	1, 82h,	2 dup(0)
		db 83h,	2 dup(0), 82h, 10h, 2, 2 dup(0AAh), 0ABh, 0AAh
		db 4 dup(0ABh),	2 dup(0AAh), 0ABh, 3 dup(0AAh),	0ABh, 0AAh
		db 0E7h, 2 dup(0F1h), 0E8h, 0E7h, 0F1h,	2 dup(0E8h), 0E7h
		db 2 dup(0F1h),	0E7h, 0E8h, 0E7h, 0E8h,	0F1h, 8, 2, 0CBh
		db 5 dup(0), 0CAh, 0CBh, 0CAh, 0CBh, 4 dup(0), 0CBh, 0CAh
		db 2, 5, 2 dup(0F9h), 8	dup(0FAh), 2, 1, 0EAh, 0EBh, 5
		db 1, 86h, 3 dup(88h), 87h, 6, 1, 0BAh,	5 dup(0B9h), 8
		db 1, 0BCh, 0BBh, 0BCh,	0BBh, 0BCh, 0BBh, 0BCh,	0BBh, 8
		db 1, 8	dup(0B9h), 6, 4, 0BCh, 0BBh, 0BCh, 0BBh, 0BCh
		db 0BBh, 0BCh, 0BBh, 0BCh, 0BBh, 0BCh, 0BBh, 0BCh, 0BBh
		db 0BCh, 0BBh, 0BCh, 0BBh, 0BCh, 0BBh, 0BCh, 0BBh, 0BCh
		db 0BBh, 6, 5, 0BCh, 0BBh, 0BCh, 0BBh, 0BCh, 0BBh, 0BCh
		db 0BBh, 0BCh, 0BBh, 0BCh, 0, 0BCh, 0BBh, 0BCh,	3 dup(0)
		db 0BCh, 0BBh, 4 dup(0), 0BCh, 5 dup(0), 6, 5, 0BCh, 0BBh
		db 0BCh, 0BBh, 0BCh, 0BBh, 0, 0BBh, 0BCh, 0BBh,	0BCh, 0BBh
		db 3 dup(0), 0BBh, 0BCh, 0BBh, 4 dup(0), 0BCh, 0BBh, 5 dup(0)
		db 0BBh, 2, 3, 0FEh, 0FBh, 0FCh, 0FDh, 0FCh, 0FDh, 4, 2
		db 8 dup(0EDh),	7, 1, 6	dup(0B9h), 0ECh, 4, 2, 2 dup(0)
		db 73h,	72h, 73h, 72h, 2 dup(59h), 4, 2, 74h, 75h, 2 dup(0)
		db 2 dup(59h), 74h, 75h, 8, 2, 10h dup(59h), 2 dup(1)
		db 0FEh, 2 dup(1), 0FCh, 8, 1, 8 dup(0D6h), 0Ah, 1, 0DEh
		db 8 dup(0D9h),	84h, 2,	4, 0EEh, 0BFh, 0EEh, 2 dup(0EFh)
		db 2 dup(3), 0,	2, 1, 0EEh, 0EFh, 1, 5,	0EEh, 0EFh, 0EEh
		db 0EFh, 2 dup(3), 2, 0CFh, 0CEh, 0CFh,	0CEh, 0CFh, 0CEh
		db 3, 2, 0D2h, 0D1h, 0D2h, 0D1h, 0D2h, 0D1h, 26h, 4, 9
		db 2 dup(0), 9,	0, 9, 0, 9, 0, 9, 0, 7Eh, 2 dup(9), 0
		db 7Eh,	2 dup(9), 0, 7Eh, 2 dup(9), 0, 9
		db 2 dup(9), 0,	7Eh, 2 dup(9), 0, 7Eh, 2 dup(9), 0, 7Eh
		db 3 dup(9), 2 dup(0), 9, 0, 9,	0, 9, 0, 9, 0, 9, 0, 9
		db 0, 9, 3 dup(0), 7Dh,	0C9h, 3	dup(0),	9, 2 dup(0), 9
		db 0, 9, 0, 9, 0, 9, 0,	9, 2 dup(0), 9,	2 dup(0), 9, 0
		db 9, 0, 9, 0, 9, 0, 9,	0, 9, 0, 9, 0, 9, 2 dup(0), 7Dh
		db 0C9h, 2 dup(0), 9, 2	dup(0),	9, 0, 9, 0, 9, 0, 9, 0
		db 9, 7Ch, 0, 2	dup(9),	0, 9, 0, 7Dh, 9, 7Ch, 0, 9, 0
		db 9, 0, 9, 0, 2 dup(9), 7Ch, 0, 2 dup(9), 7Ch,	2 dup(0)
		db 9, 2	dup(0),	2 dup(9), 7Ch, 0, 9, 0,	9, 0, 2	dup(9)
		db 7Ch,	9
		;==============================