; ANIMATED OBJECTS GRAPHIX

; ZERO 
loc_8DDD:
		db 6, 17h, 8Ah dup(0)
		
loc_8E69:
		db 6, 17h, 2 dup(0), 0Fh, 5 dup(0)
		db 0FFh, 0F0h, 4 dup(0), 0AAh, 0A0h, 3 dup(0), 0Fh, 2 dup(0FFh)
		db 4 dup(0), 55h, 0A0h,	4 dup(0), 56h, 3Ah, 4 dup(0), 6Ah
		db 0AAh, 4 dup(0), 7Ah,	0A0h, 3	dup(0),	15h, 57h, 80h
		db 2 dup(0), 1,	57h, 0E5h, 0FCh, 2 dup(0), 5, 5Fh, 0A5h
		db 0FFh, 2 dup(0), 5, 5Fh, 0A5h, 0FFh, 2 dup(0), 5, 5Fh
		db 0A9h, 0FCh, 2 dup(0), 5, 5Dh, 0EAh, 0A8h, 2 dup(0)
		db 1, 53h, 0FFh, 0AAh, 4 dup(0), 3Fh, 0F2h, 4 dup(0), 0Ah
		db 80h,	4 dup(0), 1Ah, 5 dup(0), 15h, 5	dup(0),	34h, 5 dup(0)
		db 3Ch,	5 dup(0), 2Ah, 0A8h, 4 dup(0), 3Fh, 0FFh, 2 dup(0)
		
loc_8EF5:
		db 6, 17h, 9 dup(0), 0F0h, 4 dup(0), 0Fh, 0FFh,	4 dup(0)
		db 0Ah,	0AAh, 4	dup(0),	2 dup(0FFh), 0F0h, 3 dup(0), 5
		db 5Ah,	4 dup(0), 5, 63h, 0A0h,	3 dup(0), 6, 0AAh, 0A0h
		db 3 dup(0), 3Ah, 0AAh,	3 dup(0), 15h, 5Fh, 0A0h, 2 dup(0)
		db 1, 57h, 97h,	0F0h, 2	dup(0),	5, 5Ah,	0A5h, 0FCh, 2 dup(0)
		db 5, 6Ah, 0F5h, 0FFh, 2 dup(0), 5, 0AFh, 0F5h,	0FFh, 2	dup(0)
		db 1, 0ADh, 96h, 5Eh, 3	dup(0),	0A3h, 0FFh, 0FAh, 0A8h
		db 0, 0Ah, 80h,	3Fh, 0F0h, 0A2h, 2 dup(0), 2, 8Fh, 0A0h
		db 3 dup(0), 6,	0A0h, 0A9h, 2 dup(0), 0Bh, 0D5h, 0, 15h
		db 0, 0A0h, 3Ah, 0F0h, 0, 17h, 0FAh, 0F0h, 0Fh,	0A8h, 0
		db 3, 0AFh, 2 dup(0), 0FFh, 2 dup(0), 0F0h, 0
		
loc_8F81:
		db 6, 17h
		db 9 dup(0), 0F0h, 4 dup(0), 0Fh, 0FFh,	4 dup(0), 0Ah
		db 0AAh, 4 dup(0), 2 dup(0FFh),	0F0h, 3	dup(0),	5, 5Ah
		db 4 dup(0), 5,	63h, 0A0h, 3 dup(0), 6,	0AAh, 0A0h, 3 dup(0)
		db 3Ah,	0AAh, 3	dup(0),	15h, 5Fh, 0A0h,	2 dup(0), 1, 57h
		db 67h,	0F0h, 2	dup(0),	5, 5Fh,	0A9h, 0FCh, 2 dup(0), 5
		db 5Fh,	0AAh, 0FFh, 2 dup(0), 5, 5Fh, 0FAh, 0AAh, 2 dup(0)
		db 1, 5Dh, 96h,	0AAh, 0A0h, 2 dup(0), 0A3h, 0FFh, 30h
		db 0A8h, 0, 2, 83h, 0FCh, 0F2h,	8, 2 dup(0), 2,	0B3h, 0A0h
		db 3 dup(0), 6,	0A0h, 0A9h, 2 dup(0), 0Bh, 0D5h, 0, 15h
		db 0, 0A0h, 3Ah, 0F0h, 0, 17h, 0FAh, 0F0h, 0Fh,	0A8h, 0
		db 3, 0AFh, 2 dup(0), 0FFh, 2 dup(0), 0F0h, 0
		
loc_900D:
		db 6, 17h
		db 33h dup(0), 0Fh, 5 dup(0), 0FFh, 0F0h, 4 dup(0), 0AAh
		db 0A0h, 3 dup(0), 0Fh,	2 dup(0FFh), 4 dup(0), 55h, 0A0h
		db 2 dup(0), 0Ah, 80h, 56h, 0Ah, 2 dup(0), 0AAh, 0AFh
		db 6Ah,	0AAh, 0, 0Ah, 0A0h, 0ABh, 0FAh,	0A0h, 0, 2, 80h
		db 2Fh,	0FFh, 2	dup(0),	8, 80h,	0D7h, 0EBh, 2Ah, 2 dup(0)
		db 3, 0FCh, 0A9h, 0A6h,	0A0h, 0, 3, 0FFh, 25h, 0E4h, 0A8h
		db 2 dup(0), 0FFh, 0C3h, 0F0h, 88h, 2 dup(0), 2Ah, 0A8h
		db 0A0h, 3 dup(0), 3Fh,	0FFh, 3Ch, 0
		
loc_9099:
		db 6, 17h, 2 dup(0)
		db 0Fh,	5 dup(0), 0FFh,	0F0h, 4	dup(0),	0AAh, 0A0h, 3 dup(0)
		db 0Fh,	2 dup(0FFh), 4 dup(0), 55h, 0A0h, 4 dup(0), 56h
		db 3Ah,	4 dup(0), 6Ah, 0AAh, 4 dup(0), 0AAh, 0A0h, 8, 2	dup(0)
		db 15h,	5Ah, 0,	0AAh, 0, 1, 57h, 0D7h, 0C2h, 0A8h, 0, 5
		db 5Fh,	0E9h, 0FAh, 2 dup(0), 5, 5Fh, 0AAh, 0A8h, 2 dup(0)
		db 5, 5Fh, 0FAh, 0A0h, 2 dup(0), 1, 5Fh, 0F5h, 0FCh, 3 dup(0)
		db 0Dh,	9Fh, 3Ah, 3 dup(0), 3, 0FFh, 0CAh, 90h,	0Ah, 2 dup(0)
		db 3Fh,	0A0h, 5Fh, 0AFh, 3 dup(0), 0A8h, 3Ah, 0F0h, 3 dup(0)
		db 29h,	0Fh, 4 dup(0), 15h, 0C0h, 0A0h,	3 dup(0), 0Fh
		db 0CAh, 0F0h, 3 dup(0), 3, 0AFh, 5 dup(0), 0F0h, 0
		
loc_9125:
		db 6, 17h,	4 dup(0), 0F0h,	4 dup(0), 0Fh
		db 0FFh, 4 dup(0), 0Ah,	0AAh, 4	dup(0),	2 dup(0FFh), 0F0h
		db 3 dup(0), 5,	5Ah, 4 dup(0), 5, 63h, 0A0h, 3 dup(0)
		db 6, 0AAh, 0A0h, 3 dup(0), 3Ah, 0AAh, 3 dup(0), 15h, 5Fh
		db 0A0h, 2 dup(0), 1, 57h, 0A7h, 0F0h, 2 dup(0), 5, 56h
		db 0A9h, 0FCh, 2 dup(0), 5, 5Ah, 0ADh, 0FFh, 2 dup(0)
		db 5, 6Ah, 0F5h, 0FFh, 2 dup(0), 1, 5Ah, 0AFh, 0FCh, 3 dup(0)
		db 0Fh,	0AAh, 0F0h, 3 dup(0), 0Fh, 0FAh, 0C0h, 3 dup(0)
		db 3, 0FEh, 4 dup(0), 2Bh, 0F0h, 4 dup(0), 6Ah,	4 dup(0)
		db 0BDh, 50h, 3	dup(0),	3, 0AFh, 5 dup(0), 0FAh, 80h, 4	dup(0)
		db 0Fh,	0F0h, 3	dup(0)
		
loc_91B1:
		db	6, 17h,	8 dup(0), 0F0h,	4 dup(0)
		db 0Fh,	0FFh, 4	dup(0),	0Ah, 0AAh, 3 dup(0), 2Ah, 2 dup(0FFh)
		db 0F0h, 2 dup(0), 0AAh, 5, 5Ah, 3 dup(0), 0AAh, 5, 63h
		db 0A0h, 2 dup(0), 28h,	6, 0AAh, 0A0h, 2 dup(0), 28h, 0Ah
		db 0AAh, 3 dup(0), 0Ah,	15h, 0A8h, 3 dup(0), 0Ah, 9Dh
		db 5Fh,	0F0h, 2	dup(0),	6, 0AAh, 97h, 0FCh, 2 dup(0), 5
		db 6Ah,	0D7h, 0FFh, 2 dup(0), 5, 5Fh, 0D7h, 0FFh, 2 dup(0)
		db 1, 55h, 96h,	66h, 0A0h, 2 dup(0), 3,	0FFh, 30h, 0A8h
		db 2 dup(0), 3,	0FCh, 0F2h, 8, 2 dup(0), 2, 0B3h, 0A0h
		db 3 dup(0), 6,	0A0h, 0A9h, 2 dup(0), 0Bh, 0D5h, 0, 15h
		db 0, 0A0h, 3Ah, 0F0h, 0, 17h, 0FAh, 0F0h, 0Fh,	0A8h, 0
		db 3, 0AFh, 2 dup(0), 0FFh, 2 dup(0), 0F0h, 0
		
loc_923D:
		db 6, 17h
		db 9 dup(0), 0Fh, 5 dup(0), 0FFh, 0F0h,	4 dup(0), 0AAh
		db 0A0h, 3 dup(0), 0Fh,	2 dup(0FFh), 4 dup(0), 55h, 0A0h
		db 2 dup(0), 2,	80h, 56h, 3Ah, 2 dup(0), 0Ah, 0A1h, 6Ah
		db 0AAh, 2 dup(0), 55h,	75h, 0AAh, 0A0h, 0, 1, 55h, 0D5h
		db 0E8h, 2 dup(0), 5, 57h, 0FFh, 0AAh, 80h, 0, 5, 5Fh
		db 0FEh, 2 dup(0AAh), 0A8h, 5, 5Fh, 0FFh, 5Fh, 2, 0AAh
		db 1, 5Fh, 0FDh, 7Fh, 0, 82h, 0, 0Dh, 96h, 5Ch,	3 dup(0)
		db 3, 0FFh, 0F0h, 4 dup(0), 3Fh, 0F0h, 3 dup(0), 2, 8Fh
		db 0A0h, 3 dup(0), 6, 0A0h, 0A9h, 2 dup(0), 0Bh, 0D5h
		db 0, 15h, 0, 0A0h, 3Ah, 0F0h, 0, 17h, 0FAh, 0F0h, 0Fh
		db 0A8h, 0, 3, 0AFh, 2 dup(0), 0FFh, 2 dup(0), 0F0h, 0
		
loc_92C9:		
		db 6, 17h
		db 20h dup(0), 0F0h, 4 dup(0), 0Fh, 0FFh, 4 dup(0)
		db 0Ah,	0AAh, 4	dup(0),	2 dup(0FFh), 0F0h, 3 dup(0), 5
		db 5Ah,	4 dup(0), 5, 6Ah, 0A0h,	3 dup(0), 6, 0AAh, 0A0h
		db 3 dup(0), 0Ah, 0AAh,	4 dup(0), 0Fh, 0A0h, 3 dup(0)
		db 1, 55h, 70h,	3 dup(0), 15h, 0FBh, 5Ch, 3 dup(0), 55h
		db 0EAh, 5Fh, 3	dup(0),	55h, 0ABh, 5Fh,	3 dup(0), 56h
		db 0AFh, 55h, 2	dup(0),	0Bh, 16h, 0BFh,	6Fh, 0FEh, 0A0h
		db 0Bh,	2, 95h,	0FFh, 0FEh, 0A9h, 0Bh, 2, 0AFh,	0FFh, 0F0h
		db 5, 0FBh, 2Ah, 0ABh, 0FFh, 2 dup(0), 0FBh
		
loc_9355:
		db 6, 17h, 2Dh dup(0)
		db 3Fh,	0FFh, 4	dup(0),	0Ah, 0AAh, 5 dup(0), 0Fh, 5 dup(0)
		db 0Fh,	5 dup(0), 5, 5 dup(0), 29h, 0, 0Fh, 3 dup(0), 28h
		db 0, 0FFh, 0C0h, 2 dup(0), 0A8h, 0, 0FFh, 0AFh, 2 dup(0)
		db 0A8h, 0, 0FAh, 0FCh,	2 dup(0), 0FFh,	0, 0AFh, 0E8h
		db 2 dup(0), 0FFh, 0, 0FDh, 0A8h, 3, 0FFh, 3Fh,	0C0h, 0D5h
		db 0A8h, 35h, 55h, 5Fh,	0F0h, 15h, 0A8h, 0D6h, 0FFh, 0DFh
		db 0F0h, 5, 0AFh, 5Ah, 0AFh, 0DAh, 0A0h, 0, 0BDh, 7Fh
		db 2 dup(0AAh),	8
		
loc_93E1:
		db 6, 17h, 7 dup(0), 0Ch, 1, 3 dup(0)
		db 2, 0Fh dup(0), 40h, 0, 30h, 0, 0F0h,	4 dup(0), 0Fh
		db 0FFh, 4 dup(0), 0Ah,	0AAh, 0, 30h, 2	dup(0),	2 dup(0FFh)
		db 0F0h, 3 dup(0), 5, 5Ah, 4 dup(0), 5,	63h, 0A0h, 3 dup(0)
		db 6, 0AAh, 0A0h, 3 dup(0), 0Ah, 0AAh, 4 dup(0), 0Fh, 0A0h
		db 3 dup(0), 1,	55h, 70h, 3 dup(0), 15h, 0FBh, 5Ch, 3 dup(0)
		db 55h,	0FAh, 5Fh, 3 dup(0), 55h, 0FAh,	5Fh, 3 dup(0)
		db 55h,	0EBh, 55h, 2 dup(0), 0Bh, 15h, 6Bh, 6Fh, 0C0h
		db 0, 0Bh, 0, 29h, 0FFh, 0FCh, 0, 0Bh, 0, 2Ah, 0FFh, 0FEh
		db 0A5h, 0FBh, 2, 0AAh
		db 0BFh, 0FEh, 0A5h, 0FBh
		
loc_946D:
		db 6, 17h
		db 7 dup(0), 4,	6 dup(0)
		db 0F0h, 4, 3 dup(0), 0Fh, 0FFh, 3 dup(0), 0Ch,	0Ah, 0AAh
		db 4 dup(0), 2 dup(0FFh), 0F0h,	4 dup(0), 0A0h,	0, 80h
		db 0, 10h, 1, 0A4h, 4 dup(0), 5, 55h, 4	dup(0),	5, 5Ah
		db 4 dup(0), 5,	6Ah, 0A0h, 3 dup(0), 6,	0AAh, 0A0h, 3 dup(0)
		db 0Ah,	0AAh, 4	dup(0),	0Fh, 0A0h, 3 dup(0), 1,	55h, 70h
		db 3 dup(0), 15h, 0FBh,	5Ch, 3 dup(0), 55h, 0EAh, 5Fh
		db 3 dup(0), 55h, 0ABh,	5Fh, 3 dup(0), 56h, 0AFh, 55h
		db 2 dup(0), 0Bh, 16h, 0BFh, 6Fh, 0FEh,	0A0h, 0Bh, 2, 95h
		db 0FFh, 0FEh, 0A9h, 0Bh, 2, 0AFh, 0FFh, 0F0h, 5, 0FBh
		db 2Ah,	0ABh, 0FFh, 2 dup(0), 0FBh
		
loc_94F9:
		db 6, 17h
		db 4 dup(0), 15h
		db 54h,	4 dup(0), 2 dup(55h), 2	dup(0),	0F0h, 0, 2 dup(55h)
		db 0, 0Fh, 0A0h, 0, 15h, 55h, 0, 0FAh, 0B0h, 3,	7Fh, 0FFh
		db 0, 0A0h, 0F4h, 0Fh, 7Fh, 0FFh, 2 dup(0), 1Ah, 0CFh
		db 0EFh, 0EAh, 2 dup(0), 0Bh, 3Fh, 0F6h, 0ABh, 3 dup(0)
		db 0FFh, 0FAh, 80h, 2 dup(0), 0Ah, 0FFh, 0Ah, 3	dup(0)
		db 5Ah,	0B0h, 0Ah, 2 dup(0), 0Fh, 0D8h,	0, 0Ah,	2 dup(0)
		db 0ABh, 2 dup(0), 22h,	80h, 0,	0FAh, 2	dup(0),	2, 2 dup(0)
		db 0Fh,	0A0h, 0, 2, 3 dup(0), 0F0h, 2Dh	dup(0)
		
loc_9585:
		db	6, 17h
		db 4 dup(0), 15h, 54h, 3 dup(0), 88h, 2	dup(55h), 3 dup(0)
		db 2Ah,	0A9h, 55h, 0, 38h, 0, 0Ah, 0AAh, 95h, 0, 0EBh
		db 0, 23h, 7Eh,	0AFh, 3, 0AFh, 0D0h, 0Fh, 7Fh, 0ABh, 0Eh
		db 80h,	6Ah, 0BFh, 0EFh, 0EAh, 0Ah, 0, 0Ah, 0FFh, 0F7h
		db 0FFh, 3 dup(0), 0FFh, 0C0h, 5 dup(0), 3Ch, 4	dup(0)
		db 3, 0F0h, 4 dup(0), 2, 80h, 4	dup(0),	2, 80h,	4 dup(0)
		db 5, 5	dup(0),	0Dh, 5 dup(0), 0Fh, 5 dup(0), 0Ah, 0A8h
		db 4 dup(0), 0Fh, 0FFh,	1Fh dup(0)
		
loc_9611:
		db 6, 17h
		db 34h	dup(0)
		db 2, 3	dup(0),	3, 0C0h, 22h, 20h, 2 dup(0), 3Fh, 0FCh
		db 0Ah,	80h, 2 dup(0), 2Ah, 0A8h, 2Ah, 2 dup(0), 3, 2 dup(0FFh)
		db 0CAh, 3 dup(0), 2Ah,	94h, 0Ah, 3 dup(0), 3Ah, 0E4h
		db 0Ah,	0, 8, 0, 20h, 0A4h, 0Ah, 0, 88h, 80h, 20h, 2 dup(28h)
		db 0, 2Ah, 0, 8, 0A0h, 0A8h, 0,	0Ah, 82h, 9Fh, 0F6h, 0A0h
		db 0, 0Ah, 2Ah,	0DFh, 0F7h, 80h, 0, 0Ah, 0A8h, 0DFh, 0F7h
		db 2 dup(0), 2,	80h, 0DFh, 0F7h, 4 dup(0), 0DFh, 0F7h
		db 2 dup(0)
		
loc_969D:
		db 6, 17h
		db 31h dup(0), 80h, 4	dup(0),	8, 88h
		db 3, 0C0h, 2 dup(0), 2, 0A0h, 3Fh, 0FCh, 3 dup(0), 0A8h
		db 2Ah,	0A8h, 3	dup(0),	0A3h, 2	dup(0FFh), 0C0h, 2 dup(0)
		db 0A0h, 16h, 0A8h, 3 dup(0), 0A0h, 1Bh, 0ACh, 3 dup(0)
		db 0A0h, 1Ah, 8, 0, 20h, 0, 2 dup(28h),	8, 2, 22h, 0, 2Ah
		db 0Ah,	20h, 0,	0A8h, 0, 0Ah, 9Fh, 0F6h, 82h, 0A0h, 0
		db 2, 0DFh, 0F7h, 0A8h,	0A0h, 2	dup(0),	0DFh, 0F7h, 2Ah
		db 0A0h, 2 dup(0), 0DFh, 0F7h, 2, 80h, 2 dup(0), 0DFh
		db 0F7h, 2 dup(0)

loc_9729:
		db 2, 7, 0FFh, 0FCh, 55h, 57h, 0, 7, 0
		db 7, 0, 7, 0, 7, 0, 7

loc_9739:
		db 2, 7, 0, 7, 0, 7, 0, 7,	0, 7, 0
		db 7, 55h, 57h,	0FFh, 0FCh
		
loc_9749:
		db 2, 7, 0D0h,	0, 0D0h, 0, 0D0h
		db 0, 0D0h, 0, 0D0h, 0,	0D5h, 55h, 3Fh,	0FFh
		
loc_9759:
		db 2, 7, 3Fh
		db 0FFh, 0D5h, 55h, 0D0h, 0, 0D0h, 0, 0D0h, 0, 0D0h, 0
		db 0D0h, 0
		
loc_9769:
		db 3, 4, 2, 80h, 0, 0AAh, 95h,	54h, 0AAh, 0BFh
		db 0FFh, 2, 80h, 0
		
loc_9777:
		db 2, 7, 0Ah, 0A0h, 2,	80h, 0Ah, 0E0h
		db 2Bh,	0B8h, 2Eh, 0ECh, 2Bh, 0B8h, 0Ah, 0E0h
		
loc_9787:
		db 0Ch, 1
		db 0Ch dup(0FFh)
		
loc_9795:
		db 0Ch, 8, 0FFh,	0F0h, 0Bh dup(0), 0Fh
		db 0FFh, 0Ch dup(0), 0FFh, 0F0h, 0Bh dup(0), 0Fh, 0FFh
		db 0Ch dup(0), 0FFh, 0F0h, 0Bh dup(0), 0Fh, 0FFh, 0Ch dup(0)
		db 0FFh, 0F0h, 0Bh dup(0), 0Fh,	0FFh
		
loc_97F7:
		db 0Ah, 10h,	0FCh, 9	dup(0)
		db 3, 0FCh, 9 dup(0), 3
		db 0FCh, 9 dup(0), 3, 0FCh, 9 dup(0), 3, 0FCh, 9 dup(0)
		db 3, 0C0h, 9 dup(0), 3Ch, 9 dup(0), 3,	0C0h, 9	dup(0)
		db 3Ch,	9 dup(0), 3, 0C0h, 9 dup(0), 3Ch, 9 dup(0), 3
		db 0C0h, 9 dup(0), 3Ch,	9 dup(0), 3, 0C0h, 9 dup(0), 3Ch
		db 9 dup(0), 3
		
loc_9899:
		db	8, 19h,	0FFh, 8	dup(0),	0FFh, 8	dup(0)
		db 0FFh, 8 dup(0), 0F0h, 7 dup(0), 0Fh,	8 dup(0), 0F0h
		db 7 dup(0), 0Fh, 8 dup(0), 0F0h, 7 dup(0), 0Ch, 7 dup(0)
		db 3, 8	dup(0),	0C0h, 7	dup(0),	30h, 7 dup(0), 0Ch, 7 dup(0)
		db 3, 8	dup(0),	0C0h, 7	dup(0),	0C0h, 7	dup(0),	30h, 7 dup(0)
		db 30h,	7 dup(0), 0Ch, 7 dup(0), 0Ch, 7	dup(0),	3, 7 dup(0)
		db 3, 7	dup(0),	3, 7 dup(0), 3,	7 dup(0), 3
		
loc_9963:
		db 6,	20h, 0FFh
		db 6 dup(0), 0FFh, 6 dup(0), 0F0h, 5 dup(0), 0Fh, 6 dup(0)
		db 0F0h, 5 dup(0), 0Ch,	5 dup(0), 3, 6 dup(0), 0C0h, 5 dup(0)
		db 30h,	5 dup(0), 0Ch, 5 dup(0), 3, 5 dup(0), 3, 6 dup(0)
		db 0C0h, 5 dup(0), 0C0h, 5 dup(0), 0C0h, 5 dup(0), 30h
		db 5 dup(0), 30h, 5 dup(0), 30h, 5 dup(0), 30h,	5 dup(0)
		db 0Ch,	5 dup(0), 0Ch, 5 dup(0), 0Ch, 5	dup(0),	0Ch, 5 dup(0)
		db 0Ch,	5 dup(0), 3, 5 dup(0), 3, 5 dup(0), 3, 5 dup(0)
		db 3, 5	dup(0),	3, 5 dup(0), 3,	5 dup(0), 3, 5 dup(0)
		db 3
		
loc_9A25:
		db 4, 29h, 0F0h, 3 dup(0), 0Fh, 4 dup(0), 0C0h, 3 dup(0)
		db 30h,	3 dup(0), 0Ch, 3 dup(0), 3, 4 dup(0), 0C0h, 3 dup(0)
		db 0C0h, 3 dup(0), 30h,	3 dup(0), 30h, 3 dup(0), 30h, 3	dup(0)
		db 0Ch,	3 dup(0), 0Ch, 3 dup(0), 0Ch, 3	dup(0),	3, 3 dup(0)
		db 3, 3	dup(0),	3, 4 dup(0), 0C0h, 3 dup(0), 0C0h, 3 dup(0)
		db 0C0h, 3 dup(0), 0C0h, 3 dup(0), 30h,	3 dup(0), 30h
		db 3 dup(0), 30h, 3 dup(0), 30h, 3 dup(0), 30h,	3 dup(0)
		db 30h,	3 dup(0), 30h, 3 dup(0), 0Ch, 3	dup(0),	0Ch, 3 dup(0)
		db 0Ch,	3 dup(0), 0Ch, 3 dup(0), 0Ch, 3	dup(0),	3, 3 dup(0)
		db 3, 3	dup(0),	3, 3 dup(0), 3,	3 dup(0), 3, 3 dup(0)
		db 3, 3	dup(0),	3, 3 dup(0), 3
		
		
loc_9ACB:
		db	1, 30h,	30h dup(0C0h)
		
loc_9AFD:
		db 2 dup(6), 0Fh, 3, 0FCh, 3, 0FCh, 0, 3Fh, 4 dup(0Fh)
		db 0, 5	dup(0Fh), 0, 5 dup(0Fh), 0, 5 dup(0Fh),	0, 3Fh
		db 0C3h, 0FCh, 3, 0FCh,	0
		
loc_9B23:
		db 2 dup(6), 5,	50h, 15h, 54h
		db 5, 50h, 3 dup(14h), 0, 2 dup(14h), 0, 54h, 15h, 50h
		db 2 dup(14h), 5, 50h, 0, 54h, 2 dup(14h), 15h,	0, 4 dup(14h)
		db 15h,	54h, 5,	50h, 5,	50h
		
loc_9B49:
		db 2 dup(6), 2Ah, 0A8h, 0Ah
		db 0A0h, 0Ah, 0A0h, 28h, 0, 4 dup(28h),	2Ah, 0A0h, 4 dup(28h)
		db 0, 0A8h, 0Ah	dup(28h), 0Ah, 0A0h, 0Ah, 0A0h,	0Ah, 0A0h
		
loc_9B6F:
		db 6, 15h, 25h dup(0), 0Fh, 0C0h, 4 dup(0), 3Dh, 70h, 0FCh
		db 3 dup(0), 35h, 57h, 0D7h, 0C0h, 2 dup(0), 0Dh, 97h
		db 55h,	70h, 2 dup(0), 5, 55h, 59h, 70h, 2 dup(0), 35h
		db 65h,	95h, 0C0h, 2 dup(0), 0D6h, 59h,	55h, 0C0h, 2 dup(0)
		db 0D5h, 56h, 65h, 3 dup(0), 0F7h, 0D5h, 57h, 3	dup(0)
		db 3Ch,	33h, 5Fh, 5 dup(0), 0FCh, 1Ah dup(0)
		
loc_9BEF:
		db 6, 15h, 13h dup(0)
		db 0FCh, 0, 0FFh, 2 dup(0), 3, 0D7h, 3,	0D5h, 0C0h, 0
		db 3, 55h, 0F5h, 55h, 40h, 0, 3, 3 dup(55h), 7Ch, 2 dup(0)
		db 0D5h, 55h, 0A5h, 57h, 2 dup(0), 0D5h, 0A5h, 59h, 57h
		db 2 dup(0), 1Ah, 56h, 69h, 5Fh, 2 dup(0), 29h,	2 dup(65h)
		db 0FCh, 0, 3, 65h, 95h, 65h, 0C0h, 0, 0Dh, 2 dup(59h)
		db 95h,	0C0h, 0, 0Dh, 56h, 2 dup(55h), 50h, 0, 0Fh, 55h
		db 59h,	0A5h, 5Ch, 0, 3, 0D5h, 0D6h, 95h, 5Fh, 2 dup(0)
		db 35h,	55h, 57h, 0D7h,	3 dup(0), 0F5h,	0C0h, 3Ch, 3 dup(0)
		db 3Fh,	0Fh dup(0)
		
loc_9C6F:
		db 6, 15h, 20h, 2 dup(0), 20h,	0, 28h
		db 2 dup(8), 0,	0A8h, 2, 0A0h, 0Ah, 0, 0FCh, 0A8h, 0Ah
		db 80h,	2, 0A3h, 0DFh, 0C8h, 0FAh, 0, 2, 0A3h, 55h, 77h
		db 7Ch,	2 dup(0), 2Fh, 59h, 55h, 5Ch, 0, 2, 0Dh, 55h, 59h
		db 5Ch,	0, 28h,	15h, 5Ah, 55h, 70h, 2 dup(0), 0D9h, 2 dup(55h)
		db 42h,	80h, 3,	55h, 66h, 65h, 7Ah, 0A8h, 3, 56h, 59h
		db 95h,	7Eh, 0,	3, 0D5h, 55h, 59h, 5Ch,	2 dup(0), 0FFh
		db 0D5h, 95h, 0F0h
		db 0, 20h, 2Fh,	25h, 56h, 0, 20h, 0, 0AAh, 0Dh,	5Eh, 80h
		db 20h,	0, 0A8h, 0Dh, 0FAh, 0A0h, 0, 2,	80h, 0Bh, 0C2h
		db 0A8h, 0, 0Ah, 0, 28h, 0, 0Ah, 0, 20h, 0, 2 dup(28h)
		db 0, 80h, 2 dup(0), 20h, 9 dup(0)
	
loc_9CEF:
		db 6, 10h, 11h	dup(0)
		db 20h,	5 dup(0), 28h, 5 dup(0), 0A9h, 0, 0A8h,	2 dup(0)
		db 2, 0A4h, 2, 0Ah, 7Fh, 0FFh, 0AAh, 50h, 3Eh, 0A5h, 7Fh
		db 2 dup(0FFh),	0, 73h,	0AAh, 5Fh, 0FFh, 0F5h, 50h, 4Ch
		db 0Ah,	85h, 55h, 50h, 3 dup(0), 0A2h, 68h, 5 dup(0), 10h
		db 4 dup(0), 5,	40h, 4 dup(0), 11h, 0Fh	dup(0)
		
loc_9D51:
		db	6, 10h
		db 2 dup(0), 5,	55h, 0A0h, 3 dup(0), 5Fh, 0FFh,	0FAh, 0A0h
		db 0, 1, 0FFh, 2 dup(0AAh), 80h, 0, 7, 2 dup(0FFh), 0AAh
		db 2 dup(0), 7,	0FAh, 0AAh, 0A0h, 20h, 0, 7, 0FFh, 0FAh
		db 0, 28h, 0, 1, 0FAh, 0A8h, 0,	0A9h, 0, 0AAh, 7Fh, 0A0h
		db 2, 0A4h, 2, 0Ah, 9Fh, 0FAh, 0AAh, 50h, 3Eh, 0AAh, 9Fh
		db 0EAh, 0A9h, 0, 7Fh, 3 dup(0AAh), 0A0h, 0, 40h, 0Ah
		db 2 dup(8Ah), 4 dup(0), 0A2h, 68h, 5 dup(0), 10h, 4 dup(0)
		db 5, 40h, 4 dup(0), 11h, 3 dup(0)
		
loc_9DB3:
		db 6, 10h, 5 dup(0), 20h
		db 5 dup(0), 28h, 5 dup(0), 0A9h, 0, 0AAh, 2 dup(0), 2
		db 0A4h, 2, 0Ah, 8Ah, 2	dup(0AAh), 50h,	3Eh, 0AAh, 0ABh
		db 2Ah,	0A9h, 0, 0FFh, 0AAh, 9Fh, 8Ah, 0A0h, 0,	0C0h, 0Ah
		db 7Eh,	8Ah, 4 dup(0), 7Eh, 0A0h, 4 dup(0), 7Fh, 0AAh
		db 0A9h, 3 dup(0), 17h,	0FFh, 0FDh, 50h, 2 dup(0), 1, 2	dup(55h)
		db 19h dup(0)
		
loc_9E15:		
		db 2, 15h, 5 dup(0), 0F0h, 9 dup(0), 0F0h
		db 2 dup(0), 3,	0C0h, 0, 0F0h, 7 dup(0), 0F0h, 4 dup(0)
		db 0Fh,	0Ch, 30h, 0F0h,	0Fh, 3 dup(0)
		
loc_9E41:		
		db 2, 15h, 2 dup(0)
		db 0Fh,	0Ah dup(0), 0F0h, 3 dup(0), 0F0h, 6 dup(0), 0Fh
		db 0, 30h, 0C0h, 3Fh, 0C0h, 0Fh, 6 dup(0), 0F0h, 4 dup(0)
		
loc_9E6D:
		db 2, 15h, 2 dup(0), 0Fh, 6 dup(0), 0F0h, 3 dup(0), 0F0h
		db 5 dup(0), 0F0h, 3, 0Ch, 3, 0F0h, 9 dup(0), 0F0h, 4 dup(0)
		db 0Fh,	3 dup(0)
		
loc_9E99:
		db 6, 17h, 2 dup(0), 0FFh, 3 dup(0), 30h
		db 0Fh,	14h, 0F0h, 3 dup(0), 0F0h, 55h,	4Fh, 2 dup(0)
		db 0Fh,	45h, 55h, 54h, 0C0h, 0,	35h, 3 dup(55h), 30h, 2	dup(0)
		db 55h,	1, 45h,	5Ch, 0,	15h, 0,	54h, 15h, 55h, 40h, 5
		db 3 dup(55h), 41h, 50h, 0, 2 dup(55h),	5, 0, 54h, 0Fh
		db 5, 54h, 50h,	0, 14h,	2 dup(0), 55h, 2 dup(0), 14h, 30h
		db 4 dup(0), 14h, 3 dup(0), 28h, 0, 14h, 2 dup(0), 2, 0BEh
		db 80h,	50h, 3 dup(0), 28h, 5, 40h, 3 dup(0), 1, 54h, 4	dup(0)
		db 15h,	42h, 80h, 3 dup(0), 50h, 2Bh, 0E8h, 2 dup(0), 1
		db 40h,	2, 80h,	2 dup(0), 51h, 40h, 4 dup(0), 5, 44h, 4	dup(0)
		db 1, 50h, 4 dup(0), 5,	40h, 2 dup(0)
		
loc_9F25:		
		db 6, 17h, 0, 3, 0C0h
		db 0FFh, 3 dup(0), 0Dh,	7Fh, 54h, 0F0h,	2 dup(0), 34h
		db 1, 55h, 4Fh,	3 dup(0), 54h, 5, 54h, 0C0h, 2 dup(0)
		db 1, 51h, 55h,	30h, 3 dup(0), 4, 15h, 30h, 3 dup(0), 51h
		db 55h,	54h, 2 dup(0), 5, 45h, 51h, 14h, 0, 15h, 54h, 55h
		db 5, 14h, 0, 5, 51h, 2	dup(50h), 14h, 2 dup(0), 15h, 55h
		db 0, 14h, 5 dup(0), 50h, 4 dup(0), 5, 40h, 2 dup(0), 28h
		db 0, 54h, 2 dup(0), 2,	0BEh, 85h, 40h,	3 dup(0), 28h
		db 14h,	28h, 4 dup(0), 52h, 0BEh, 80h, 3 dup(0), 50h, 28h
		db 3 dup(0), 1,	40h, 4 dup(0), 51h, 40h, 4 dup(0), 5, 44h
		db 4 dup(0), 1,	50h, 4 dup(0), 5, 40h, 2 dup(0)
		
loc_9FB1:
		db 6, 17h
		db 2 dup(0), 0Fh, 0F0h,	4 dup(0), 0F5h,	5Fh, 3 dup(0)
		db 0Fh,	50h, 5,	0F0h, 2	dup(0),	35h, 5,	50h, 5Ch, 2 dup(0)
		db 0D4h, 50h, 5, 17h, 2	dup(0),	55h, 2 dup(0), 55h, 2 dup(0)
		db 50h,	2 dup(0), 5, 2 dup(0), 14h, 50h, 5, 14h, 2 dup(0)
		db 2 dup(5), 2 dup(50h), 3 dup(0), 50h,	5, 4 dup(0), 5
		db 50h,	4 dup(0), 1, 40h, 4 dup(0), 1
		db 40h,	28h, 4 dup(0), 52h, 0BEh, 80h, 3 dup(0), 14h, 28h
		db 2 dup(0), 0Ah, 0, 14h, 3 dup(0), 0AFh, 0A0h,	50h, 3 dup(0)
		db 0Ah,	1, 40h,	4 dup(0), 1, 41h, 4 dup(0), 11h, 44h, 4	dup(0)
		db 11h,	50h, 4 dup(0), 5, 40h, 4 dup(0), 1, 40h, 2 dup(0)
		
loc_A03D:
		db 4, 0Eh, 2Ah,	2 dup(0AAh), 0A8h, 2 dup(33h), 2 dup(0CCh)
		db 2Ah,	2 dup(0AAh), 0A8h, 0Fh,	0FCh, 0Fh, 0F0h, 3, 0F0h
		db 3Fh,	0C0h, 0, 2 dup(0FFh), 2	dup(0),	0Fh, 0F0h, 2 dup(0)
		db 0Ah,	80h, 2 dup(0), 2Ah, 3 dup(0), 0A8h, 2 dup(0), 2
		db 0A0h, 2 dup(0), 0Ch,	80h, 2 dup(0), 3Fh, 3 dup(0), 3Fh
		db 3 dup(0)
		
loc_A077:
		db 4,	0Eh, 2Ah, 2 dup(0AAh), 0A8h, 2 dup(33h)
		db 2 dup(0CCh),	2Ah, 2 dup(0AAh), 0A8h,	0Fh, 0F0h, 3Fh
		db 0F0h, 3, 0FCh, 0Fh, 0C0h, 0,	2 dup(0FFh), 2 dup(0)
		db 0Fh,	0F0h, 2	dup(0),	2, 0A0h, 3 dup(0), 0A8h, 3 dup(0)
		db 2Ah,	3 dup(0), 0Ah, 80h, 2 dup(0), 2, 30h, 3	dup(0)
		db 0FCh, 3 dup(0), 0FCh
		
loc_A0B1:
		db 5, 6, 6 dup(0), 2, 82h, 80h, 2	dup(0)
		db 0Bh,	0EBh, 0E0h, 2 dup(0), 2, 82h, 80h, 0Bh dup(0)
		
loc_A0D1:
		db 5, 6, 6 dup(0), 2Ah,	82h, 0A8h, 2 dup(0), 0B3h, 0AAh
		db 0CEh, 2 dup(0), 0B3h, 0AAh, 0CEh, 2 dup(0), 2Ah, 82h
		db 0A8h, 6 dup(0)
		
loc_A0F1:		
		db 5, 6, 2, 0AAh, 0, 0AAh, 80h,	0Bh, 0FEh
		db 82h,	0BFh, 0E0h, 2Fh, 0Fh, 0AAh, 0F0h, 0F8h,	2Fh, 0Fh
		db 0AAh, 0F0h, 0F8h, 0Bh, 0FEh,	82h, 0BFh, 0E0h, 2, 0A8h
		db 0, 2Ah, 80h
		
loc_A111:
		db	5, 6, 2, 2Ah, 0, 0A8h, 80h, 8, 0AAh, 82h
		db 0AAh, 20h, 2Ah, 3 dup(0AAh),	0A8h, 2Bh, 0Fh,	0AAh, 0F0h
		db 0E8h, 0Ah, 0FEh, 82h, 0BFh, 0A0h, 2,	0A8h, 0, 2Ah, 80h
		
		
loc_A131:
		db 6, 14h, 3 dup(0), 2,	0AAh, 2	dup(0),	0Ah, 80h, 0Ah
		db 2Ah,	80h, 3,	0EAh, 0A3h, 0C8h, 0BAh,	80h, 0Ch, 3Ah
		db 0F8h, 0F0h, 0AFh, 0C0h, 0Ch,	8Ah, 28h, 30h, 0Ah, 80h
		db 2, 0AEh, 0ABh, 0C0h,	0Ah, 80h, 0, 0B3h, 0A8h, 0, 0AAh
		db 80h,	0, 0BFh, 0A0h, 2 dup(0AAh), 2 dup(0), 0BFh, 8Ah
		db 0AAh, 0A0h, 2 dup(0), 2 dup(2Ah), 0AAh, 8, 3	dup(0)
		db 2Ah,	0A8h, 0AAh, 0A0h, 2 dup(0), 3 dup(0AAh), 0BCh
		db 2 dup(0), 8Ah, 0A0h,	2Ah, 0BCh, 2 dup(0), 0A2h, 0Ah
		db 0AAh, 0A0h, 0, 2, 0A0h, 0AAh, 0A8h, 2 dup(0), 0Ah, 82h
		db 0AAh, 2, 0A0h, 0, 2Ah, 0Ah, 0A0h, 0,	0A8h, 0, 88h, 2
		db 0A0h, 0, 0A8h, 0, 0B0h, 2, 0A8h, 0, 0A8h, 0,	0AFh, 3Ah
		db 0AAh, 0Eh, 0A8h
		
loc_A1AB:
		db 6, 14h, 7 dup(0), 0A8h, 4 dup(0), 3Eh
		db 0AAh, 3Ch, 3	dup(0),	0C3h, 0AFh, 8Fh, 3 dup(0), 0C8h
		db 0A2h, 83h, 3	dup(0),	2Ah, 0EAh, 0BCh, 3 dup(0), 0Bh
		db 3Ah,	80h, 3 dup(0), 0Bh, 0FAh, 0Ah, 0A0h, 2 dup(0)
		db 0Bh,	0F8h, 2	dup(0AAh), 80h,	0, 2, 2	dup(0A2h), 2 dup(0AAh)
		db 3 dup(0), 0Ah, 0A0h,	0AAh, 0A0h, 0Ch, 2, 0AAh, 8Ah
		db 0AAh, 0BCh, 2, 2 dup(0AAh), 2Ah, 0AAh, 0BCh,	3Ah, 0AAh
		db 0, 2	dup(0AAh), 0A0h, 0, 2 dup(0A0h), 0AAh, 0A8h, 0
		db 3, 0Ah, 82h,	0AAh, 2, 0A0h, 0, 2Ah, 0Ah, 0A0h, 0, 0A8h
		db 0, 88h, 2, 0A0h, 0, 0A8h, 0,	0B0h, 2, 0A8h, 0, 0A8h
		db 0, 0AFh, 3Ah, 0AAh, 0Eh, 0A8h
		
loc_A225:		
		db 6, 16h, 2 dup(0), 7
		db 2 dup(0), 40h, 0, 0Ah, 95h, 0F0h, 5,	54h, 0,	0Ah, 95h
		db 7Ch,	10h, 41h, 0, 3,	0FFh, 0FCh, 0, 40h, 2, 0AAh, 0Ah
		db 28h,	0, 40h,	0Ah, 82h, 0AAh,	0A0h, 2, 0A0h, 0Ah, 8
		db 0A2h, 80h, 2, 0A0h, 0, 2Ah, 8Ah, 0AFh, 0Ah, 40h, 0
		db 2 dup(0Ah), 0BEh, 8Ah, 3 dup(0), 3Bh, 0FAh, 0AAh, 3 dup(0)
		db 0FFh, 0F0h, 0A8h, 3 dup(0), 0DFh, 0FEh, 4 dup(0), 37h
		db 0E9h, 40h, 3	dup(0),	0Ah, 95h, 40h, 3 dup(0), 4, 55h
		db 40h,	3 dup(0), 2 dup(15h), 40h, 3 dup(0), 54h, 5, 50h
		db 2 dup(0), 2,	90h, 1,	68h, 0,	0Ah, 82h, 80h, 0, 2Ah
		db 0, 5, 0AAh, 80h
		db 0, 0Ah, 80h,	0, 5Ah,	2 dup(0), 0AAh,	0A0h, 0, 5, 0
		db 1, 55h, 50h
		
loc_A2AB:
		db	6, 16h,	2 dup(0), 1Ch, 4 dup(0), 2Ah, 57h
		db 0C0h, 3 dup(0), 2Ah,	55h, 0F0h, 3 dup(0), 0Fh, 0FFh
		db 0F0h, 2 dup(0), 0Ah,	0A8h, 2Ah, 0A0h, 2 dup(0), 2Ah
		db 0Ah,	0AAh, 80h, 2 dup(0), 28h, 22h, 8Ah, 4 dup(0), 0AAh
		db 0, 0FCh, 3 dup(0), 28h, 0Ah,	0AFh, 4	dup(0),	0AAh, 0ABh
		db 3 dup(0), 2 dup(0AAh), 0Fh, 28h, 0, 0Ah, 0AAh, 0A0h
		db 0BEh, 2Ah, 80h, 2Ah,	0, 0Fh,	0E9h, 4Ah, 0, 82h, 0, 0Ah
		db 95h,	48h, 80h, 2 dup(0), 4, 55h, 40h, 3 dup(0), 2 dup(15h)
		db 40h,	3 dup(0), 54h, 5, 50h, 2 dup(0), 2, 90h, 1, 68h
		db 2 dup(0), 2,	80h, 0,	2Ah, 2 dup(0), 2, 80h, 0, 0Ah
		db 80h,	0, 0AAh, 0A0h, 0, 0AAh,	0A0h, 1, 55h, 50h, 1, 55h
		db 50h
		
loc_A331:	
		db 6, 15h,	3 dup(0), 2, 0A8h, 4 dup(0), 0Bh, 0EAh
		db 4 dup(0), 0ABh, 0E2h, 3 dup(0), 0Ah,	0AAh, 0A2h, 2 dup(0)
		db 2, 80h, 0FAh, 8Ah, 0, 0Eh, 0FEh, 0BFh, 3Eh, 0AAh, 0
		db 6, 56h, 95h,	3Eh, 0A8h, 2 dup(0), 2,	0A0h, 0F0h, 2Ah
		db 80h,	2 dup(0), 0A8h,	0Ah, 0AAh, 80h,	2 dup(0), 3 dup(0AAh)
		db 0A0h, 2 dup(0), 2Ah,	0A0h, 2Ah, 0A0h, 2 dup(0), 2, 8Eh
		db 0ABh, 0F0h, 3 dup(0), 0Fh, 0FFh, 0F0h, 3 dup(0), 0Fh
		db 0FFh, 5 dup(0), 0F8h, 5 dup(0), 0AAh, 5 dup(0), 0AAh
		db 80h,	4 dup(0), 2Ah, 80h, 4 dup(0), 2Ah, 80h,	3 dup(0)
		db 2Ah,	0AAh, 4	dup(0),	2 dup(0AAh), 0
		
loc_A3B1:
		db	6, 15h,	3 dup(0)
		db 2Ah,	80h, 4 dup(0), 0BAh, 0A0h, 3 dup(0), 0Ah, 0BEh
		db 20h,	3 dup(0), 2 dup(0AAh), 20h, 2 dup(0), 28h, 0Fh
		db 0E8h, 0A0h, 0, 0EFh,	0EBh, 0F3h, 0EAh, 80h, 0, 65h
		db 69h,	53h, 0EAh, 0A8h, 2 dup(0), 2Ah,	0Fh, 2Ah, 0AAh
		db 2 dup(0), 0Ah, 80h, 2 dup(0AAh), 80h, 0, 0Ah, 3 dup(0AAh)
		db 0A0h, 0, 2, 0AAh, 0A0h, 2Ah,	0A0h, 2	dup(0),	2Ah, 0Eh
		db 0ABh, 0F0h, 3 dup(0), 0Fh, 0FFh, 0F0h, 3 dup(0), 0Fh
		db 0FFh, 0A0h, 4 dup(0), 0FAh, 0A0h, 3 dup(0), 2, 8Ah
		db 0A0h, 3 dup(0), 2, 0A2h, 0A0h, 3 dup(0), 0Ah, 80h, 0A8h
		db 3 dup(0), 0Ah, 80h, 0A8h, 2 dup(0), 2, 0AAh,	2Ah, 0A8h
		db 2 dup(0), 0Ah, 0A8h,	0AAh, 0A8h
		
loc_A431:
		db 6, 16h, 0Ah, 2 dup(0)
		db 2, 0A0h, 0, 0AAh, 95h, 55h, 56h, 0A5h, 54h, 0Ah, 0
		db 0BAh, 0A2h, 0A0h, 2 dup(0), 0Ah, 0FEh, 20h, 0A0h, 2 dup(0)
		db 2 dup(0AAh),	20h, 0A0h, 2 dup(0), 3Fh, 0A8h,	2 dup(0A0h)
		db 2 dup(0), 3,	0EAh, 82h, 0A0h, 2 dup(0), 3Fh,	2 dup(0AAh)
		db 80h,	3 dup(0), 2Ah, 0AAh, 4 dup(0), 0AAh, 0A0h, 4 dup(0)
		db 0AAh, 8Ah, 4	dup(0),	2Ah, 0AAh, 4 dup(0), 6,	0A9h, 40h
		db 3 dup(0), 5,	55h, 40h, 3 dup(0), 5, 55h, 80h, 3 dup(0)
		db 2Ah,	5Ah, 80h, 3 dup(0), 0AAh, 0Ah, 0A0h, 0,	2 dup(2)
		db 0A0h, 2, 0A8h, 0, 0Ah, 82h, 80h, 0, 2Ah, 0, 0Ah, 0AAh
		db 80h,	8, 0Ah,	80h, 0,	0AAh, 0, 2, 0AAh, 0A0h,	0, 0Ah
		db 0, 0Ah, 0AAh, 0A0h
		
loc_A4B7:		
		db 6, 16h, 8 dup(0), 0AAh, 4 dup(0)
		db 2, 0EAh, 80h, 3 dup(0), 2Bh,	0F8h, 80h, 2 dup(0), 2
		db 0AAh, 0A8h, 80h, 3 dup(0), 0FEh, 0A2h, 80h, 3 dup(0)
		db 0Fh,	0AAh, 4	dup(0),	0FEh, 0A0h, 0A8h, 4 dup(0), 0Ah
		db 0AAh, 4 dup(0), 2 dup(0AAh),	3 dup(0), 2 dup(0AAh)
		db 0Ah,	28h, 0,	0Ah, 0AAh, 0A0h, 0AAh, 2Ah, 80h, 2Ah, 0
		db 6, 0A9h, 4Ah, 0, 82h, 0, 5, 55h, 48h, 80h, 2	dup(0)
		db 5, 55h, 80h,	3 dup(0), 2Ah, 5Ah, 80h, 3 dup(0), 0A8h
		db 0Ah,	0A0h, 2	dup(0),	2, 0A0h, 2, 0A8h, 2 dup(0), 2
		db 80h,	0, 2Ah,	0, 8, 2, 80h, 8, 0Ah, 80h, 2, 0AAh, 0A0h
		db 2, 0AAh, 0A0h, 0Ah, 0AAh, 0A0h, 0Ah,	0AAh, 0A0h
		
loc_A53D:		
		db 6
		db 14h,	2 dup(0), 0FCh,	3 dup(0), 55h, 3, 0C1h,	42h, 0A8h
		db 0, 54h, 0Fh,	0, 17h,	0AAh, 0, 41h, 7Ch, 0
		db 0ADh, 62h, 2	dup(0),	0BEh, 0Ah, 0AAh, 96h, 28h, 0, 0BAh
		db 3, 0FAh, 89h, 4Ah, 0, 0FAh, 80h, 3Eh, 0A5h, 2Ah, 0
		db 0F2h, 0ABh, 0F2h, 50h, 0Ah, 0, 0F0h,	0A8h, 5, 0A8h
		db 8, 0, 0F0h, 0, 5Ah, 0AAh, 28h, 0, 0F0h, 5, 0AAh, 0Ah
		db 0A8h, 0, 3Ch, 5Ah, 0AAh, 0A2h, 0A0h,	0, 0Fh,	8, 0AAh
		db 2 dup(80h), 0, 0Ah, 0A6h, 0AAh, 3 dup(0), 2Ah, 0A5h
		db 55h,	40h, 2 dup(0), 2Ah, 25h, 55h, 40h, 0A0h, 0, 0Ah
		db 89h,	55h, 82h, 0A8h,	0, 2, 81h, 5Ah,	8Ah, 0A8h, 2, 0AAh
		db 0A0h, 42h, 0A8h, 28h, 0Ah, 0AAh, 0A0h, 0, 0A0h, 0A8h

loc_A5B7:		
		db 6, 14h, 2 dup(0), 0FCh, 4 dup(0), 3,	0C0h, 2, 0A8h
		db 2 dup(0), 0Fh, 0, 0Bh, 0AAh,	2 dup(0), 3Ch, 0, 0AFh
		db 0E2h, 20h, 0, 0BEh, 0Ah, 0AAh, 0A2h,	8, 0, 0BAh, 3
		db 0FAh, 8Ah, 0Ah, 0, 0FAh, 80h, 3Eh, 0A8h, 2Ah, 0, 0F2h
		db 0ABh, 0F2h, 0A0h, 0Ah, 0, 0F0h, 0A8h, 0Ah, 0A8h, 8
		db 0, 0F0h, 0, 2 dup(0AAh), 28h, 0, 0F0h, 2, 0AAh, 0Ah
		db 0A8h, 0, 3Ch, 0Ah, 0AAh, 0A2h, 0A0h,	0, 0Fh,	8, 0AAh
		db 2 dup(80h), 0, 0Ah, 0A6h, 0AAh, 3 dup(0), 2Ah, 0A5h
		db 55h,	40h, 2 dup(0), 2Ah, 25h, 55h, 40h, 0A0h, 0, 0Ah
		db 89h,	55h, 82h, 0A8h,	0, 2, 81h, 5Ah,	8Ah, 0A8h, 2, 0AAh
		db 0A0h, 42h, 0A8h, 28h, 0Ah, 0AAh, 0A0h, 0, 0A0h, 0A8h
		
loc_A631:		
		db 6, 15h, 3, 4	dup(0),	0Ch, 3,	0C0h, 2	dup(55h), 50h
		db 3Ch,	0, 0FDh, 6Ah, 0AAh, 97h, 0F0h, 0, 35h, 0BFh, 0FFh
		db 0E5h, 0C0h, 0, 6, 2 dup(0F0h), 0F9h,	0, 0Ah,	6, 0F3h
		db 0Ch,	0F9h, 0, 2Ah, 85h, 0BFh, 0FFh, 0E5h, 0,	2Ah, 0A4h
		db 6Ch,	0F3h, 91h, 0, 28h, 0A0h, 51h, 4, 50h, 0, 8, 0A4h
		db 5, 55h, 3 dup(0), 65h, 40h, 0A0h, 3 dup(0), 45h, 54h
		db 5, 40h, 2 dup(0), 54h, 2 dup(55h), 50h, 2 dup(0), 10h
		db 5, 2	dup(50h), 2 dup(0), 4, 0, 5, 40h, 2 dup(0), 4
		db 5, 55h, 50h,	3 dup(0), 5, 55h, 4 dup(0), 1, 15h, 50h
		db 2 dup(0), 2,	5, 55h,	40h, 3 dup(0), 0AAh, 85h, 50h
		db 2 dup(0), 2,	0AAh, 0A1h, 55h, 40h
		
loc_A6B1:
		db 6, 15h, 3, 4 dup(0)
		db 0Ch,	3, 0C0h, 2 dup(55h), 50h, 3Ch, 0, 0FDh,	6Ah, 0AAh
		db 97h,	0F0h, 0, 35h, 0BFh, 0FFh, 0E5h,	0C0h, 0, 6, 2 dup(0F0h)
		db 0F9h, 2 dup(0), 6, 0F3h, 0Ch, 0F9h, 2 dup(0), 5, 0BFh
		db 0FFh, 0E5h, 2 dup(0), 4, 6Ch, 0F3h, 91h, 3 dup(0), 51h
		db 4, 50h, 3 dup(0), 5,	55h, 5 dup(0), 0A0h, 4 dup(0)
		db 1, 5, 40h, 0, 1, 40h, 15h, 55h, 50h,	0, 0Ah,	2 dup(55h)
		db 2 dup(50h), 0, 2Ah, 95h, 40h, 5, 40h, 0, 2Ah, 85h, 5
		db 55h,	50h, 0,	28h, 94h, 5, 55h, 2 dup(0), 8, 4, 1, 15h
		db 50h,	0, 1, 6, 5, 55h, 40h, 0, 30h, 0C0h, 0AAh, 85h
		db 50h,	0, 4, 2, 0AAh, 0A1h, 55h, 40h
		
loc_A731:		
		db 2, 7, 0Ah, 0A0h
		db 2Ah,	88h, 0AAh, 0A2h, 0AAh, 88h, 0AAh, 0A2h,	2Ah, 88h
		db 0Ah,	0A0h
		
loc_A741:		
		db 2, 8, 3 dup(0), 10h, 0, 4, 0, 4, 2 dup(55h)
		db 0, 4, 0, 4, 0, 10h
		
loc_A753:		
		db 2, 8, 1,	0, 1, 0, 1, 0, 1, 0, 1
		db 0, 41h, 4, 15h, 50h,	1, 0
		
loc_A765:		
		db 2, 8, 4, 0, 10h, 0, 10h
		db 0, 2	dup(55h), 10h, 0, 10h, 0, 4, 3 dup(0)
		
loc_A777:		
		db 2, 8, 0
		db 40h,	5, 54h,	10h, 41h, 0, 40h, 0, 40h, 0, 40h, 0, 40h
		db 0, 40h
		
loc_A789:
		db 2, 5, 3 dup(0), 54h,	3Fh, 50h, 0, 54h, 2 dup(0)
		
loc_A795:
		db 6, 3, 0Ah, 5	dup(0),	0AAh, 95h
		db 4 dup(55h), 0Ah, 5 dup(0)
	
loc_A7A9:	
		db 3, 8, 0FFh, 2 dup(0), 0FCh
		db 2 dup(0), 0C3h, 0C0h, 2 dup(0), 3Ch,	28h, 0,	3, 0EAh
		db 0, 2, 0BCh, 0, 2, 80h, 2 dup(0), 80h
		
loc_A7C3:
		db 4, 0Ch, 0Fh, 0
		db 0Fh,	0F0h, 3Fh, 0CFh, 0F0h, 0FCh, 0Ch, 3Fh, 0CFh, 0
		db 0Fh,	2 dup(0F3h), 0F0h, 3Fh,	0CFh, 0F3h, 0F0h, 3Fh
		db 0FFh, 2 dup(0FCh), 33h, 0FFh, 2 dup(0FCh), 0Fh, 0CFh
		db 0C3h, 0F0h, 0, 0F0h,	3Fh, 0,	0Fh, 3Fh, 0F0h,	0, 3Fh
		db 0C0h, 2 dup(0), 0Fh,	3 dup(0)
		
loc_A7F5:		
		db 4, 0Ch, 2 dup(0), 0Fh
		db 2 dup(0), 0FCh, 3Ch,	0C0h, 3, 0FFh, 0Fh, 0, 0Fh, 0F3h
		db 0C0h, 0, 0Fh, 0, 3Fh, 2 dup(0), 2 dup(0FFh),	0C0h, 0Fh
		db 0C3h, 0F3h, 0F0h, 0Fh, 3Fh, 0F3h, 0C0h, 3, 0FFh, 0Fh
		db 5 dup(0), 3,	0FCh, 3	dup(0),	0F0h, 2	dup(0)
		
loc_A827:
		db	4, 0Ch
		db 8 dup(0), 0Fh, 3 dup(0), 3Fh, 0C0h, 0Fh, 0, 0Fh, 4 dup(0)
		db 0FFh, 2 dup(0), 0Fh,	0FCh, 0F0h, 0, 0Fh, 0FFh, 0F0h
		db 0, 3, 0FFh, 4 dup(0), 3, 9 dup(0)
		
loc_A859:		
		db 6, 0Eh, 0, 8Ah, 0AAh
		db 0, 0Ah, 0, 0Ah, 0AAh, 80h, 0A0h, 0A8h, 80h, 15h, 4 dup(55h)
		db 54h,	3 dup(11h), 3 dup(44h),	0Fh, 3 dup(0FFh), 0F1h
		db 10h,	0Fh, 0FFh, 0FDh, 55h, 51h, 10h,	3, 0FDh, 2 dup(55h)
		db 44h,	40h, 0,	0F5h, 2	dup(55h), 51h, 2 dup(0), 0C1h
		db 2 dup(14h), 41h, 0, 0Fh, 4 dup(0FFh), 0F0h, 7 dup(0)
		db 60h,	28h, 18h, 0Ah, 2 dup(0), 5Ah, 0A8h, 16h, 0AAh
		db 2 dup(0), 6,	80h, 1,	0A0h, 0

loc_A8AF:			
		db 6, 0Eh, 7 dup(0), 8Ah
		db 0AAh, 0, 0Ah, 0, 0Ah, 0AAh, 80h, 0A0h, 0A8h,	80h, 15h
		db 4 dup(55h), 54h, 3 dup(11h),	3 dup(44h), 0Fh, 3 dup(0FFh)
		db 0F1h, 10h, 0Fh, 0FFh, 0FDh, 55h, 51h, 10h, 3, 0FDh
		db 2 dup(55h), 44h, 40h, 0, 0F5h, 2 dup(55h), 51h, 2 dup(0)
		db 0C1h, 2 dup(14h), 41h, 0, 0Fh, 4 dup(0FFh), 0F0h, 0
		db 0A0h, 24h, 28h, 9, 2	dup(0),	0AAh, 94h, 2Ah,	0A5h, 2	dup(0)
		db 0Ah,	40h, 2,	90h, 0
		
loc_A905:
		db	6, 0Eh,	3, 0F0h, 0Fh, 0C0h, 0
		db 30h,	0Fh, 3Fh, 0FCh,	0F0h, 3Fh, 0, 0Ch, 2 dup(0CCh)
		db 0F0h, 0FFh, 0C0h, 0Fh, 3Fh, 33h, 3Fh, 0FFh, 0C0h, 3
		db 0CCh, 0CFh, 0CCh, 0CFh, 0C0h, 0, 3Fh, 2 dup(33h), 3Fh
		db 0, 2	dup(0Ch), 2 dup(0CCh), 0FCh, 2 dup(0), 33h, 2 dup(0F3h)
		db 3Ch,	2 dup(0), 3 dup(0CCh), 0FCh, 0,	3, 2 dup(3Fh)
		db 33h,	0F0h, 0, 3, 2 dup(0CCh), 0CFh, 0F0h, 2 dup(0)
		db 0F3h, 33h, 0FFh, 0C3h, 0F0h,	3Ch, 3Fh, 0CCh,	3Fh, 0Ch
		db 0FCh, 2 dup(0), 0F0h, 0, 3, 0F0h
		
loc_A95B:		
		db 6,	0Eh, 0Fh, 0, 0Fh
		db 0C0h, 0, 30h, 33h, 0C0h, 3Fh, 2 dup(0F0h), 0FCh, 2 dup(0Fh)
		db 0CCh, 0FFh, 0FCh, 30h, 0, 3Fh, 33h, 3Fh, 0FFh, 0, 3
		db 3 dup(0CCh),	0FFh, 0, 0Fh, 33h, 3Fh,	33h, 3Fh, 0, 3Ch
		db 2 dup(0CCh),	2 dup(0FCh), 0,	0Fh, 3Fh, 2 dup(33h), 3Ch
		db 0, 3, 2 dup(0CFh), 0CCh, 0FCh, 0, 0Fh, 3 dup(33h), 0F0h
		db 0, 3Ch, 0CFh, 0FCh, 0CFh, 0F3h, 0F0h, 33h, 3Ch, 3Fh
		db 0FFh, 0CFh, 0FCh, 0Ch, 0CCh,	3, 0FCh, 0Ch, 0FCh, 3
		db 0F0h, 0C0h, 0, 3, 0F0h
		
loc_A9B1:		
		db 6, 0Eh, 0Ch,	0, 0FFh, 2 dup(0)
		db 0F0h, 3Fh, 3, 33h, 0C0h, 3, 3Ch, 0Ch, 3Ch, 0CFh, 0C0h
		db 2 dup(0F0h),	3, 2 dup(0F3h),	2 dup(0FFh), 0,	0Ch, 2 dup(0CCh)
		db 0CFh, 0FFh, 0C0h, 0Fh, 3 dup(33h), 3Fh, 0C0h, 3Ch, 0FCh
		db 0CFh, 0CCh, 0FFh, 30h, 3 dup(33h), 3Fh, 2 dup(0FCh)
		db 3Ch,	0CFh, 0CCh, 0CFh, 0, 30h, 2 dup(33h), 3Fh, 3Ch
		db 3Fh,	0C0h, 0Fh, 2 dup(0CCh),	0FCh, 0CFh, 0F0h, 0, 0FFh
		db 0F3h, 0F0h, 0CCh, 0F0h, 0Ch,	3, 0FFh, 0F0h, 33h, 0F0h
		db 0Ch,	0, 3Fh,	0, 0Fh,	0C0h
		
loc_AA07:		
		db 6, 0Eh, 4	dup(0),	2Ah, 5 dup(0)
		db 2 dup(0A0h),	4 dup(0), 0B0h,	28h, 4 dup(0), 0Ch, 28h
		db 5 dup(0), 28h, 0Ah, 4 dup(0), 0A0h, 2Ah, 0A0h, 2 dup(0)
		db 2, 0A0h, 4 dup(0), 2Ah, 80h,	0, 0AAh, 0A0h, 2, 0AAh
		db 0
		db 2, 0Ah, 88h,	8Ah, 0A8h, 2 dup(0), 0AAh, 0A2h, 2Ah, 80h
		db 3 dup(0), 0AAh, 0A8h, 2 dup(0), 2Ah,	0AAh, 22h, 8Ah
		db 2 dup(0), 0Ah, 0A0h,	2 dup(20h), 80h, 0
		
loc_AA5D:		
		db 6, 0Eh, 3 dup(0)
		db 0Ah,	80h, 4 dup(0), 2 dup(0A8h), 3 dup(0), 2, 80h, 0Ah
		db 3 dup(0), 2,	0C0h, 2, 80h, 2Ah, 2 dup(0), 30h, 2, 80h
		db 0Ah,	80h, 2 dup(0), 2, 80h, 2Ah, 0A0h, 2 dup(0), 2
		db 80h,	4 dup(0), 0Ah, 2 dup(0), 0AAh, 0A0h, 0,	0AAh, 0
		db 2, 0Ah, 88h,	8Ah, 0A8h, 2 dup(0), 0AAh, 0A2h, 2Ah, 80h
		db 0, 28h, 0, 0AAh, 0A8h, 2 dup(0), 2, 0AAh, 22h, 20h
		db 2 dup(0), 2Ah, 0A0h,	88h, 20h, 2 dup(0)
		
loc_AAB3:			
		db 6, 7, 0, 1
		db 55h,	54h, 2 dup(0), 5, 55h, 66h, 55h, 50h, 0, 50h, 55h
		db 0A5h, 55h, 95h, 0, 3	dup(55h), 0A5h,	55h, 50h, 5, 56h
		db 15h,	64h, 50h, 14h, 20h, 5, 40h, 15h, 0, 4, 0, 1, 40h
		db 5, 0, 1
		
loc_AADF:					
		db 6, 7, 0, 1,	55h, 54h, 0, 2 dup(5), 55h, 66h
		db 55h,	3 dup(50h), 55h, 0A5h, 55h, 95h, 40h, 3	dup(55h)
		db 0A5h, 55h, 0, 5, 52h, 55h, 45h, 50h,	2 dup(0), 5, 40h
		db 15h,	3 dup(0), 15h, 0, 54h, 2 dup(0)
		
loc_AB0B:		
		db 4, 0Eh, 2 dup(0)
		db 0Fh,	0F0h, 2	dup(0),	0FFh, 0F4h, 0, 3, 0Fh, 0C4h, 0
		db 0Fh,	0F3h, 0C4h, 0, 3Fh, 0FFh, 14h, 0, 0C3h,	0FFh, 10h
		db 0, 2	dup(0FCh), 50h,	3, 0FFh, 0F1h, 40h, 0Ch, 3Fh, 0C5h
		db 0, 0Fh, 0CFh, 14h, 0, 3Fh, 0FFh, 14h, 0, 3Fh, 0FCh
		db 50h,	0, 3Fh,	0F1h, 40h, 0, 0Fh, 15h,	2 dup(0)
		
loc_AB45:		
		db 4, 0Dh
		db 0, 3Fh, 0FCh, 0, 3, 0FCh, 0FFh, 0C0h, 0Fh, 3Fh, 0FCh
		db 0F0h, 3Fh, 2	dup(0FFh), 0CCh, 33h, 0FFh, 0F3h, 0FCh
		db 3Fh,	0FCh, 0FFh, 0FCh, 2 dup(3Fh), 0FFh, 0CCh, 0Fh
		db 0FFh, 0CFh, 0F0h, 3Ah, 66h, 0A6h, 0ECh, 3Eh,	99h, 9Ah
		db 0BCh, 0Fh, 0E5h, 6Fh, 0F0h, 0, 0D5h,	3Fh, 2 dup(0)
		db 15h,	2 dup(0)
		
loc_AB7B:		
		db 4, 10h, 3 dup(0), 70h, 2 dup(0), 5, 5Fh
		db 3Fh,	0Fh, 0F0h, 50h,	2 dup(0F0h), 0,	0A0h, 0F0h, 2 dup(0)
		db 0A0h, 0F0h, 0, 2, 0A8h, 0F0h, 0, 0Ah, 0A2h, 3Fh, 0C0h
		db 0AAh, 0A8h, 2, 0FAh,	8Ah, 0A2h, 0Ah,	0F2h, 2Ah, 0A8h
		db 22h,	3Ch, 0AAh, 0A2h, 28h, 8Ah, 0AAh, 8Ah, 22h, 2Ah
		db 0A2h, 2 dup(28h), 0AAh, 88h,	0A0h, 0Ah, 0AAh, 0A2h
		db 80h,	0, 0AAh, 0A8h, 0
		
loc_ABBD:
		db 4, 0Eh, 0, 0Fh, 0F0h,	2 dup(0)
		db 2 dup(3Ch), 2 dup(0), 0F0h, 0Fh, 0, 0F0h, 0F3h, 0FFh
		db 0, 3Ch, 2 dup(0FFh),	0Fh, 3Fh, 33h, 2 dup(0FFh), 0Fh
		db 0CFh, 0FFh, 30h, 0Fh, 2 dup(0FFh), 30h, 0Fh,	2 dup(0FFh)
		db 30h,	3, 0FFh, 0FCh, 0C0h, 0,	2 dup(0FFh), 2 dup(0)
		db 0Fh,	0F0h, 2	dup(0),	2 dup(0FFh), 0,	0Fh, 2 dup(0FFh)
		db 0F0h

loc_ABF7:		
		db 4, 7, 1, 2 dup(55h), 40h, 5, 57h, 0FFh, 30h, 15h
		db 7Fh,	0FFh, 0CCh, 15h, 2 dup(0FFh), 30h, 15h,	2 dup(0FFh)
		db 0CCh, 5, 2 dup(0FFh), 30h, 1, 0FFh, 0FCh, 0C0h
		
loc_AC15:		
		db 4, 7
		db 1, 2	dup(55h), 40h, 5, 53h, 0FFh, 30h, 15h, 73h, 0FFh
		db 0CCh, 14h, 3Fh, 0Fh,	30h, 15h, 0F3h,	0FFh, 0CCh, 5
		db 0F3h, 0FFh, 30h, 1, 0FFh, 0FCh, 0C0h
		
loc_AC33:			
		db 6, 0Eh, 6 dup(0)
		db 28h,	4 dup(0), 28h, 2Ah, 80h, 2 dup(0), 2, 0A8h, 2Ah
		db 80h,	2 dup(0), 2, 0A8h, 28h,	80h, 8,	20h, 2,	28h, 2
		db 4 dup(28h), 80h, 2, 88h, 2 dup(28h),	22h, 80h, 0, 2Ah
		db 0A2h, 8Ah, 0A8h, 2 dup(0), 2, 2 dup(0AAh), 4	dup(0)
		db 0Eh,	0B0h, 4	dup(0),	0Ch, 30h, 14h dup(0)
		
loc_AC89:		
		db 6, 0Eh, 0Dh dup(0)
		db 8, 2	dup(0),	20h, 2 dup(0), 28h, 8, 20h, 28h, 0, 2
		db 0AAh, 2 dup(28h), 2Ah, 80h, 2, 0AAh,	28h, 2 dup(2Ah)
		db 80h,	2Ah, 82h, 0A2h,	8Ah, 82h, 0A8h,	2Ah, 28h, 2 dup(0AAh)
		db 28h,	0A8h, 22h, 80h,	0Eh, 0B0h
		db 2, 88h, 28h,	0, 0Ch,	30h, 0,	28h, 8,	4 dup(0), 20h
		db 12h dup(0)
		
loc_ACDF:			
		db 6, 0Eh, 0Eh dup(0), 8, 20h, 3 dup(0), 20h
		db 2 dup(28h), 8, 2 dup(0), 28h, 2Ah, 0A8h, 28h, 0, 2
		db 0AAh, 0A2h, 8Ah, 0AAh, 80h, 2, 4 dup(0AAh), 80h, 2Ah
		db 88h,	0Eh, 0B0h, 22h,	0A8h, 2Ah, 28h,	0Ch, 30h, 28h
		db 0A8h, 28h, 80h, 2 dup(0), 2,	28h, 2Ah, 80h, 2 dup(0)
		db 2, 0A8h, 2Ah, 4 dup(0), 0A8h, 0Ah, 4	dup(0),	0A0h, 2
		db 80h,	2 dup(0), 2, 80h
		
loc_AD35:		
		db 6, 10h, 2 dup(0), 0Ch, 0Fh, 3	dup(0)
		db 3Fh,	2 dup(0F0h), 2 dup(0), 3, 0EBh,	0FFh, 2	dup(0)
		db 3Ch,	3Fh, 0BEh, 0FFh, 0CFh, 0, 0F0h,	0FFh, 0EBh, 0FFh
		db 3 dup(0F0h),	4 dup(0FFh), 0Fh, 0C0h,	2 dup(5), 0Fh
		db 0CFh, 0FCh, 0C0h, 2 dup(1), 0, 0F3h,	0FFh, 4	dup(0)
		db 0F3h, 0FFh, 0F0h, 2 dup(0), 0Fh, 0CFh, 0, 3Fh, 3Ch
		db 0Fh,	0FFh, 0F0h, 2 dup(0), 3Fh, 2 dup(0FFh),	0Fh, 0C0h
		db 0, 0Fh, 2 dup(0FCh),	4 dup(0), 0FCh,	0F0h, 3	dup(0)
		db 0Fh,	3, 0C0h, 4 dup(0), 0Ch,	4 dup(0)
		
loc_AD97:		
		db 6, 10h, 2 dup(0)
		db 0Ch,	4 dup(0), 0Fh, 0F0h, 0FCh, 3 dup(0), 2 dup(0FFh)
		db 3 dup(0), 3,	2 dup(0FFh), 0CFh, 2 dup(0), 3Fh, 0BEh
		db 0FFh, 2 dup(0F0h), 0, 0FFh, 0EBh, 2 dup(0FFh), 0, 3Fh
		db 3 dup(0FFh),	0CFh, 0FFh, 0F0h, 3Ah, 0AFh, 0FFh, 0F3h
		db 0FCh, 0, 3Fh, 0FAh, 0AFh, 0F3h, 0FFh, 0C0h, 3Ch, 0FFh
		db 0FBh, 0CFh, 0Fh, 0C0h, 2 dup(0Fh), 0FFh, 0F0h, 0, 0F0h
		db 3, 2	dup(0FFh), 0Fh,	0, 3Ch,	0, 0FFh, 3Fh, 2	dup(0)
		db 0Ch,	0, 3Fh,	0CFh, 4	dup(0),	30h, 3,	0C0h, 3	dup(0)
		db 0Ch,	0, 3Ch,	2 dup(0)
		
loc_ADF9:
		db 6, 0Ch, 0, 3,	33h, 0Ch, 3 dup(0)
		db 2 dup(33h), 30h, 0C0h, 2 dup(0), 2 dup(0FFh), 0C3h
		db 2 dup(0), 0Fh, 0FFh,	0C0h, 0FCh, 30h, 2 dup(3Ch), 0Fh
		db 0Ch,	3Fh, 2 dup(0C0h), 0, 3,	0C0h, 0F3h, 0FFh, 30h
		db 2 dup(0), 0FFh, 0F0h, 0FFh, 0C0h, 2 dup(0), 0FFh, 0C3h
		db 0C0h, 0F0h, 0Fh, 0C3h, 0F3h,	0FCh, 0, 3Ch, 0, 0FFh
		db 0FCh, 0C0h, 3 dup(0), 3, 0C0h, 0F0h,	4 dup(0), 0F0h
		db 3Ch,	2 dup(0)
		
loc_AE43:
		db 6, 0Ch, 0, 3,	33h, 0Ch, 3 dup(0), 2 dup(33h)
		db 30h,	0C0h, 2	dup(0),	2 dup(0FFh), 0C3h, 0, 30h, 0Fh
		db 2 dup(0FFh),	0FCh, 30h, 0C0h, 3Fh, 0FFh, 2 dup(3Fh)
		db 0C3h, 2 dup(0), 3Fh,	0C0h, 0F3h, 0FCh, 0C0h,	3Fh, 0C3h
		db 0FFh, 0F0h, 0FFh, 0,	33h, 2 dup(0FFh), 2 dup(0C3h)
		db 0C0h, 0Fh, 0FFh, 0F3h, 0FCh,	0, 0C0h, 0, 0FFh, 0F3h
		db 0C0h, 0, 30h, 0, 3Ch, 0Fh, 4	dup(0),	0F0h, 3Ch, 3 dup(0)
		
loc_AE8D:
		db 6, 16h, 2 dup(0), 0AAh, 4 dup(0), 0Ah, 0AAh,	0A0h, 3	dup(0)
		db 2Bh,	0EBh, 0E8h, 0, 80h, 0, 2Fh, 0AAh, 0F8h,	8, 82h
		db 0, 0Ah, 0FFh, 0A0h, 2, 0A8h,	0, 0Bh,	0, 0E0h, 0Ah, 0A0h
		db 2 dup(0), 0FFh, 0Ah,	0, 0A0h, 0, 2Ah, 0, 0AAh, 2 dup(0A0h)
		db 2, 4	dup(0AAh), 0A0h, 0Ah, 0A8h, 2, 0AAh, 2Ah, 80h
		db 2, 0AAh, 0A8h, 0AAh,	80h, 2 dup(0), 0Ah, 8Ah, 2Ah, 80h
		db 2 dup(0), 5,	2 dup(55h), 50h, 2 dup(0), 20h,	2 dup(0)
		db 8, 2	dup(0),	0ABh, 3Fh, 0FDh, 6Ah, 0, 2, 0A0h, 0CFh
		db 0FDh, 4Ah, 80h, 0Ah,	83h, 33h, 0F5h,	42h, 0A0h, 2, 0A0h
		db 0CFh, 0F5h, 0Ah, 80h, 0, 0A0h, 33h, 0F5h, 0Ah, 2 dup(0)
		db 0A0h, 0CFh, 0F5h, 0Ah, 0, 2Ah, 0A0h,	11h, 54h, 0Ah
		db 0A8h, 0AAh, 0A0h, 3Fh, 0FCh,	0Ah, 0AAh
		
loc_AF13:		
		db 6, 16h, 3 dup(0)
		db 0AAh, 4 dup(0), 0Ah,	0AAh, 0A0h, 0, 2, 0, 2Bh, 0EBh
		db 0E8h, 0, 82h, 20h, 2Fh, 0AAh, 0F8h, 0, 2Ah, 80h, 0Ah
		db 0FFh, 0A0h, 0, 0Ah, 0A0h, 0Bh, 0, 0E0h, 0, 0Ah, 0, 0A0h
		db 0FFh, 2 dup(0), 2 dup(0Ah), 0AAh, 0,	0A8h, 0, 0Ah, 4	dup(0AAh)
		db 80h,	2, 0A8h, 0AAh, 80h, 2Ah, 0A0h, 0, 2, 0AAh, 2Ah
		db 0AAh, 80h, 0, 2, 0A8h, 0A2h,	0A0h, 2	dup(0),	5, 2 dup(55h)
		db 50h,	2 dup(0), 20h
		db 2 dup(0), 8,	2 dup(0), 0ABh,	3Fh, 0FDh, 6Ah,	0, 2, 0A0h
		db 0CFh, 0FDh, 4Ah, 80h, 0Ah, 83h, 33h,	0F5h, 42h, 0A0h
		db 2, 0A0h, 0CFh, 0F5h,	0Ah, 80h, 0, 0A0h, 33h,	0F5h, 0Ah
		db 2 dup(0), 0A0h, 0CFh, 0F5h, 0Ah, 0, 2Ah, 0A0h, 11h
		db 54h,	0Ah, 0A8h, 0AAh, 0A0h, 3Fh, 0FCh, 0Ah, 0AAh
		
loc_AF99:		
		db 6
		db 15h,	0, 3 dup(0FFh),	2 dup(0), 0Fh, 3 dup(88h), 0F0h
		db 0, 3Eh, 22h,	2Ah, 0AAh, 0BCh, 0, 38h, 88h, 2	dup(0AAh)
		db 0ACh, 0, 3Eh, 22h, 2Ah, 0AAh, 0BCh, 0, 0Fh, 3 dup(0FFh)
		db 0F0h, 0, 5, 5Fh, 2 dup(0FFh), 0F0h, 0, 5, 55h, 7Fh
		db 0FFh, 0C0h, 0, 1, 5Fh, 2 dup(0FFh), 2 dup(0), 1, 55h
		db 5Fh,	0FFh, 3	dup(0),	57h, 0FFh, 0FCh, 3 dup(0), 15h
		db 5Fh,	0F0h, 3	dup(0),	5, 0FFh, 0F0h, 3 dup(0), 1, 57h
		db 0F0h, 4 dup(0), 5Fh,	0FCh, 4	dup(0),	5, 5Fh,	5 dup(0)
		db 7Fh,	5 dup(0), 17h, 5 dup(0), 1Ch, 5	dup(0),	10h, 5 dup(0)
		db 40h,	2 dup(0)
		
loc_B019:		
		db 6, 15h, 2 dup(0), 3 dup(0FFh), 2 dup(0)
		db 0Fh,	3 dup(22h), 0F0h, 0, 3Eh, 0AAh,	0A8h, 88h, 0BCh
		db 0, 3Ah, 2 dup(0AAh),	22h, 2Ch, 0, 3Eh, 0AAh,	0A8h, 88h
		db 0BCh, 0, 0Fh, 3 dup(0FFh), 0F0h, 0, 0Fh, 2 dup(0FFh)
		db 0F5h, 50h, 0, 3, 0FFh, 0FDh,	55h, 50h, 2 dup(0), 2 dup(0FFh)
		db 0F5h, 40h, 2	dup(0),	0FFh, 0F5h, 55h, 40h, 2	dup(0)
		db 3Fh,	0FFh, 0D5h, 3 dup(0), 0Fh, 0F5h, 54h, 3	dup(0)
		db 0Fh,	0FFh, 50h, 3 dup(0), 0Fh, 0D5h,	40h, 3 dup(0)
		db 3Fh,	0F5h, 4	dup(0),	0F5h, 50h, 4 dup(0), 0FDh, 5 dup(0)
		db 0D4h, 5 dup(0), 34h,	5 dup(0), 4, 5 dup(0), 1, 3 dup(0)
		
loc_B099:
		db 4, 16h, 0, 0Ah, 3 dup(0), 0AAh, 0A0h, 0, 2, 0BFh, 0E8h
		db 0, 0Ah, 0FBh, 0BAh, 0, 0Ah, 0FFh, 0FAh, 0, 2Ah, 0BEh
		db 0E8h, 0, 28h, 2Fh, 80h, 0, 23h, 0C0h, 0Ch, 0, 0Fh, 3Ch
		db 0F3h, 0, 3Ch, 0F3h, 0FCh, 0C0h, 0F0h, 0F3h, 0FCh, 0F0h
		db 0FCh, 3Ch, 0F3h, 0F0h, 3Fh, 5, 0Fh, 0C0h, 0Ch, 55h
		db 53h,	0, 1, 55h, 54h,	0, 5, 55h, 14h,	0, 5, 54h, 50h
		db 0, 5, 55h, 0, 54h, 5, 54h, 1, 40h, 1, 50h, 15h, 54h
		db 1, 55h, 50h,	2 dup(0), 55h, 40h, 0
		
loc_B0F3:
		db 4, 16h, 0, 0Ah
		db 3 dup(0), 0AAh, 0A0h, 0, 2, 0BFh, 0E8h, 0, 0Ah, 0EEh
		db 0FAh, 0, 0Ah, 0FFh, 0FAh, 0,	2, 0BBh, 0EAh, 80h, 0
		db 2Fh,	82h, 80h, 3, 0,	3Ch, 80h, 0Ch, 0F3h, 0CFh, 0, 33h
		db 0CFh, 0F3h, 0C0h, 0F3h, 0CFh, 2 dup(0F0h), 0FCh, 0F3h
		db 0C3h, 0F0h, 3Fh, 5, 0Fh, 0C0h, 0Ch, 55h, 53h, 0, 1
		db 55h,	54h, 0,	5, 55h,	14h, 0,	5, 54h,	50h, 54h, 5, 55h
		db 1, 40h, 5, 54h, 5, 54h, 1, 55h, 54h,	2 dup(0), 55h
		db 40h,	5 dup(0)
		
loc_B14D:		
		db 6, 16h, 2 dup(0), 3Ch, 0F0h, 0, 50h
		db 0, 3, 2 dup(0FFh), 31h, 64h,	2 dup(0), 2 dup(0FFh)
		db 0C1h, 54h, 0, 0AAh, 8Bh, 0FFh, 0C1h,	54h, 2,	2 dup(82h)
		db 0FFh, 0, 50h, 2, 0ABh, 0EBh,	0FCh, 0C2h, 0A0h, 0, 0Fh
		db 0FFh, 80h, 2, 0A0h, 0, 0Fh, 0FAh, 68h, 0Ah, 50h, 0
		db 3Ch,	29h, 0AAh, 8Ah,	2 dup(0), 0C0h,	0A9h, 2	dup(0AAh)
		db 3 dup(0), 0A5h, 0A0h, 0A8h, 3 dup(0), 25h, 0AAh, 4 dup(0)
		db 5, 69h, 40h,	3 dup(0), 5, 55h, 40h, 3 dup(0), 5, 55h
		db 40h,	3 dup(0), 2Ah, 56h, 90h, 3 dup(0), 0AAh, 1Ah, 0A0h
		db 0, 2	dup(2),	0A0h, 12h, 0A8h, 0, 0Ah, 82h, 80h, 0, 2Ah
		db 0, 0Ah, 0AAh, 80h, 8, 0Ah, 80h, 0, 0AAh, 0, 2, 0AAh
		db 0A0h, 0, 0Ah, 0, 0Ah, 0AAh, 0A0h
		
loc_B1D3:		
		db 6, 16h, 2 dup(0)
		db 0F3h, 0C0h, 3 dup(0), 0Fh, 0FFh, 0FCh, 0C0h,	2 dup(0)
		db 3, 2	dup(0FFh), 2 dup(0), 2,	0AAh, 2Fh, 0FFh, 0
		db 0, 2	dup(0Ah), 0Bh, 0FCh, 2 dup(0), 0Ah, 2 dup(0AFh)
		db 0F3h, 3 dup(0), 3Fh,	0FFh, 80h, 3 dup(0), 3Fh, 0C0h
		db 68h,	3 dup(0), 0F0h,	0Ah, 0AAh, 2 dup(0), 3,	0, 2 dup(0AAh)
		db 3 dup(0), 2 dup(0AAh), 0Ah, 28h, 0, 0Ah, 0AAh, 0A0h
		db 0AAh, 2Ah, 80h, 2Ah,	0, 5, 69h, 4Ah,	0, 82h,	0, 5, 55h
		db 48h,	80h, 2 dup(0), 5, 55h, 40h, 3 dup(0), 2Ah, 56h
		db 90h,	3 dup(0), 0A8h,	1Ah, 0A0h, 2 dup(0), 2,	0A0h, 12h
		db 0A8h, 2 dup(0), 2, 80h, 0, 2Ah, 0, 8, 2, 80h, 8, 0Ah
		db 80h,	2, 0AAh, 0A0h, 2, 0AAh,	0A0h, 0Ah, 0AAh, 0A0h
		db 0Ah,	0AAh, 0A0h
		
loc_B259:
		db 3, 6, 0Ah, 82h, 0A0h, 20h, 0AAh, 0A8h
		db 22h,	0AAh, 0A8h, 0Ah, 0AAh, 0A0h, 0,	0AAh, 2	dup(0)
		db 28h,	0
		
loc_B26D:		
		db 2, 8, 5 dup(0), 54h,	4 dup(55h), 0, 54h, 4 dup(0)
		
loc_B27F:
		db 2, 8, 1, 40h, 1, 40h, 1, 40h, 1, 40h, 5, 50h, 5, 50h
		db 5, 50h, 1, 40h
		
loc_B291:		
		db 2, 8, 4 dup(0), 15h,	0, 4 dup(55h)
		db 15h,	5 dup(0)
		
loc_B2A3:		
		db 2, 8,	1, 40h,	5, 50h,	5, 50h,	5, 50h
		db 1, 40h, 1, 40h, 1, 40h, 1, 40h

loc_B2B5:		
		db 2, 10h, 4, 0C8h, 1
		db 0D0h, 4, 0C8h, 1, 0D0h, 0, 0C0h, 0, 0C0h, 0,	0C0h, 0
		db 0C0h, 0, 0C0h, 0, 0C0h, 0, 0C0h, 0, 0C0h, 0,	0C0h, 1
		db 20h,	1, 60h,	0, 80h
		
loc_B2D7:		
		db	6, 13h,	3 dup(0), 14h, 40h, 2 dup(0)
		db 30h,	0, 55h,	10h, 2 dup(0), 0C0h, 0,	88h, 80h, 2 dup(0)
		db 0C0h, 5, 55h, 51h, 2	dup(0),	30h, 0,	0AFh, 0F0h, 3 dup(0)
		db 0Ah,	4Bh, 0F0h, 2 dup(0), 0C0h, 2Ah,	0AFh, 0C4h, 2 dup(0)
		db 30h,	0, 0FFh, 15h, 40h, 2 dup(0), 57h, 0F0h,	69h, 50h
		db 0, 1, 43h, 0C5h, 5Ah, 50h, 1, 55h, 0Ch, 5, 56h, 94h
		db 1, 55h, 0, 1, 56h, 80h, 0, 54h, 2 dup(0), 2,	94h, 3 dup(0)
		db 55h,	5Ah, 90h, 2 dup(0), 1, 55h, 0AAh, 0A0h,	2 dup(0)
		db 1, 40h, 4 dup(0), 0Ah, 4 dup(0), 0Ah, 0AAh, 4 dup(0)
		db 0Ah,	0AAh, 3	dup(0)
		
loc_B34B:
		db	6, 13h,	3 dup(0), 14h, 40h, 2 dup(0)
		db 30h,	0, 55h,	10h, 2 dup(0), 30h, 0, 88h, 80h, 2 dup(0)
		db 0Ch,	5, 55h,	51h, 2 dup(0), 30h, 0, 0AFh, 0F0h, 2 dup(0)
		db 0C0h, 0Ah, 4Bh, 0F0h, 3 dup(0), 2Ah,	0AFh, 0C4h, 2 dup(0)
		db 30h,	0, 0FFh, 15h, 40h, 0, 30h, 57h,	0F0h, 69h, 50h
		db 0, 1, 43h, 0C5h, 5Ah, 50h, 1, 55h, 0Ch, 5, 56h, 94h
		db 1, 55h, 0, 1, 56h, 80h, 0, 54h, 2 dup(0), 2,	94h, 3 dup(0)
		db 55h,	5Ah, 90h, 0, 0A0h, 0Ah,	55h, 0AAh, 0A0h, 0, 2 dup(0AAh)
		db 4 dup(0), 0Ah, 0A0h,	5 dup(0), 0A0h,	9 dup(0)

loc_B3BF:		
		db 6, 0Bh
		db 0, 0A0h, 4 dup(0), 2, 0A8h, 4 dup(0), 0Ah, 5Ah, 5 dup(0)
		db 0AAh, 4 dup(0), 2, 0A8h, 5 dup(0), 0A0h, 3 dup(0), 8
		db 0, 0A0h, 0, 2Ah, 0, 8, 0, 0A8h, 0, 0AAh, 80h, 2, 0
		db 2Ah,	2, 2 dup(0A0h),	2, 0, 0Ah, 0AAh, 80h, 0Ah, 8, 0
		db 2, 0AAh, 2 dup(0), 0A0h
		
loc_B403:		
		db 6, 0Bh, 0, 0Ah, 5 dup(0), 2Ah
		db 80h,	4 dup(0), 0A5h,	0A0h, 4	dup(0),	0Ah, 0A0h, 4 dup(0)
		db 2Ah,	80h, 0A0h, 3 dup(0), 28h, 2, 0A8h, 0, 0A0h, 0
		db 0A0h, 2 dup(0Ah), 2,	2 dup(0), 0A0h,	2 dup(0Ah), 8
		db 2 dup(0), 0A8h, 2 dup(0Ah), 8, 2 dup(0), 2Ah, 0A8h
		db 0Ah,	8, 2 dup(0), 2,	0A0h, 2, 0A0h, 0
		
loc_B447:		
		db 6, 15h, 0, 30h
		db 0, 2	dup(0Ch), 0C0h,	0, 0FCh, 0FFh, 2 dup(3Fh), 30h
		db 0, 0Fh, 0FFh, 0F0h, 3Fh, 30h, 0, 0F0h, 3Ch, 2 dup(0Fh)
		db 0C0h, 0, 0FCh, 0FFh,	3Fh, 3,	2 dup(0), 0Fh, 0FFh, 0F0h
		db 0Ah,	80h, 0,	0Fh, 0,	0F0h, 2Ah, 80h,	2 dup(0), 0FFh
		db 0, 0ABh, 4 dup(0), 0Ah, 0A3h, 3 dup(0), 2 dup(0AAh)
		db 3
		db 2 dup(0), 2,	0AAh, 0A0h, 82h, 80h, 0, 2, 0A0h, 0Ah
		db 8Ah,	80h, 2 dup(0), 2 dup(0AAh), 3, 3 dup(0), 2Ah, 28h
		db 3, 2	dup(0),	2Ah, 5Ah, 0A5h,	0ABh, 0, 2, 0AAh, 0B5h
		db 5Eh,	0ABh, 80h, 0Ah,	80h, 39h, 6Ch, 3, 0A0h,	2, 0A0h
		db 36h,	9Ch, 3,	80h, 20h, 0A0h,	0Dh, 70h, 0Bh, 8, 0Ah
		db 28h,	3, 0C0h, 2Bh, 0A0h, 2Ah, 0AAh, 2 dup(0), 0AAh
		db 0A8h
		
loc_B4C7:			
		db 6, 15h, 3, 2 dup(30h),	0, 0Ch,	0, 0Ch,	2 dup(0FCh)
		db 0FFh, 3Fh, 0, 0Ch, 0FCh, 0Fh, 0FFh, 0F0h, 0,	3, 2 dup(0F0h)
		db 3Ch,	0Fh, 2 dup(0), 0C0h, 0FCh, 0FFh, 3Fh, 0, 2, 0A0h
		db 0Fh,	0FFh, 0F0h, 0, 2, 0A8h,	0Fh, 0,	0F0h, 2	dup(0)
		db 0EAh, 0, 0FFh, 3 dup(0), 0CAh, 0A0h,	4 dup(0), 0C0h
		db 2 dup(0AAh),	2 dup(0), 2, 82h, 0Ah, 0AAh, 80h, 0, 2
		db 0A2h, 0A0h, 0Ah, 80h, 2 dup(0), 0C0h, 2 dup(0AAh), 3	dup(0)
		db 0C0h, 28h, 0A8h, 3 dup(0), 0EAh, 5Ah, 0A5h, 0A8h, 0
		db 2, 0EAh, 0B5h, 5Eh, 0AAh, 80h, 0Ah, 0C0h, 39h, 6Ch
		db 2, 0A0h, 2, 0C0h, 36h, 9Ch, 0Ah, 80h, 20h, 0E0h, 0Dh
		db 70h,	0Ah, 8,	0Ah, 0E8h, 3, 0C0h, 28h, 0A0h, 2Ah, 0AAh
		db 2 dup(0), 0AAh, 0A8h
		
loc_B547:		
		db 4, 9, 8, 2 dup(2), 80h, 2, 8Ah
		db 0AAh, 0, 2, 0A5h, 68h, 0, 0Ah, 5Fh, 0DAh, 80h, 2Ah
		db 7Fh,	0F6h, 0A0h, 2, 9Fh, 0DAh, 0, 0Ah, 0A9h,	68h, 0
		db 2, 0Ah, 8Ah,	0, 8, 2	dup(2),	80h
		
loc_B56D:		
		db 4,	9, 5 dup(0), 82h
		db 0Ah,	2 dup(0), 22h, 0A0h, 2 dup(0), 29h, 60h, 0, 2
		db 9Fh,	0DAh, 2	dup(0),	27h, 68h, 2 dup(0), 0A9h, 0A0h
		db 0, 2	dup(2),	8, 5 dup(0)
		
loc_B593:		
		db 4,	10h, 4 dup(0), 2, 80h
		db 2, 80h, 8, 2	dup(0),	20h, 8,	2, 80h,	20h, 8,	0Ah, 0A0h
		db 20h,	2, 2 dup(82h), 80h, 0, 3Fh, 0FCh, 2 dup(0), 0FBh
		db 0EFh, 0, 0Ah, 2 dup(0FFh), 0A0h, 20h, 0FEh, 0BFh, 8
		db 2, 3Fh, 0FCh, 80h, 8, 3, 0C0h, 2 dup(20h), 2	dup(0)
		db 8, 20h, 2 dup(0), 2 dup(8), 2 dup(0), 20h, 4	dup(0)
		
loc_B5D5:		
		db 4, 10h, 4 dup(0), 8,	2 dup(0), 2 dup(20h), 2	dup(0)
		db 8, 20h, 2, 80h, 2 dup(8), 0Ah, 0A0h,	20h, 2,	2 dup(82h)
		db 80h,	0, 3Fh,	0FCh, 0, 20h, 0FBh, 0EFh, 8, 0Ah, 2 dup(0FFh)
		db 0A0h, 0, 0FEh, 0BFh,	0, 2, 3Fh, 0FCh, 80h, 8, 3, 0C0h
		db 2 dup(20h), 2 dup(0), 8, 20h, 2 dup(0), 8, 20h, 2 dup(0)
		db 8, 4	dup(0)
		
loc_B617:
		db 6, 17h,	8 dup(0), 55h, 5 dup(0), 54h, 50h
		db 4 dup(0), 0A5h, 50h,	3 dup(0), 15h, 55h, 53h, 4 dup(0)
		db 0AFh, 0FCh, 3 dup(0), 2Ah, 0CBh, 0FFh, 3 dup(0), 2 dup(0AAh)
		db 0BFh, 3 dup(0), 3, 0FAh, 0A4h, 4 dup(0), 0FAh, 55h
		db 3 dup(0), 0Fh, 0C5h,	65h, 40h, 0, 0Ch, 0, 15h, 69h
		db 50h,	0, 3 dup(0FFh),	0E9h, 50h, 0, 0FAh, 0FFh, 0FEh
		db 0ABh, 0D0h, 0, 2 dup(0Ah), 0AAh, 0AFh, 0FCh,	2 dup(0)
		db 2, 84h, 55h,	0FCh, 3	dup(0),	5, 15h,	7Ch, 3 dup(0)
		db 5, 45h, 40h,	3 dup(0), 15h, 1, 60h, 0, 0Ah, 0, 0A4h
		db 0, 0AAh, 0A0h, 0Fh, 0AAh, 0A0h, 0, 0Ah, 0ACh, 0, 0FAh
		db 80h,	0, 2Ah,	0F0h, 0, 0Fh, 2	dup(0),	0FFh, 0
		
loc_B72F:		
		db 6, 17h
		db 2 dup(0), 5,	50h, 4 dup(0), 5, 45h, 4 dup(0), 0Ah, 55h
		db 3 dup(0), 1,	2 dup(55h), 30h, 3 dup(0), 0Ah,	0FFh, 0C0h
		db 2 dup(0), 2,	0ACh, 0BFh, 0F0h, 2 dup(0), 0Ah, 0AAh
		db 0ABh, 0F0h, 3 dup(0), 3Fh, 0A9h, 4 dup(0), 0Fh, 95h
		db 4 dup(0), 0F5h, 65h,	40h, 0,	0Ch, 0,	15h, 69h, 50h
		db 0, 3	dup(0FFh), 0E9h, 50h, 0, 0FAh, 0FFh, 0FEh, 0ABh
		db 0D0h, 0, 2 dup(0Ah),	0AAh, 0AFh, 0FCh, 2 dup(0), 2
		db 85h,	55h, 0FCh, 3 dup(0), 5,	54h, 3Ch, 3 dup(0), 1
		db 50h,	5 dup(0), 50h, 5 dup(0), 58h, 5	dup(0),	28h, 5 dup(0)
		db 28h,	4 dup(0), 2Ah, 0A8h
		db 4 dup(0), 0FFh, 0FCh, 2 dup(0)
		
loc_B6A3:		
		db 6, 17h, 8 dup(0), 55h
		db 5 dup(0), 54h, 50h, 4 dup(0), 0A5h, 50h, 3 dup(0), 15h
		db 55h,	53h, 4 dup(0), 0AFh, 0FCh, 3 dup(0), 2Ah, 0CBh
		db 0FFh, 3 dup(0), 2 dup(0AAh),	0BFh, 3	dup(0),	3, 0FAh
		db 0A4h, 4 dup(0), 0FAh, 55h, 3	dup(0),	0Fh, 0C5h, 65h
		db 40h,	0, 0Ch,	0, 15h,	69h, 50h, 0, 3 dup(0FFh), 0E9h
		db 50h,	0, 0FAh, 0FFh, 0FEh, 0ABh, 0D0h, 0, 2 dup(0Ah)
		db 0AAh, 0AFh, 0FCh, 2 dup(0), 2, 85h, 55h, 0FCh, 3 dup(0)
		db 5, 54h, 3Ch,	3 dup(0), 5, 51h, 40h, 3 dup(0), 15h, 5
		db 60h,	0, 0Ah,	0, 0A4h, 0, 0AAh, 0A0h,	0Fh, 0AAh, 0A0h
		db 0, 0Ah, 0ACh, 0, 0FAh, 80h, 0, 2Ah, 0F0h, 0,	0Fh, 2 dup(0)
		db 0FFh, 0
		
loc_B7BB:		
		db 0Ch, 0Bh, 2Ah, 0, 2, 0A8h, 8 dup(0), 82h, 0A0h
		db 0Ah,	0FAh, 6	dup(0),	2Ah, 0,	4 dup(0AAh), 50h, 0Ah
		db 5Ah,	50h, 2 dup(0), 80h, 0A0h, 2 dup(0AAh), 0A8h, 0A5h
		db 0AAh, 5Ah, 0A5h, 0AAh, 50h, 2 dup(0), 18h, 33h, 2 dup(0AAh)
		db 2Ah,	0A5h, 0A9h, 0AAh, 0A5h,	0AAh, 50h, 0, 0Ah, 0, 33h
		db 0Ah,	2Ah, 4 dup(0AAh), 0A5h,	0AAh, 0, 6, 2 dup(0), 28h
		db 3 dup(0AAh),	22h, 2Ah, 2 dup(0AAh), 50h, 0AAh, 3, 32h
		db 0AAh, 0A2h, 2Ah, 28h, 0AAh, 2 dup(0A2h), 8Ah, 0AAh
		db 5Ah,	0Ah, 0AAh, 82h,	0A8h, 2	dup(8Ah), 0AAh,	2 dup(0A8h)
		db 0A2h, 22h, 0A8h, 2, 0A8h, 2 dup(0), 8, 0A0h,	0AAh, 0A0h
		db 8Ah,	0, 88h,	80h, 4 dup(0), 0A2h, 2Ah, 0, 0Ah, 22h
		db 0A0h, 2 dup(0)
		
loc_B841:		
		db 0Ch,	0Bh, 2Ah, 0, 2,	0A8h, 6	dup(0)
		db 9Ah,	0A0h, 82h, 0A0h, 0Ah, 0FAh, 5 dup(0), 2, 0A0h
		db 8, 4	dup(0AAh), 50h,	0Ah, 5Ah, 50h, 0, 2, 60h, 8, 2 dup(0AAh)
		db 0A8h, 0A5h, 0AAh, 5Ah, 0A5h,	0AAh, 50h, 0, 0AAh, 0
		db 3, 33h, 0AAh, 2Ah, 0A5h, 0A9h, 0AAh,	0A5h, 0AAh, 50h
		db 6, 80h, 0Ah,	0AAh, 0Ah, 2Ah,	4 dup(0AAh), 0A5h, 0AAh
		db 0Ah,	80h, 0,	0AAh, 0A8h, 3 dup(0AAh), 22h, 2Ah, 2 dup(0AAh)
		db 5Ah,	80h, 2 dup(0), 0Ah, 0AAh, 8Ah, 88h, 0AAh, 88h
		db 0A8h, 8Ah, 0A8h, 80h, 3 dup(0), 0Ah,	2 dup(2Ah), 0AAh
		db 3 dup(0A2h),	22h, 5 dup(0), 8Ah, 0, 0AAh, 8,	0A0h, 0Ah
		db 88h,	4 dup(0), 0Ah, 22h, 0A0h, 0, 0A2h, 2Ah,	3 dup(0)
		
loc_B8C7:
		db 2, 3, 2 dup(0), 0Fh,	0C0h, 0Fh, 0Ch
		
loc_B8CF:
		db 2, 3, 0Ch, 0C0h
		db 33h,	0FCh, 3Fh, 0F0h
		
loc_B8D7:
		db 2, 3, 2 dup(0), 3Fh, 3	dup(0)
		
loc_B8DF:
		db 0Ch,	2Fh, 5 dup(0), 0FFh, 9 dup(0), 5, 57h, 0FFh, 0D5h
		db 50h,	8 dup(0), 35h, 0FFh, 5Ch, 9 dup(0), 5, 55h, 50h
		db 0Ah dup(0), 55h, 3, 9 dup(0), 3Ah, 0, 0BFh, 9 dup(0)
		db 34h,	0A9h, 2Fh, 0C0h, 8 dup(0), 0FAh, 2Ah, 0AFh, 0F0h
		db 7 dup(0), 3,	0FAh, 0AAh, 2Fh, 0F0h, 0, 0A0h,	5 dup(0)
		db 3, 0FEh, 0Ah, 0BFh, 0F0h, 0Ah, 0AAh,	5 dup(0), 3, 0FFh
		db 0AAh, 0FFh, 0C0h, 2 dup(0AAh), 40h, 5 dup(0), 0FCh
		db 2Bh,	0EAh, 2	dup(0AAh), 1, 0AAh, 80h, 4 dup(0), 0Ah
		db 0AFh, 80h, 2Ah, 0A0h, 0, 2Ah, 0, 2Ah, 0A0h, 2 dup(0)
		db 0A8h, 3, 2Ah, 8Ah, 2	dup(0),	0Ah, 0A8h, 0, 0A8h, 0
		db 0Ah,	0A2h, 0A8h, 0AAh, 0A0h,	4 dup(0), 2, 0AAh, 40h
		db 0AAh, 8Ah, 2	dup(0A8h), 0A0h, 5 dup(0), 1, 2	dup(0AAh)
		db 8, 0A8h, 0AAh, 0A0h,	6 dup(0), 2Ah, 0A0h, 0Ah, 0AAh
		db 2Ah,	80h, 6 dup(0), 0Ah, 0, 2, 0A8h,	80h, 0Ah dup(0)
		db 2, 0AAh, 80h, 9 dup(0), 2Ah,	0AAh, 0Ah dup(0), 0Ah
		db 0AAh, 0Ah dup(0), 0Ah, 2Ah, 80h, 9 dup(0), 2Ah, 0AAh
		db 0E0h, 9 dup(0), 0BAh, 0ABh, 0A8h, 8 dup(0), 0Ah, 0BEh
		db 0AFh, 0AAh, 8 dup(0), 2Ah, 8Fh, 0FFh, 0AAh, 80h, 7 dup(0)
		db 0AAh, 0B3h, 0F2h, 0AAh, 0A0h, 6 dup(0), 2, 0AAh, 0BCh
		db 0Eh,	0AAh, 0A0h, 6 dup(0), 0Ah, 0AAh, 8Fh, 0FEh, 0AAh
		db 0A8h, 6 dup(0), 0Ah,	0AAh, 0B3h, 0C0h, 2Ah, 0A8h, 6 dup(0)
		db 2Ah,	0AAh, 3Ch, 30h,	2, 0AAh, 0
		db 5 dup(0), 2Ah, 0A0h,	0Fh, 0F0h, 0, 0AAh, 6 dup(0), 0AAh
		db 0, 0Fh, 0CCh, 0, 2Ah, 80h, 4	dup(0),	2, 0A8h, 0, 33h
		db 2 dup(0), 0Ah, 80h, 4 dup(0), 2, 0A0h, 4 dup(0), 2Ah
		db 6 dup(0), 0A8h, 4 dup(0), 0AAh, 6 dup(0), 0AAh, 4 dup(0)
		db 0AAh, 6 dup(0), 2Ah,	80h, 2 dup(0), 2, 0A8h,	6 dup(0)
		db 2Ah,	80h, 2 dup(0), 2, 0A8h,	6 dup(0), 0Ah, 40h, 2 dup(0)
		db 1, 0A0h, 6 dup(0), 5, 80h, 2	dup(0),	2, 50h,	6 dup(0)
		db 2, 80h, 2 dup(0), 2,	80h, 6 dup(0), 2, 80h, 2 dup(0)
		db 2, 80h, 6 dup(0), 0Ah, 0A0h,	2 dup(0), 0Ah, 0A0h, 6 dup(0)
		db 0AAh, 0A0h, 2 dup(0), 0Ah, 0AAh, 5 dup(0), 0Ah, 0AAh
		db 0A0h, 2 dup(0), 0Ah,	0AAh, 0A0h, 2 dup(0)
		
loc_BB15:		
		db 12h, 0Ch
		db 0Ah dup(0AAh), 0A8h,	7 dup(0), 0Ah dup(0AAh), 0A8h
		db 7 dup(0), 0ABh, 0FFh, 0ABh, 0FFh, 0ABh, 0FFh, 0ABh
		db 0FFh, 0ABh, 0FFh, 0A8h, 5 dup(0), 20h, 0, 0AFh, 0FFh
		db 0EFh, 0FFh, 0EFh, 0FFh, 0EFh, 0FFh, 0EFh, 0FFh, 0E8h
		db 2, 0A0h, 2Ah, 2, 2 dup(0AAh), 80h, 0AFh, 0ABh, 0EFh
		db 0ABh, 0EFh, 0AAh, 0AFh, 0ABh, 0EFh, 0ABh, 0E8h, 2 dup(8)
		db 80h,	88h, 0,	20h, 0,	0AFh, 0ABh, 0EFh, 0FFh,	0EFh, 0FFh
		db 0AFh, 0FFh, 0EFh, 0FFh, 0E8h, 8, 0, 80h, 88h, 0, 20h
		db 0, 0AFh, 0ABh, 0EFh,	0FFh, 0AFh, 0FFh, 0AFh,	0FFh, 0AFh
		db 0FFh, 0E8h, 2, 82h, 0, 8Ah, 0A0h, 80h, 0, 0AFh, 0ABh
		db 0EFh, 0AAh, 0AFh, 0AAh, 0AFh, 0BEh, 0AFh, 0ABh, 0E8h
		db 0, 22h, 2, 8, 0, 80h, 0, 0AFh, 0FFh,	0EFh, 0AAh, 0AFh
		db 0FFh, 0EFh, 0AFh, 0EFh, 0ABh, 0E8h, 20h, 22h, 2, 20h
		db 2, 2	dup(0),	0ABh, 0FFh, 0ABh, 0AAh,	0ABh, 0FFh, 4 dup(0ABh)
		db 0A8h, 0Ah, 80h, 0A8h, 20h, 2, 2 dup(0), 0Ah dup(0AAh)
		db 0A8h, 7 dup(0), 0Ah dup(0AAh), 0A8h,	7 dup(0)
		
loc_BBEF:		
		db 0Ch
		db 13h,	0Fh, 9 dup(0FFh), 0FCh,	0, 3Fh,	0Ah dup(0FFh)
		db 0, 0Bh dup(0FFh), 0C0h, 0Bh dup(0FFh), 0C0h,	0FFh, 4	dup(3)
		db 30h,	33h, 3 dup(30h), 3Fh, 0C0h, 0FFh, 3Fh, 2 dup(33h)
		db 0CFh, 5 dup(33h), 3Fh, 0C0h,	0FFh, 3Fh, 2 dup(33h)
		db 0CFh, 2 dup(33h), 3 dup(30h), 3Fh, 0C0h, 0FFh, 3Fh
		db 2 dup(33h), 0CFh, 3 dup(33h), 30h, 0F3h, 3Fh, 0C0h
		db 0FFh, 2 dup(3), 33h,	0CFh, 33h, 30h,	3 dup(33h), 3Fh
		db 0C0h, 0Bh dup(0FFh),	0C0h, 0Bh dup(0FFh), 0C0h, 3Fh
		db 0Ah dup(0FFh), 0, 0Fh, 9 dup(0FFh), 0FCh, 6 dup(0)
		db 0Fh,	0C0h, 0Ah dup(0), 3Fh, 0Bh dup(0), 0FFh, 0F0h
		db 0Ah dup(0), 0Fh, 0C0h, 0Ah dup(0), 0Fh, 0Bh dup(0)
		db 0Ch,	6 dup(0)
			
		db 0Ch, 13h, 0Fh, 9 dup(0FFh), 0FCh, 0
		db 3Fh,	2 dup(0FFh), 2 dup(0C0h), 0FFh,	2 dup(3), 3 dup(0FFh)
		db 0, 3	dup(0FFh), 0F3h, 0CCh, 0FFh, 33h, 3Fh, 3 dup(0FFh)
		db 0C0h, 3 dup(0FFh), 0F3h, 0CCh, 0FFh,	2 dup(0Fh), 3 dup(0FFh)
		db 0C0h, 3 dup(0FFh), 0F3h, 0CCh, 0FFh,	33h, 3Fh, 3 dup(0FFh)
		db 0C0h, 3 dup(0FFh), 0F3h, 0C0h, 0FFh,	2 dup(3), 3 dup(0FFh)
		db 0C0h, 0Bh dup(0FFh),	0C0h, 0FFh, 0F0h, 3 dup(30h), 33h
		db 3, 33h, 3, 0Fh, 0FFh, 0C0h, 0FFh, 2 dup(0F3h), 33h
		db 3Ch,	0F3h, 2	dup(33h), 3Fh, 33h, 0FFh, 0C0h,	0FFh, 2	dup(0F3h)
		db 33h,	3Ch, 0F3h, 2 dup(33h), 0Fh, 33h, 0FFh, 0C0h, 0FFh
		db 2 dup(0F3h),	33h, 3Ch, 0F3h,	2 dup(33h), 3Fh, 33h, 0FFh
		db 0C0h, 3Fh, 0F0h, 30h, 33h, 3Ch, 0F3h, 33h, 2	dup(3)
		db 0Fh,	0FFh, 0, 0Fh, 9	dup(0FFh), 0FCh, 6 dup(0), 0Fh
		db 0C0h, 0Ah dup(0), 3Fh, 0Bh dup(0), 0FFh, 0F0h, 0Ah dup(0)
		db 0Fh,	0C0h, 0Ah dup(0), 0Fh, 0Bh dup(0), 0Ch,	6 dup(0)
		
loc_BDBB:		
		db 4, 2	dup(0Fh), 2 dup(0FFh), 0F0h, 3Fh, 2 dup(0FFh)
		db 0FCh, 0FFh, 3, 0C0h,	2 dup(0FFh), 33h, 0CCh,	2 dup(0FFh)
		db 33h,	0CCh, 2	dup(0FFh), 33h,	0CCh, 2	dup(0FFh), 33h
		db 0C0h, 0FFh, 3Fh, 2 dup(0FFh), 0FCh, 0Fh, 2 dup(0FFh)
		db 0F0h, 0, 0Fh, 0C0h, 2 dup(0), 3, 0F0h, 2 dup(0), 3Fh
		db 0FCh, 2 dup(0), 0Fh,	0C0h, 2	dup(0),	3, 0C0h, 3 dup(0)
		db 0C0h, 0
		
loc_BDF9:	
		db 4, 2 dup(0Fh), 2 dup(0FFh),	0F0h, 3Fh, 2 dup(0FFh)
		db 0FCh, 0FFh, 3, 0CCh,	2 dup(0FFh), 33h, 0CCh,	2 dup(0FFh)
		db 33h,	0C3h, 2	dup(0FFh), 33h,	0CCh, 2	dup(0FFh), 3, 0CCh
		db 0CFh, 3Fh, 2	dup(0FFh), 0FCh, 0Fh, 2	dup(0FFh), 0F0h
		db 0, 0Fh
		db 0C0h, 2 dup(0), 3, 0F0h, 2 dup(0), 3Fh, 0FCh, 2 dup(0)
		db 0Fh,	0C0h, 2	dup(0),	3, 0C0h, 3 dup(0), 0C0h, 0, 0Ch
		db 13h,	0Fh, 9 dup(0FFh), 0FCh,	0, 3Ch,	0FCh, 2	dup(0CCh)
		db 6 dup(0Ch), 0Fh, 0, 2 dup(0FCh), 3 dup(0CCh), 0FCh
		db 0FFh, 3Ch, 2	dup(0CCh), 0FFh, 0C0h, 2 dup(0FCh), 3 dup(0CCh)
		db 0FCh, 0Fh, 3Ch, 2 dup(0CCh),	3Fh, 0C0h, 2 dup(0FCh)
		db 3 dup(0CCh),	2 dup(0CFh), 3Ch, 2 dup(0CCh), 0FFh, 0C0h
		db 0FCh, 0Ch, 0F3h, 2 dup(0CCh), 0Ch, 0Fh, 3Ch,	0Ch, 0CCh
		db 0Fh,	0C0h, 0Bh dup(0FFh), 0C0h, 0FFh, 0F0h, 3Fh, 4 dup(3)
		db 2 dup(33h), 3, 0FFh,	0C0h, 0FFh, 0FCh, 0FFh,	2 dup(33h)
		db 2 dup(3Fh), 33h, 3, 3Fh, 0FFh, 0C0h,	0FFh, 0FCh, 0FFh
		db 2 dup(3), 0Fh, 3, 2 dup(33h), 0Fh, 0FFh, 0C0h, 0FFh
		db 0FCh, 0FFh, 3Fh, 0Fh, 3Fh, 0F3h, 2 dup(33h),	3Fh, 0FFh
		db 0C0h, 3Fh, 0F0h, 2 dup(3Fh),	33h, 3 dup(3), 33h, 3
		db 0FFh, 0, 0Fh, 9 dup(0FFh), 0FCh, 6 dup(0), 0Fh, 0C0h
		db 0Ah dup(0), 3Fh, 0Bh	dup(0),	0FFh, 0F0h, 0Ah	dup(0)
		db 0Fh,	0C0h, 0Ah dup(0), 0Fh, 0Bh dup(0), 0Ch,	6 dup(0)
		
loc_BF1D:			
		db 0Ch,	13h, 0Fh, 9 dup(0FFh), 0FCh, 0,	3Ch, 0FCh, 2 dup(0CCh)
		db 6 dup(0Ch), 0Fh, 0, 2 dup(0FCh), 3 dup(0CCh), 0FCh
		db 0FFh, 3Ch, 2	dup(0CCh), 0FFh, 0C0h, 2 dup(0FCh), 3 dup(0CCh)
		db 0FCh, 0Fh, 3Ch, 2 dup(0CCh),	3Fh, 0C0h, 2 dup(0FCh)
		db 3 dup(0CCh),	2 dup(0CFh), 3Ch, 2 dup(0CCh), 0FFh, 0C0h
		db 0FCh, 0Ch, 0F3h, 2 dup(0CCh), 0Ch, 0Fh, 3Ch,	0Ch, 0CCh
		db 0Fh,	0C0h, 0Bh dup(0FFh), 0C0h, 2 dup(0FFh),	0C0h, 0CCh
		db 5 dup(0C0h),	2 dup(0FFh), 0C0h, 2 dup(0FFh),	0CFh, 4	dup(0CCh)
		db 0CFh, 0CCh, 2 dup(0FFh), 0C0h, 2 dup(0FFh), 0C0h, 0CCh
		db 0C0h, 4 dup(0CCh), 2	dup(0FFh), 0C0h, 2 dup(0FFh), 0FCh
		db 0CCh, 0CFh, 4 dup(0CCh), 2 dup(0FFh), 0C0h, 3Fh, 0FFh
		db 2 dup(0C0h),	0CFh, 0C0h, 0CCh, 2 dup(0C0h), 2 dup(0FFh)
		db 0, 0Fh, 9 dup(0FFh),	0FCh, 6	dup(0),	0Fh, 0C0h, 0Ah dup(0)
		db 3Fh,	0Bh dup(0), 0FFh, 0F0h,	0Ah dup(0), 0Fh, 0C0h
		db 0Ah dup(0), 0Fh, 0Bh	dup(0),	0Ch, 6 dup(0)
		
loc_C003:
		db 10h, 0Ah
		db 3Fh,	0F0h, 3Ch, 2 dup(0Fh), 0FFh, 0,	0FFh, 0C0h, 0F3h
		db 0F0h, 0Fh, 0FCh, 3, 0FFh, 0,	0FFh, 0FCh, 3Ch, 2 dup(0Fh)
		db 0FFh, 0C3h, 0FFh, 0F0h, 0FFh, 0FCh, 3Fh, 0FFh, 0Fh
		db 0FFh, 0C0h, 0F0h, 2 dup(3Ch), 2 dup(0Fh), 3,	0C3h, 0C0h
		db 0F0h, 0FCh, 2 dup(3Ch), 2 dup(0Fh), 3, 0C0h,	0F0h, 0
		db 3Ch,	2 dup(0Fh), 3, 0C3h, 0C0h, 2 dup(0F0h),	2 dup(3Ch)
		db 0, 0Fh, 3, 0C0h, 0FFh, 0F0h,	3Ch, 2 dup(0Fh), 0FFh
		db 0C3h, 0C0h, 2 dup(0F0h), 2 dup(3Ch),	0, 0Fh,	3, 0C0h
		db 3Fh,	0FCh, 3Ch, 2 dup(0Fh), 0FFh, 3,	0C0h, 2	dup(0F0h)
		db 2 dup(3Ch), 0FFh, 0Fh, 3, 0C0h, 0, 2	dup(3Ch), 2 dup(0Fh)
		db 0, 3, 0C0h, 2 dup(0F0h), 2 dup(3Ch),	0FFh, 0Fh, 3, 0C0h
		db 0F0h, 2 dup(3Ch), 2 dup(0Fh), 0, 3, 0C0h, 2 dup(0F0h)
		db 2 dup(3Ch), 2 dup(0Fh), 3, 0C0h, 0FFh, 0FCh,	3Fh, 0FFh
		db 0Fh,	0, 3, 0FFh, 2 dup(0F0h), 3Ch, 3Fh, 0FFh, 0Fh, 0FFh
		db 0C0h, 3Fh, 0F0h, 0Fh, 0FCh, 0Fh, 2 dup(0), 0FFh, 0C0h
		db 0F0h, 3Ch, 0Fh, 0FCh, 3, 0FFh, 0, 12h, 0Ah, 0FFh, 0
		db 3Fh,	0FCh, 0Fh, 0FFh, 3, 0FFh, 0F0h,	3Fh, 0F0h, 3Ch
		db 2 dup(0Fh), 3, 0C3h,	0FFh, 0F0h, 0FFh, 0, 3Fh, 0FFh
		db 0Fh,	0FFh, 0C3h, 0FFh, 0F0h,	0FFh, 0FCh, 3Ch, 2 dup(0Fh)
		db 3, 0C3h, 0FFh, 0F0h,	3Ch, 0,	3Ch, 2 dup(0Fh), 3, 0C3h
		db 0C0h, 0, 0F0h, 2 dup(3Ch), 2	dup(0Fh), 0CFh,	0C3h, 0C0h
		db 0, 3Ch, 0, 3Ch, 2 dup(0Fh), 3, 0C3h,	0C0h, 0, 0F0h
		db 0, 3Ch, 2 dup(0Fh), 0FFh, 0C3h, 0C0h, 0, 3Ch, 0, 3Fh
		db 0FFh, 0Fh, 0FFh, 0C3h, 0FFh,	0, 0FFh, 0F0h, 3Ch, 2 dup(0Fh)
		db 0FFh, 0C3h, 0FFh, 0C0h, 3Ch,	0, 3Fh,	0FCh, 0Fh, 0FFh
		db 3, 0FFh, 0, 3Fh, 0FCh, 3Ch, 2 dup(0Fh), 33h,	0C3h, 0FFh
		db 0C0h, 3Ch, 0, 3Ch, 0, 0Fh, 3Ch, 3, 0C0h, 2 dup(0), 2	dup(3Ch)
		db 2 dup(0Fh), 3, 0C3h,	0C0h, 0, 3Ch, 0, 3Ch, 0, 2 dup(0Fh)
		db 3, 0C0h, 0, 0F0h, 2 dup(3Ch), 2 dup(0Fh), 3,	0C3h, 0C0h
		db 0, 0FFh, 0, 3Ch, 0, 0Fh, 3, 0C3h, 0FFh, 0F0h, 0FFh
		db 0FCh
		db 3Fh,	0FFh, 0Fh, 3, 0C3h, 0FFh, 0F0h,	0FFh, 0, 3Ch, 0
		db 0Fh,	3, 0C3h, 0FFh, 0F0h, 3Fh, 0F0h,	0Fh, 0FCh, 0Fh
		db 3, 0C3h, 0FFh, 0F0h

loc_C15B:
		db 6, 10h,	0Ch dup(0), 8, 5 dup(0)
		db 28h,	5 dup(0), 6Ah, 5 dup(0), 1Ah, 80h, 2 dup(0), 2Ah
		db 0, 5, 0AAh, 0FFh, 0FDh, 0A0h, 80h, 0, 2 dup(0FFh), 0FDh
		db 5Ah,	0BCh, 5, 5Fh, 0FFh, 0F5h, 0AAh,	0CDh, 0, 5, 55h
		db 52h,	0A0h, 31h, 2 dup(0), 29h, 8Ah, 4 dup(0), 4, 5 dup(0)
		db 1, 50h, 5 dup(0), 44h, 0Eh dup(0)
		
loc_C1BD:	
		db 6, 10h, 0, 0Ah, 55h
		db 50h,	2 dup(0), 0Ah, 0AFh, 0FFh, 0F5h, 2 dup(0), 2, 2	dup(0AAh)
		db 0FFh, 40h, 2	dup(0),	0AAh, 2	dup(0FFh), 0D0h, 0, 8
		db 0Ah,	0AAh, 0AFh, 0D0h, 0, 28h, 0, 0AFh, 0FFh, 0D0h
		db 0, 6Ah, 0, 2Ah, 0AFh, 40h, 0, 1Ah, 80h, 0Ah,	0FDh, 0AAh
		db 0, 5, 0AAh, 0AFh, 0F6h, 0A0h, 80h, 0, 6Ah, 0ABh, 0F6h
		db 0AAh, 0BCh, 0, 0Ah, 3 dup(0AAh), 0FDh, 2 dup(0), 2 dup(0A2h)
		db 0A0h, 1, 2 dup(0), 29h, 8Ah,	4 dup(0), 4, 5 dup(0)
		db 1, 50h, 5 dup(0), 44h, 2 dup(0)
		
loc_C21F:
		db 6, 10h, 8, 5 dup(0)
		db 28h,	5 dup(0), 6Ah, 5 dup(0), 1Ah, 80h, 2 dup(0), 0AAh
		db 0, 5, 2 dup(0AAh), 0A2h, 0A0h, 80h, 0, 6Ah, 0A8h, 0EAh
		db 0AAh, 0BCh, 0, 0Ah, 0A2h, 0F6h, 0AAh, 0FFh, 2 dup(0)
		db 0A2h, 0BDh, 0A0h, 3,	2 dup(0), 0Ah, 0BDh, 3 dup(0)
		db 6Ah,	0AAh, 0FDh, 2 dup(0), 5, 7Fh, 0FFh, 0D4h, 3 dup(0)
		db 2 dup(55h), 40h, 1Ah	dup(0)
		
loc_C281:
		db 2 dup(4), 2 dup(0), 2
		db 80h,	0, 55h,	56h, 0AAh, 0, 3Fh, 0FEh, 0AAh, 2 dup(0)
		db 2, 80h
		
loc_C293:		
		db 6, 17h, 9 dup(0), 55h, 4 dup(0), 5, 15h, 4 dup(0)
		db 5, 5Ah, 4 dup(0), 0C5h, 55h,	54h, 3 dup(0), 3Fh, 0FAh
		db 4 dup(0), 0FFh, 0E3h, 0A8h, 3 dup(0), 0FEh, 2 dup(0AAh)
		db 3 dup(0), 1Ah, 0AFh,	0C0h, 3	dup(0),	55h, 0AFh, 3 dup(0)
		db 1, 59h, 53h,	0F0h, 2	dup(0),	5, 69h,	54h, 0,	30h, 0
		db 5, 6Bh, 3 dup(0FFh),	0, 7, 0EAh, 0BFh, 0FFh,	0AFh, 0
		db 3Fh,	0FAh, 0AAh, 2 dup(0A0h), 0, 3Fh, 55h, 52h, 80h
		db 2 dup(0), 3Ch, 15h, 50h, 3 dup(0), 1, 45h, 50h, 3 dup(0)
		db 9, 50h, 54h,	2 dup(0), 0Ah, 0AAh, 0,	1Ah, 0,	0A0h, 3Ah
		db 0A0h, 0, 0Ah, 0AAh, 0F0h, 0Fh, 0A8h,	0, 2, 0AFh, 2 dup(0)
		db 0FFh, 2 dup(0), 0F0h, 0
		
loc_C31F:		
		db 6, 17h, 2 dup(0), 5, 50h, 4	dup(0)
		db 51h,	50h, 4 dup(0), 55h, 0A0h, 3 dup(0), 0Ch, 2 dup(55h)
		db 40h,	2 dup(0), 3, 0FFh, 0A0h, 3 dup(0), 0Fh,	0FEh, 3Ah
		db 80h,	2 dup(0), 0Fh, 0EAh, 0AAh, 0A0h, 3 dup(0), 6Ah
		db 0FCh, 4 dup(0), 56h,	0F0h, 3	dup(0),	1, 59h,	5Fh, 3 dup(0)
		db 5, 69h, 54h,	0, 30h,	0, 5, 6Bh, 3 dup(0FFh),	0, 7, 0EAh
		db 0BFh, 0FFh, 0AFh, 0,	3Fh, 0FAh, 0AAh, 2 dup(0A0h), 0
		db 3Fh,	55h, 52h, 80h, 2 dup(0), 3Ch, 15h, 50h,	4 dup(0)
		db 5, 40h, 4 dup(0), 5,	5 dup(0), 25h, 5 dup(0), 28h, 5	dup(0)
		db 28h,	5 dup(0), 2Ah, 0A8h, 4 dup(0), 3Fh, 0FFh, 2 dup(0)

loc_C3AB:		
		db 6, 17h, 9 dup(0), 55h, 4 dup(0), 5, 15h, 4 dup(0), 5
		db 5Ah,	4 dup(0), 0C5h,	55h, 54h, 3 dup(0), 3Fh, 0FAh
		db 4 dup(0), 0FFh, 0E3h, 0A8h, 3 dup(0), 0FEh, 2 dup(0AAh)
		db 3 dup(0), 1Ah, 0AFh,	0C0h, 3	dup(0),	55h, 0AFh, 3 dup(0)
		db 1, 59h, 53h,	0F0h, 2	dup(0),	5, 69h,	54h, 0,	30h, 0
		db 5, 6Bh, 3 dup(0FFh),	0, 7, 0EAh, 0BFh, 0FFh,	0AFh, 0
		db 3Fh,	0FAh, 0AAh, 2 dup(0A0h), 0, 3Fh, 55h, 12h, 80h
		db 2 dup(0), 3Dh, 54h, 50h, 3 dup(0), 1, 51h, 50h, 3 dup(0)
		db 9, 40h, 54h,	2 dup(0), 0Ah, 0AAh, 0,	1Ah, 0,	0A0h, 3Ah
		db 0A0h, 0, 0Ah, 0AAh, 0F0h, 0Fh, 0A8h,	0, 2, 0AFh, 2 dup(0)
		db 0FFh, 2 dup(0), 0F0h, 0
		
loc_C437:	
		db 0Ch, 0Bh, 0Ah, 0A6h, 6 dup(0)
		db 2Ah,	80h, 0,	0A8h, 20h, 0Ah,	80h, 5 dup(0), 0AFh, 0A0h
		db 0Ah
		db 82h,	20h, 9,	80h, 0,	5, 0A5h, 0A0h, 5, 4 dup(0AAh)
		db 0, 0AAh, 0, 5, 0AAh,	5Ah, 0A5h, 0AAh, 5Ah, 2Ah, 2 dup(0AAh)
		db 2, 90h, 5, 0AAh, 5Ah, 0AAh, 6Ah, 5Ah, 0A8h, 0AAh, 0CCh
		db 0C0h, 2, 0A0h, 0AAh,	5Ah, 4 dup(0AAh), 0A8h,	0A0h, 0AAh
		db 0A0h, 2, 0A5h, 2 dup(0AAh), 0A8h, 88h, 3 dup(0AAh)
		db 2Ah,	0AAh, 0, 2, 2Ah, 0A2h, 2Ah, 22h, 0AAh, 22h, 0A2h
		db 0AAh, 0A0h, 3 dup(0), 88h, 3	dup(8Ah), 0AAh,	2 dup(0A8h)
		db 0A0h, 4 dup(0), 22h,	0A0h, 0Ah, 20h,	0AAh, 0, 0A2h
		db 7 dup(0), 0A8h, 8Ah,	0, 0Ah,	88h, 0A0h, 3 dup(0)
		
loc_C4BD:		
		db 0Ch
		db 0Bh,	8 dup(0), 2Ah, 80h, 0, 0A8h, 0,	0A8h, 6	dup(0)
		db 0AFh, 0A0h, 0Ah, 82h, 0Ah, 2, 2 dup(0), 5, 0A5h, 0A0h
		db 5, 4	dup(0AAh), 24h,	2 dup(0), 5, 0AAh, 5Ah,	0A5h, 0AAh
		db 5Ah,	2Ah, 2 dup(0AAh), 0A0h,	0, 5, 0AAh, 5Ah, 0AAh
		db 6Ah,	5Ah, 0A8h, 2 dup(0AAh),	0CCh, 90h, 0, 0AAh, 5Ah
		db 4 dup(0AAh),	0A8h, 0A0h, 0CCh, 0, 0AAh, 5, 2	dup(0AAh)
		db 0A8h, 88h, 3	dup(0AAh), 28h,	2 dup(0), 0A5h,	0AAh, 0A2h
		db 2 dup(8Ah), 0AAh, 28h, 0A8h,	8Ah, 0AAh, 8Ch,	0C0h, 2Ah
		db 88h,	8Ah, 2 dup(2Ah), 0AAh, 2 dup(0A2h), 2Ah, 82h, 0AAh
		db 0A0h, 2, 22h, 0, 0A2h, 0Ah, 0AAh, 0Ah, 20h, 2 dup(0)
		db 2Ah,	80h, 2 dup(0), 0Ah, 88h, 0A0h, 0, 0A8h,	8Ah, 4 dup(0)
		
loc_C543:
		db 2, 5, 2 dup(0), 15h,	0, 5, 0FCh, 15h, 3 dup(0)
		
loc_C54F:	
		db 0Ch
		db 2Fh,	6 dup(0), 0FFh,	9 dup(0), 5, 57h, 0FFh,	0D5h, 50h
		db 8 dup(0), 35h, 0FFh,	5Ch, 9 dup(0), 5, 55h, 50h, 9 dup(0)
		db 0C0h, 55h, 0Ah dup(0), 0FEh,	0, 0ACh, 8 dup(0), 3, 0F8h
		db 6Ah,	1Ch, 8 dup(0), 0Fh, 0FAh, 0A8h,	0AFh, 6	dup(0)
		db 0Ah,	0, 0Fh,	0F8h, 0AAh, 0AFh, 0C0h,	5 dup(0), 0AAh
		db 0A0h, 0Fh, 0FEh, 0A0h, 0BFh,	0C0h, 4	dup(0),	1, 2 dup(0AAh)
		db 3, 0FFh, 0AAh, 0FFh,	0C0h, 3	dup(0),	2, 0AAh, 40h, 2	dup(0AAh)
		db 0ABh, 0E8h, 3Fh, 5 dup(0), 0A8h, 0, 0Ah, 0A8h, 2, 0FAh
		db 0A0h, 4 dup(0), 2Ah,	0A0h, 2	dup(0),	0A2h, 0A8h, 0C0h
		db 2Ah,	2 dup(0), 0Ah, 0A8h, 4 dup(0), 0Ah, 0AAh, 2Ah
		db 8Ah,	0A0h, 0, 2Ah, 5	dup(0),	0Ah, 2 dup(2Ah), 0A2h
		db 0AAh, 1, 0AAh, 80h, 4 dup(0), 0Ah, 0AAh, 2Ah, 20h, 2	dup(0AAh)
		db 40h,	5 dup(0), 2, 0A8h, 0AAh, 0A0h, 0Ah, 0A8h, 7 dup(0)
		db 2, 2Ah, 80h,	0, 0A0h, 6 dup(0), 2, 0AAh, 80h, 0Ah dup(0)
		db 0AAh, 0A8h, 0Ah dup(0), 0AAh, 0A0h, 9 dup(0), 2, 0A8h
		db 0A0h, 9 dup(0), 0Bh,	0AAh, 0A8h, 9 dup(0), 2Ah, 0EAh
		db 0AEh, 9 dup(0), 0AAh, 0FAh, 0BEh, 0A0h, 7 dup(0), 2
		db 0AAh, 0FFh, 0F2h, 0A8h, 7 dup(0), 0Ah, 0AAh,	8Fh, 0CEh
		db 0AAh, 7 dup(0), 0Ah,	0AAh, 0B0h, 3Eh, 0AAh, 80h, 6 dup(0)
		db 2Ah,	0AAh, 0BFh, 0F2h, 0AAh,	0A0h, 6	dup(0),	2Ah, 0A8h
		db 3, 0CEh, 0AAh, 0A0h,	6 dup(0), 0AAh,	80h, 0Ch, 3Ch
		db 0AAh, 0A8h, 6 dup(0), 0AAh, 0, 0Fh, 0F0h, 0Ah, 0A8h
		db 5 dup(0), 2,	0A8h, 0, 33h, 0F0h, 0, 0AAh, 5 dup(0)
		db 2, 0A0h, 2 dup(0), 0CCh, 0, 2Ah, 80h, 5 dup(0), 0A8h
		db 4 dup(0), 0Ah, 80h, 5 dup(0), 0AAh, 4 dup(0), 2Ah, 6	dup(0)
		db 0AAh, 4 dup(0), 0AAh, 6 dup(0), 2Ah,	80h, 2 dup(0)
		db 2, 0A8h, 6 dup(0), 2Ah, 80h,	2 dup(0), 2, 0A8h, 6 dup(0)
		db 0Ah,	40h, 2 dup(0), 1, 0A0h,	6 dup(0), 5, 80h, 2 dup(0)
		db 2, 50h, 6 dup(0), 2,	80h, 2 dup(0), 2, 80h, 6 dup(0)
		db 2, 80h, 2 dup(0), 2,	80h, 6 dup(0), 0Ah, 0A0h, 2 dup(0)
		db 0Ah,	0A0h, 6	dup(0),	0AAh, 0A0h, 2 dup(0), 0Ah, 0AAh
		db 5 dup(0), 0Ah, 0AAh,	0A0h, 2	dup(0),	0Ah, 0AAh, 0A0h
		db 2 dup(0)
		
loc_C785:		
		db 6,	0Eh, 0,	2, 0A0h, 4 dup(0), 2 dup(2Ah)
		db 4 dup(0), 0A0h, 2, 80h, 2 dup(0), 2,	80h, 3,	80h, 2 dup(0)
		db 2, 80h, 0Ch,	2 dup(0), 0A8h,	2, 80h,	2 dup(0), 2, 0A0h
		db 2, 80h, 2 dup(0), 0Ah, 0A8h,	0, 0A0h, 5 dup(0), 0AAh
		db 0, 0Ah
		db 0AAh, 2 dup(0), 2Ah,	0A2h, 22h, 0A0h, 80h, 0, 2, 0A8h
		db 8Ah,	0AAh, 3	dup(0),	2Ah, 0AAh, 0, 28h, 2 dup(0), 8
		db 88h,	0AAh, 80h, 2 dup(0), 8,	22h, 0Ah, 0A8h
		
loc_C7DB:
		db	6, 0Eh
		db 0, 0A8h, 4 dup(0), 2	dup(0Ah), 4 dup(0), 28h, 0Eh, 4	dup(0)
		db 28h,	30h, 4 dup(0), 28h, 5 dup(0), 0Ah, 4 dup(0), 0A0h
		db 0Ah,	80h, 2 dup(0), 0Ah, 0A8h, 2, 0A8h, 5 dup(0), 0AAh
		db 80h,	0Ah, 0AAh, 2 dup(0), 2Ah, 0A2h,	22h, 0A0h, 80h
		db 0, 2, 0A8h, 8Ah, 0AAh, 3 dup(0), 2Ah, 0AAh, 4 dup(0)
		db 0A2h, 88h, 0AAh, 0A8h, 0, 2,	2 dup(8), 0Ah, 0A0h
		
loc_C831:
		db 6
		db 17h
		db	3 dup(0), 0F0h,	4 dup(0), 0Fh, 0FFh, 4 dup(0)
		db 0Ah,	0AAh, 4	dup(0),	2 dup(0FFh), 0F0h, 3 dup(0), 0Ah
		db 55h,	4 dup(0), 0ACh,	95h, 4 dup(0), 0AAh, 0A9h, 4 dup(0)
		db 0Ah,	0ADh, 4	dup(0),	2, 0D5h, 54h, 3	dup(0),	3Fh, 5Bh
		db 0D5h, 40h, 2	dup(0),	0FFh, 5Ah, 0F5h, 50h, 2	dup(0)
		db 0FFh, 5Ah, 0F5h, 50h, 2 dup(0), 3Fh,	6Ah, 0F5h, 50h
		db 2 dup(0), 2Ah, 0ABh,	75h, 50h, 2 dup(0), 0AAh, 0FFh
		db 0C5h, 40h, 2	dup(0),	8Fh, 0FCh, 4 dup(0), 2,	0A0h, 5	dup(0)
		db 0A4h, 5 dup(0), 54h,	5 dup(0), 1Ch, 5 dup(0), 3Ch, 4	dup(0)
		db 2Ah,	0A8h, 4	dup(0),	0FFh, 0FCh, 2 dup(0)
		
loc_C8BD:
		db 6, 17h
		db 8	dup(0)
		db 0Fh,	5 dup(0), 0FFh,	0F0h, 4	dup(0),	0AAh, 0A0h, 3 dup(0)
		db 0Fh,	2 dup(0FFh), 4 dup(0), 0A5h, 50h, 3 dup(0), 0Ah
		db 0C9h, 50h, 3	dup(0),	0Ah, 0AAh, 90h,	4 dup(0), 0AAh
		db 0ACh, 4 dup(0), 0Ah,	0F5h, 54h, 3 dup(0), 0Fh, 0D6h
		db 0D5h, 40h, 2	dup(0),	3Fh, 5Ah, 0A5h,	50h, 2 dup(0)
		db 0FFh, 5Fh, 0A9h, 50h, 2 dup(0), 0FFh, 5Fh, 0FAh, 50h
		db 2 dup(0), 0B5h, 96h,	7Ah, 40h, 0, 2Ah, 0AFh,	0FFh, 0CAh
		db 2 dup(0), 8Ah, 0Fh, 0FCh, 2,	0A0h, 2	dup(0),	0Ah, 0F2h
		db 80h,	3 dup(0), 6Ah, 0Ah, 90h, 0, 0Ah, 0, 54h, 0, 57h
		db 0E0h, 0Fh, 0AFh, 0D4h, 0, 0Fh, 0ACh,	0, 0FAh, 0C0h
		db 0, 2Ah, 0F0h, 0, 0Fh, 2 dup(0), 0FFh, 0
		
loc_C949:
		db 6, 17h
		db 8 dup(0)
		db 0Fh,	5 dup(0), 0FFh,	0F0h, 4	dup(0),	0AAh, 0A0h, 3 dup(0)
		db 0Fh,	2 dup(0FFh), 4 dup(0), 0A5h, 50h, 3 dup(0), 0Ah
		db 0C9h, 50h, 3	dup(0),	0Ah, 0AAh, 90h,	4 dup(0), 0AAh
		db 0ACh, 4 dup(0), 0Ah,	0F5h, 54h, 3 dup(0), 0Fh, 0D9h
		db 0D5h, 40h, 2	dup(0),	3Fh, 6Ah, 0F5h,	50h, 2 dup(0)
		db 0FFh, 0AAh, 0F5h, 50h, 2 dup(0), 0AAh, 0AFh,	0F5h, 50h
		db 0, 0Ah, 0AAh, 96h, 75h, 40h,	0, 2Ah,	0Ch, 0FFh, 0CAh
		db 2 dup(0), 20h, 8Fh, 3Fh, 0C2h, 80h, 2 dup(0), 0Ah, 0CEh
		db 80h,	3 dup(0), 6Ah, 0Ah, 90h, 0, 0Ah, 0, 54h, 0, 57h
		db 0E0h, 0Fh, 0AFh, 0D4h, 0, 0Fh, 0ACh,	0, 0FAh, 0C0h
		db 0, 2Ah, 0F0h, 0, 0Fh, 2 dup(0), 0FFh, 0
		
loc_C9D5:
		db 6, 17h
		db 32h	dup(0)
		db 0F0h, 4 dup(0), 0Fh,	0FFh, 4	dup(0),	0Ah, 0AAh, 4 dup(0)
		db 2 dup(0FFh),	0F0h, 3	dup(0),	0Ah, 55h, 4 dup(0), 0A0h
		db 95h,	2, 0A0h, 2 dup(0), 0AAh, 0A9h, 0FAh, 0AAh, 2 dup(0)
		db 0Ah,	0AFh, 0EAh, 0Ah, 0A0h, 2 dup(0), 0FFh, 0F8h, 2
		db 80h,	0, 0A8h, 0EBh, 0D7h, 2,	20h, 0Ah, 9Ah, 6Ah, 3Fh
		db 0C0h, 0, 2Ah, 1Bh, 58h, 0FFh, 0C0h, 0, 22h, 0Fh, 0C3h
		db 0FFh, 3 dup(0), 0Ah,	2Ah, 0A8h, 3 dup(0), 3Ch, 0FFh
		db 0FCh, 2 dup(0)
		
loc_CA61:
		db 6, 17h
		db 0, 0Fh, 5 dup(0), 0FFh, 0F0h
		db 4 dup(0), 0AAh, 0A0h, 3 dup(0), 0Fh,	2 dup(0FFh), 4 dup(0)
		db 0A5h, 50h, 3	dup(0),	0Ah, 0C9h, 50h,	3 dup(0), 0Ah
		db 0AAh, 90h, 4	dup(0),	0AAh, 0ACh, 4 dup(0), 0Ah, 0F5h
		db 54h,	3 dup(0), 0Fh, 0DAh, 0D5h, 40h,	2 dup(0), 3Fh
		db 6Ah,	95h, 50h, 2 dup(0), 0FFh, 7Ah, 0A5h, 50h, 2 dup(0)
		db 0FFh, 5Fh, 0A9h, 50h, 2 dup(0), 3Fh,	0FAh, 0A5h, 40h
		db 2 dup(0), 0Fh, 0AAh,	0F0h, 3	dup(0),	3, 0AFh, 0F0h
		db 4 dup(0), 0BFh, 0C0h, 4 dup(0), 0Fh,	0E8h, 5	dup(0)
		db 0A9h, 5 dup(0), 5, 7Eh, 5 dup(0), 0FAh, 0C0h, 3 dup(0)
		db 2, 0AFh, 4 dup(0), 0Fh, 0F0h
		db 0
		
loc_CAED:
		db 6, 17h
		db 3 dup(0), 0F0h, 4	dup(0),	0Fh, 0FFh, 4 dup(0)
		db 0Ah,	0AAh, 4	dup(0),	2 dup(0FFh), 0F0h, 3 dup(0), 0Ah
		db 55h,	4 dup(0), 0ACh,	95h, 4 dup(0), 0AAh, 0A9h, 3 dup(0)
		db 20h,	0Ah, 0AAh, 3 dup(0), 0AAh, 0, 0A5h, 54h, 2 dup(0)
		db 2Ah,	83h, 0D7h, 0D5h, 40h, 2	dup(0),	0AFh, 6Bh, 0F5h
		db 50h,	2 dup(0), 2Ah, 0AAh, 0F5h, 50h,	2 dup(0), 0Ah
		db 0AFh, 0F5h, 50h, 2 dup(0), 3Fh, 5Fh,	0F5h, 40h, 2 dup(0)
		db 0ACh, 0F6h, 70h, 0, 0A0h, 6,	0A3h, 0FFh, 0C0h, 0, 0FAh
		db 0F5h, 0Ah, 0FCh, 2 dup(0), 0Fh, 0ACh, 2Ah, 4	dup(0)
		db 0F0h, 68h, 3	dup(0),	0Ah, 3,	54h, 3 dup(0), 0Fh, 0A3h
		db 0F0h, 4 dup(0), 0FAh, 0C0h, 4 dup(0), 0Fh, 4	dup(0)
		
loc_CB79:
		db 6, 17h
		db 9 dup(0), 0Fh, 5 dup(0), 0FFh, 0F0h,	4 dup(0)
		db 0AAh, 0A0h, 3 dup(0), 0Fh, 2	dup(0FFh), 0A8h, 3 dup(0)
		db 0A5h, 50h, 0AAh, 2 dup(0), 0Ah, 0C9h, 50h, 0AAh, 2 dup(0)
		db 0Ah,	0AAh, 90h, 28h,	3 dup(0), 0AAh,	0A0h, 28h, 3 dup(0)
		db 2Ah,	54h, 0A0h, 2 dup(0), 0Fh, 0F5h,	76h, 0A0h, 2 dup(0)
		db 3Fh,	0D6h, 0AAh, 90h, 2 dup(0), 0FFh, 0D7h, 0A9h, 50h
		db 2 dup(0), 0FFh, 0D7h, 0F5h, 50h, 0, 0Ah, 99h, 96h, 55h
		db 40h,	0, 2Ah,	0Ch, 0FFh, 0C0h, 2 dup(0), 20h,	8Fh, 3Fh
		db 0C0h, 3 dup(0), 0Ah,	0CEh, 80h, 3 dup(0), 6Ah, 0Ah
		db 90h,	0, 0Ah,	0, 54h,	0, 57h,	0E0h, 0Fh, 0AFh, 0D4h
		db 0, 0Fh, 0ACh, 0, 0FAh, 0C0h,	0, 2Ah,	0F0h, 0, 0Fh, 2	dup(0)
		db 0FFh, 0
		
loc_CC05:
		db 6, 17h
		db 8 dup(0), 0F0h, 4 dup(0), 0Fh, 0FFh
		db 4 dup(0), 0Ah, 0AAh,	4 dup(0), 2 dup(0FFh), 0F0h, 3 dup(0)
		db 0Ah,	55h, 4 dup(0), 0ACh, 95h, 2, 80h, 2 dup(0), 0AAh
		db 0A9h, 4Ah, 0A0h, 2 dup(0), 0Ah, 0AAh, 5Dh, 55h, 3 dup(0)
		db 2Bh,	57h, 55h, 40h, 0, 2, 0AAh, 0FFh, 0D5h, 50h, 2Ah
		db 2 dup(0AAh),	0BFh, 0F5h, 50h, 0AAh, 80h, 0F5h, 0FFh
		db 0F5h, 50h, 82h, 0, 0FDh, 7Fh, 0F5h, 40h, 2 dup(0), 35h
		db 96h,	70h, 3 dup(0), 0Fh, 0FFh, 0C0h,	3 dup(0), 0Fh
		db 0FCh, 4 dup(0), 0Ah,	0F2h, 80h, 3 dup(0), 6Ah, 0Ah
		db 90h,	0, 0Ah,	0, 54h,	0, 57h,	0E0h, 0Fh, 0AFh, 0D4h
		db 0, 0Fh, 0ACh, 0, 0FAh, 0C0h,	0, 2Ah,	0F0h, 0, 0Fh, 2	dup(0)
		db 0FFh, 0
		
loc_CC91:
		db 6, 17h
		db 21h	dup(0),	0Fh, 5 dup(0), 0FFh, 0F0h
		db 4 dup(0), 0AAh, 0A0h, 3 dup(0), 0Fh,	2 dup(0FFh), 4 dup(0)
		db 0A5h, 50h, 3	dup(0),	0Ah, 0A9h, 50h,	3 dup(0), 0Ah
		db 0AAh, 90h, 4	dup(0),	0AAh, 0A0h, 4 dup(0), 0Ah, 0F0h
		db 4 dup(0), 0Dh, 55h, 40h, 3 dup(0), 35h, 0EFh, 54h, 3	dup(0)
		db 0F5h, 0ABh, 55h, 3 dup(0), 0F5h, 0EAh, 55h, 0E0h, 2 dup(0)
		db 55h,	0FAh, 95h, 0E0h, 0Ah, 0BFh, 0F9h, 0FEh,	94h, 0E0h
		db 6Ah,	0BFh, 0FFh, 56h, 80h, 0EFh, 50h, 0Fh, 0FFh, 0FAh
		db 80h,	0EFh, 2	dup(0),	0FFh, 0EAh, 0A8h
		
loc_CD1D:
		db 6, 17h, 2Bh dup(0)
		db 0FFh, 0FCh, 4 dup(0), 0AAh, 0A0h, 4 dup(0), 0F0h, 5 dup(0)
		db 0F0h, 5 dup(0), 50h,	5 dup(0), 68h, 5 dup(0), 28h, 3	dup(0)
		db 0F0h, 0, 2Ah, 2 dup(0), 3, 0FFh, 0, 2Ah, 2 dup(0), 0FAh
		db 0FFh, 0, 0FFh, 2 dup(0), 3Fh, 0AFh, 0, 0FFh,	2 dup(0)
		db 2Bh,	0FAh, 3, 0FCh, 0FFh, 0C0h, 2Ah,	7Fh, 0Fh, 0F5h
		db 55h,	5Ch, 2Ah, 57h, 0Fh, 0F7h, 0FFh,	97h, 2Ah, 54h
		db 0Ah,	0A7h, 0FAh, 0A5h, 0FAh,	50h, 20h, 2 dup(0AAh)
		db 0FDh, 7Eh, 0
		
loc_CDA9:
		db 6, 17h
		db 15h, 54h, 4 dup(0), 2 dup(55h)
		db 4 dup(0), 2 dup(55h), 0, 0Fh, 2 dup(0), 55h,	54h, 0
		db 0Ah,	0F0h, 0, 0FFh, 0FDh, 0C0h, 0Eh,	0AFh, 0, 0FFh
		db 0FDh, 0F0h, 1Fh, 0Ah, 0, 0ABh, 0FBh,	0F3h, 0A4h, 2 dup(0)
		db 0EAh, 9Fh, 0FCh, 0E0h, 2 dup(0), 2, 0AFh, 0FFh, 4 dup(0)
		db 0A0h, 0FFh, 0A0h, 3 dup(0), 0A0h, 0Eh, 0A5h,	3 dup(0)
		db 0A0h, 0, 27h, 0F0h, 0, 2, 88h, 2 dup(0), 0EAh, 2 dup(0)
		db 80h,	2 dup(0), 0AFh,	2 dup(0), 80h, 0, 0Ah, 0F0h
		db 4 dup(0), 0Fh, 2Ch dup(0)
		
loc_CE35:
		db 6, 17h
		db 15h, 54h,	4 dup(0)
		db 2 dup(55h), 22h, 3 dup(0), 55h, 6Ah,	0A8h, 3	dup(0)
		db 56h,	0AAh, 0A0h, 0, 2Ch, 0, 0FAh, 0BDh, 0C8h, 0, 0EBh
		db 0, 0EAh, 0FDh, 0F0h,	7, 0FAh, 0C0h, 0ABh, 0FBh, 0FEh
		db 0A9h, 2, 0B0h, 0FFh,	0DFh, 0FFh, 0A0h, 0, 0A0h, 0, 3
		db 0FFh, 4 dup(0), 3Ch,	5 dup(0), 0Fh, 0C0h, 4 dup(0)
		db 2, 80h, 4 dup(0), 2,	80h, 5 dup(0), 50h, 5 dup(0), 70h
		db 5 dup(0), 0F0h, 4 dup(0), 2Ah, 0A0h,	4 dup(0), 0FFh
		db 0F0h, 21h dup(0)
		
loc_CEC1:		
		db 6, 17h
		db 9 dup(0), 40h, 30h, 6 dup(0)
		db 80h,	7 dup(0), 1, 7 dup(0), 0Fh, 0, 0Ch, 3 dup(0), 0FFh
		db 0F0h, 2 dup(0), 0Ch,	0, 0AAh, 0A0h, 3 dup(0), 0Fh, 2	dup(0FFh)
		db 4 dup(0), 0A5h, 50h,	3 dup(0), 0Ah, 0C9h, 50h, 3 dup(0)
		db 0Ah,	0AAh, 90h, 4 dup(0), 0AAh, 0A0h, 4 dup(0), 0Ah
		db 0F0h, 4 dup(0), 0Dh,	55h, 40h, 3 dup(0), 35h, 0EFh
		db 54h,	3 dup(0), 0F5h,	0AFh, 55h, 3 dup(0), 0F5h, 0AFh
		db 55h,	0E0h, 2	dup(0),	55h, 0EBh, 55h,	0E0h, 0, 3, 0F9h
		db 0E9h, 54h, 0E0h, 0, 3Fh, 0FFh, 68h, 0, 0EFh,	5Ah, 0BFh
		db 0FFh, 0A8h, 0, 0EFh,	5Ah, 0BFh, 0FEh, 0AAh, 80h
		
loc_CF4D:
		db 6
		db 17h
		db	0Ah dup(0), 10h, 3 dup(0), 10h,	0Fh, 5 dup(0)
		db 0FFh, 0F0h, 4 dup(0), 0AAh, 0A0h, 30h, 2 dup(0), 0Fh
		db 2 dup(0FFh),	2 dup(0), 2, 0,	0Ah, 5 dup(0), 1Ah, 40h
		db 4, 3	dup(0),	55h, 50h, 4 dup(0), 0A5h, 50h, 3 dup(0)
		db 0Ah,	0A9h, 50h, 3 dup(0), 0Ah, 0AAh,	90h, 4 dup(0)
		db 0AAh, 0A0h, 4 dup(0), 0Ah, 0F0h, 4 dup(0), 0Dh, 55h
		db 40h,	3 dup(0), 35h, 0EFh, 54h, 3 dup(0), 0F5h, 0ABh
		db 55h,	3 dup(0), 0F5h,	0EAh, 55h, 0E0h, 2 dup(0), 55h
		db 0FAh, 95h, 0E0h, 0Ah, 0BFh, 0F9h, 0FEh, 94h,	0E0h, 6Ah
		db 0BFh, 0FFh, 56h, 80h, 0EFh, 50h, 0Fh, 0FFh, 0FAh, 80h
		db 0EFh, 2 dup(0), 0FFh, 0EAh, 0A8h
		
loc_CFD9:
		db 3, 8, 2 dup(0), 0FFh
		db 2 dup(0), 3Fh, 0, 3,	0C3h, 28h, 3Ch,	0, 0ABh, 0C0h
		db 0, 3Eh, 80h,	0, 2, 80h, 0, 2, 2 dup(0)
		
loc_CFF3:
		db 6, 3, 5 dup(0)
		db 0A0h, 4 dup(55h), 56h, 0AAh,	5 dup(0), 0A0h
		
loc_D007:
		db	6, 15h
		db 30h,	4 dup(0), 0C0h,	3Ch, 5,	2 dup(55h), 3, 0C0h, 0Fh
		db 0D6h, 0AAh, 0A9h, 7Fh, 0, 3,	5Bh, 0FFh, 0FEh, 5Ch, 2	dup(0)
		db 6Fh,	2 dup(0Fh), 90h, 2 dup(0), 6Fh,	30h, 0CFh, 90h
		db 0A0h, 0, 5Bh, 0FFh, 0FEh, 52h, 0A8h,	0, 46h,	0CFh, 39h
		db 1Ah,	0A8h, 0, 5, 10h, 45h, 0Ah, 28h,	2 dup(0), 55h
		db 50h,	1Ah, 20h, 2 dup(0), 0Ah, 1, 59h, 2 dup(0), 1, 50h
		db 15h,	51h, 2 dup(0), 5, 2 dup(55h), 15h, 2 dup(0), 2 dup(5)
		db 50h,	4, 2 dup(0), 1,	50h, 0,	10h, 2 dup(0), 5, 55h
		db 50h,	10h, 3 dup(0), 55h, 50h, 3 dup(0), 5, 54h, 40h
		db 3 dup(0), 1,	55h, 50h, 80h, 2 dup(0), 5, 52h, 0AAh
		db 2 dup(0), 1,	55h, 4Ah, 0AAh,	80h, 0
		
loc_D087:		
		db	6, 15h,	30h, 4 dup(0)
		db 0C0h, 3Ch, 5, 2 dup(55h), 3,	0C0h, 0Fh, 0D6h, 0AAh
		db 0A9h, 7Fh, 0, 3, 5Bh, 0FFh, 0FEh, 5Ch, 2 dup(0), 6Fh
		db 2 dup(0Fh), 90h, 2 dup(0), 6Fh, 30h,	0CFh, 90h, 2 dup(0)
		db 5Bh,	0FFh, 0FEh, 50h, 2 dup(0), 46h,	0CFh, 39h, 10h
		db 2 dup(0), 5,	10h, 45h, 4 dup(0), 55h, 50h, 4	dup(0)
		db 0Ah,	4 dup(0), 1, 50h, 40h, 3 dup(0), 5, 55h, 54h, 1
		db 40h,	0, 2 dup(5), 2 dup(55h), 0A0h, 0, 1, 50h, 1, 56h
		db 0A8h, 0, 5, 55h, 50h, 52h, 0A8h, 2 dup(0), 55h, 50h
		db 16h,	28h, 0,	5, 54h,	40h, 10h, 20h, 0, 1, 55h, 50h
		db 90h,	40h, 0,	5, 52h,	0AAh, 3, 0Ch, 1, 55h, 4Ah, 0AAh
		db 80h,	10h
		
loc_D107:		
		db 6,	16h, 1,	2 dup(0), 0D0h,	2 dup(0), 15h
		db 50h,	0Fh, 56h, 0A0h,	0, 41h,	4, 3Dh,	56h, 0A0h, 0, 1
		db 0, 3Fh, 0FFh, 0C0h, 0, 1
		db 0, 28h, 0A0h, 0AAh, 80h, 0Ah, 80h, 0Ah, 0AAh, 82h, 0A0h
		db 0Ah,	80h, 2,	8Ah, 20h, 0A0h,	1, 0A0h, 0FAh, 0A2h, 0A8h
		db 2 dup(0), 0A2h, 0BEh, 2 dup(0A0h), 2	dup(0),	0AAh, 0AFh
		db 0ECh, 3 dup(0), 2Ah,	0Fh, 0FFh, 4 dup(0), 0BFh, 0F7h
		db 3 dup(0), 1,	6Bh, 0DCh, 3 dup(0), 1,	56h, 0A0h, 3 dup(0)
		db 1, 55h, 10h,	3 dup(0), 1, 2 dup(54h), 3 dup(0), 5, 50h
		db 15h,	3 dup(0), 29h, 40h, 6, 80h, 2 dup(0), 0A8h, 0
		db 2, 82h, 0A0h, 2, 0A0h, 0, 2,	0AAh, 50h, 0Ah,	0AAh, 2	dup(0)
		db 0A5h, 0, 5, 55h, 40h, 0, 50h, 0
		
		
loc_D18D:	
		db 6, 16h, 3 dup(0), 34h
		db 4 dup(0), 3,	0D5h, 0A8h, 3 dup(0), 0Fh, 55h,	0A8h, 3	dup(0)
		db 0Fh,	0FFh, 0F0h, 3 dup(0), 0Ah, 0A8h, 2Ah, 0A0h, 2 dup(0)
		db 2, 0AAh, 0A0h, 0A8h,	3 dup(0), 0A2h,	88h, 28h, 2 dup(0)
		db 3Fh,	0, 0AAh, 3 dup(0), 0FAh, 0A0h, 28h, 3 dup(0), 0EAh
		db 0AAh, 3 dup(0), 28h,	0F0h, 2	dup(0AAh), 0, 2, 0A8h
		db 0BEh, 0Ah, 0AAh, 0A0h, 0, 0A1h, 6Bh,	0F0h, 0, 0A8h
		db 2, 21h, 56h,	0A0h, 0, 82h, 0, 1, 55h, 10h, 3	dup(0)
		db 1, 2	dup(54h), 3 dup(0), 5, 50h, 15h, 3 dup(0), 29h
		db 40h,	6, 80h,	2 dup(0), 0A8h,	0, 2, 80h, 0, 2, 0A0h
		db 0, 2, 80h, 0, 0Ah, 0AAh, 0, 0Ah, 0AAh, 0, 5,	55h, 40h
		db 5, 55h, 40h
		
loc_D213:
		db 6, 14h,	0, 0AAh, 80h, 3	dup(0),	2, 0A8h
		db 0A0h, 2, 0A0h, 0, 2,	0AEh, 23h, 0CAh, 0ABh, 0C0h, 3
		db 0FAh, 0Fh, 2Fh, 0ACh, 30h, 2, 0A0h, 0Ch, 28h, 0A2h
		db 30h,	2, 0A0h, 3, 0EAh, 0BAh,	80h, 2,	0AAh, 0, 2Ah, 0CEh
		db 2 dup(0), 2 dup(0AAh), 0Ah, 0FEh, 2 dup(0), 0Ah, 0AAh
		db 0A2h, 0FEh, 2 dup(0), 20h, 0AAh, 2 dup(0A8h), 0, 0Ah
		db 0AAh, 2Ah, 0A8h, 2 dup(0), 3Eh, 3 dup(0AAh),	2 dup(0)
		db 3Eh,	0A8h, 0Ah, 0A2h, 2 dup(0), 0Ah,	0AAh, 0A0h, 8Ah
		db 3 dup(0), 2Ah, 0AAh,	0Ah, 80h, 0, 0Ah, 80h, 0AAh, 82h
		db 0A0h, 0, 2Ah, 0, 0Ah, 0A0h, 0A8h, 0,	2Ah, 0,	0Ah, 80h
		db 22h,	0, 2Ah,	0, 2Ah,	80h, 0Eh, 0, 2Ah, 0B0h,	0AAh, 0ACh
		db 0FAh, 0
		
loc_D28D:
		db 6, 14h, 0Ah	dup(0),	2Ah, 4 dup(0), 3Ch, 0AAh
		db 0BCh, 3 dup(0), 0F2h, 0FAh, 0C3h, 3 dup(0), 0C2h, 8Ah
		db 23h,	3 dup(0), 3Eh, 0ABh, 0A8h, 3 dup(0), 2,	0ACh, 0E0h
		db 2 dup(0), 0Ah, 0A0h,	0AFh, 0E0h, 0, 2, 2 dup(0AAh)
		db 2Fh,	0E0h, 0, 2 dup(0AAh), 2	dup(8Ah), 80h, 0Ah, 0AAh
		db 0Ah,	0A0h, 2	dup(0),	3Eh, 0AAh, 0A2h, 0AAh, 80h, 30h
		db 3Eh,	0AAh, 0A8h, 2 dup(0AAh), 80h, 0Ah, 2 dup(0AAh)
		db 0, 0AAh, 0ACh, 0, 2Ah, 0AAh,	2 dup(0Ah), 0, 0Ah, 80h
		db 0AAh, 82h, 0A0h, 0C0h, 2Ah, 0, 0Ah, 0A0h, 0A8h, 0, 2Ah
		db 0, 0Ah, 80h,	22h, 0,	2Ah, 0,	2Ah, 80h, 0Eh, 0, 2Ah
		db 0B0h, 0AAh, 0ACh, 0FAh, 0
		
loc_D307:	
		db 6, 14h, 3	dup(0),	3Fh, 3 dup(0)
		db 2Ah,	81h, 43h, 0C0h,	55h, 0,	0AAh, 0D4h, 0, 0F0h, 15h
		db 0, 89h, 7Ah,	0, 3Dh,	41h, 28h, 96h, 0AAh, 0A0h, 0BEh
		db 0, 0A1h, 62h, 0AFh, 0C0h, 0AEh, 0, 0A8h, 5Ah, 0BCh
		db 2, 0AFh, 0, 0A0h, 5,	8Fh, 0EAh, 8Fh,	0, 20h,	2Ah, 50h
		db 2Ah,	0Fh, 0,	28h, 0AAh, 0A5h, 0, 0Fh, 0, 2Ah, 0A0h
		db 0AAh, 50h, 0Fh, 0, 0Ah, 8Ah,	0AAh, 0A5h, 3Ch, 0, 2 dup(2)
		db 0AAh, 20h, 0F0h, 3 dup(0), 0AAh, 9Ah, 0A0h, 2 dup(0)
		db 1, 55h, 5Ah,	0A8h, 0, 0Ah, 1, 55h, 58h, 0A8h, 0, 2Ah
		db 82h,	55h, 62h, 0A0h,	0, 2Ah,	0A2h, 0A5h, 42h, 80h, 0
		db 28h,	2Ah, 81h, 0Ah, 0AAh, 80h, 2Ah, 0Ah, 0, 0Ah, 0AAh
		db 0A0h
		
loc_D381:		
		db 6, 14h, 3 dup(0), 3Fh,	3 dup(0), 2Ah, 80h, 3
		db 0C0h, 2 dup(0), 0AAh, 0E0h, 0, 0F0h,	0, 8, 8Bh, 0FAh
		db 0, 3Ch, 0, 20h, 8Ah,	0AAh, 0A0h, 0BEh, 0, 0A0h, 0A2h
		db 0AFh, 0C0h, 0AEh, 0,	0A8h, 2Ah, 0BCh, 2, 0AFh, 0, 0A0h
		db 0Ah,	8Fh, 0EAh, 8Fh,	0, 20h,	2Ah, 0A0h, 2Ah,	0Fh, 0
		db 28h,	2 dup(0AAh), 0,	0Fh, 0,	2Ah, 0A0h, 0AAh, 80h, 0Fh
		db 0, 0Ah, 8Ah,	0AAh, 0A0h, 3Ch, 0, 2 dup(2), 0AAh, 20h
		db 0F0h, 3 dup(0), 0AAh, 9Ah, 0A0h, 2 dup(0), 1, 55h, 5Ah
		db 0A8h, 0, 0Ah, 1, 55h, 58h, 0A8h, 0, 2Ah, 82h, 55h, 62h
		db 0A0h, 0, 2Ah, 0A2h, 0A5h, 42h, 80h, 0, 28h, 2Ah, 81h
		db 0Ah,	0AAh, 80h, 2Ah,	0Ah, 0,	0Ah, 0AAh, 0A0h
		
loc_D3FB:
		db 6, 15h
		db 0, 2Ah, 80h,	4 dup(0), 0ABh,	0E0h, 4	dup(0),	8Bh, 0EAh
		db 4 dup(0), 8Ah, 0AAh,	0A0h, 3	dup(0),	0A2h, 0AFh, 2
		db 80h,	2 dup(0), 0AAh,	0BCh, 0FEh, 0BFh, 0B0h,	0, 2Ah
		db 0BCh, 56h, 95h, 90h,	2, 0A8h, 0Fh, 0Ah, 80h,	0, 2, 0AAh
		db 0A0h, 2Ah, 2	dup(0),	0Ah, 3 dup(0AAh), 2 dup(0), 0Ah
		db 0A8h, 0Ah, 0A8h, 2 dup(0), 0Fh, 0EAh, 0B2h, 80h, 2 dup(0)
		db 0Fh,	0FFh, 0F0h, 4 dup(0), 0FFh, 0F0h, 4 dup(0), 2Fh
		db 5 dup(0), 0AAh, 4 dup(0), 2,	0AAh, 4	dup(0),	2, 0A8h
		db 4 dup(0), 2,	0A8h, 5	dup(0),	0AAh, 0A8h, 4 dup(0), 2	dup(0AAh)
		db 3 dup(0)
		
loc_D47B:		
		db 6,	15h, 0,	2, 0A8h, 4 dup(0), 0Ah,	0AEh, 4	dup(0)
		db 8, 0BEh, 0A0h, 3 dup(0), 8, 2 dup(0AAh), 3 dup(0), 0Ah
		db 2Bh,	0F0h, 28h, 2 dup(0), 2,	0ABh, 0CFh, 0EBh, 0FBh
		db 0, 2Ah, 0ABh, 0C5h, 69h, 59h, 0, 0AAh, 0A8h,	0F0h, 0A8h
		db 0, 2, 2 dup(0AAh), 2, 0A0h, 0, 0Ah, 3 dup(0AAh), 0A0h
		db 0, 0Ah, 0A8h, 0Ah, 0AAh, 80h, 0, 0Fh, 0EAh, 0B0h, 0A8h
		db 2 dup(0), 0Fh, 0FFh,	0F0h, 3	dup(0),	0Ah, 0FFh, 0F0h
		db 3 dup(0), 0Ah, 0AFh,	4 dup(0), 0Ah, 0A2h, 80h, 3 dup(0)
		db 0Ah,	8Ah, 80h, 3 dup(0), 2Ah, 2, 0A0h, 3 dup(0), 2Ah
		db 2, 0A0h, 3 dup(0), 2Ah, 0A8h, 0AAh, 80h, 2 dup(0), 2Ah
		db 0AAh, 2Ah, 0A0h, 2 dup(0)
		
loc_D4FB:		
		db 6, 16h, 0, 0Ah, 80h, 2 dup(0)
		db 0A0h, 15h, 5Ah, 95h,	55h, 56h, 0AAh,	0, 0Ah,	8Ah, 0AEh
		db 0, 0A0h, 0, 0Ah, 8, 0BFh, 0A0h, 2 dup(0), 0Ah, 8, 2 dup(0AAh)
		db 2 dup(0), 2 dup(0Ah), 2Ah, 0FCh, 2 dup(0), 0Ah, 82h
		db 0ABh, 0C0h, 2 dup(0), 2, 2 dup(0AAh), 0FCh, 3 dup(0)
		db 0AAh, 0A8h, 4 dup(0), 0Ah, 0AAh, 4 dup(0), 0A2h, 0AAh
		db 4 dup(0), 0AAh, 0A8h, 3 dup(0), 1, 6Ah, 90h,	3 dup(0)
		db 1, 55h, 50h,	3 dup(0), 2, 55h, 50h, 3 dup(0), 2, 0A5h
		db 0A8h, 3 dup(0), 0Ah,	0A0h, 0AAh, 3 dup(0), 2Ah, 80h
		db 0Ah,	2 dup(80h), 0, 0A8h, 0,	2, 82h,	0A0h, 2, 0A0h
		db 20h,	2, 0AAh, 0A0h, 0Ah, 0AAh, 80h, 0, 0AAh,	0, 0Ah
		db 0AAh, 0A0h, 0, 0A0h,	0
		
loc_D581:		
		db 6, 16h, 9 dup(0), 0AAh, 4 dup(0)
		db 2, 0ABh, 80h, 3 dup(0), 2, 2Fh, 0E8h, 3 dup(0), 2, 2Ah
		db 0AAh, 80h, 2	dup(0),	2, 8Ah,	0BFh, 4	dup(0),	0AAh, 0F0h
		db 3 dup(0), 2Ah, 0Ah, 0BFh, 3 dup(0), 0AAh, 0A0h, 4 dup(0)
		db 2 dup(0AAh),	3 dup(0), 28h, 0A0h, 2 dup(0AAh), 0, 2
		db 0A8h, 0AAh, 0Ah, 0AAh, 0A0h,	0, 0A1h, 6Ah, 90h, 0, 0A8h
		db 2, 21h, 55h,	50h, 0,	82h, 0,	2, 55h,	50h, 3 dup(0)
		db 2, 0A5h, 0A8h, 3 dup(0), 0Ah, 0A0h, 2Ah, 3 dup(0), 2Ah
		db 80h,	0Ah, 80h, 2 dup(0), 0A8h, 0, 2,	80h, 0,	2, 0A0h
		db 20h,	2, 80h,	20h, 0Ah, 0AAh,	80h, 0Ah, 0AAh,	80h, 0Ah
		db 0AAh, 0A0h, 0Ah, 0AAh, 0A0h
		
loc_D607:
		db	0Ch, 8,	0Ah dup(0), 0Fh
		db 0FFh, 9 dup(0), 0FFh, 0F0h, 8 dup(0), 0Fh, 0FFh, 9 dup(0)
		db 0FFh, 0F0h, 8 dup(0), 0Fh, 0FFh, 9 dup(0), 0FFh, 0F0h
		db 8 dup(0), 0Fh, 0FFh,	9 dup(0), 0FFh,	0F0h, 0Ah dup(0)
		
loc_D669:
		db 0Ah,	10h, 9 dup(0), 3Fh, 8 dup(0), 3Fh
		db 0C0h, 7 dup(0), 3Fh,	0C0h, 7	dup(0),	3Fh, 0C0h, 7 dup(0)
		db 3Fh,	0C0h, 7	dup(0),	3, 0C0h, 8 dup(0), 3Ch,	8 dup(0)
		db 3, 0C0h, 8 dup(0), 3Ch, 8 dup(0), 3,	0C0h, 8	dup(0)
		db 3Ch,	8 dup(0), 3, 0C0h, 8 dup(0), 3Ch, 8 dup(0), 3
		db 0C0h, 8 dup(0), 3Ch,	9 dup(0), 0C0h,	9 dup(0)
		
loc_D70B:
		db 8, 19h
		db 7 dup(0), 0FFh, 6 dup(0), 0FFh, 6 dup(0), 0FFh, 6 dup(0)
		db 0Fh,	7 dup(0), 0F0h,	6 dup(0), 0Fh, 7 dup(0), 0F0h
		db 6 dup(0), 0Fh, 7 dup(0), 30h, 7 dup(0), 0C0h, 6 dup(0)
		db 3, 7	dup(0),	0Ch, 7 dup(0), 30h, 7 dup(0), 0C0h, 6 dup(0)
		db 3, 7	dup(0),	3, 7 dup(0), 0Ch, 7 dup(0), 0Ch, 7 dup(0)
		db 30h,	7 dup(0), 30h, 7 dup(0), 0C0h, 7 dup(0), 0C0h
		db 7 dup(0), 0C0h, 7 dup(0), 0C0h, 7 dup(0), 0C0h, 7 dup(0)
		
loc_D7D5:
		db 6, 20h, 5 dup(0), 0FFh, 4 dup(0), 0FFh, 4 dup(0), 0Fh
		db 5 dup(0), 0F0h, 4 dup(0), 0Fh, 5 dup(0), 30h, 5 dup(0)
		db 0C0h, 4 dup(0), 3, 5	dup(0),	0Ch, 5 dup(0), 30h, 5 dup(0)
		db 0C0h, 5 dup(0), 0C0h, 4 dup(0), 3, 5	dup(0),	3, 5 dup(0)
		db 3, 5	dup(0),	0Ch, 5 dup(0), 0Ch, 5 dup(0), 0Ch, 5 dup(0)
		db 0Ch,	5 dup(0), 30h, 5 dup(0), 30h, 5	dup(0),	30h, 5 dup(0)
		db 30h,	5 dup(0), 30h, 5 dup(0), 0C0h, 5 dup(0), 0C0h
		db 5 dup(0), 0C0h, 5 dup(0), 0C0h, 5 dup(0), 0C0h, 5 dup(0)
		db 0C0h, 5 dup(0), 0C0h, 5 dup(0), 0C0h, 5 dup(0)
		
loc_D897:
		db 4, 29h
		db 3 dup(0), 0Fh, 3 dup(0), 0F0h, 2 dup(0), 3, 3 dup(0)
		db 0Ch,	3 dup(0), 30h, 3 dup(0), 0C0h, 2 dup(0), 3, 3 dup(0)
		db 3, 3	dup(0),	0Ch, 3 dup(0), 0Ch, 3 dup(0), 0Ch, 3 dup(0)
		db 30h,	3 dup(0), 30h, 3 dup(0), 30h, 3	dup(0),	0C0h, 3	dup(0)
		db 0C0h, 3 dup(0), 0C0h, 2 dup(0), 3, 3	dup(0),	3, 3 dup(0)
		db 3, 3	dup(0),	3, 3 dup(0), 0Ch, 3 dup(0), 0Ch, 3 dup(0)
		db 0Ch,	3 dup(0), 0Ch, 3 dup(0), 0Ch, 3	dup(0),	0Ch, 3 dup(0)
		db 0Ch,	3 dup(0), 30h, 3 dup(0), 30h, 3	dup(0),	30h, 3 dup(0)
		db 30h,	3 dup(0), 30h, 3 dup(0), 0C0h, 3 dup(0), 0C0h
		db 3 dup(0), 0C0h, 3 dup(0), 0C0h, 3 dup(0), 0C0h, 3 dup(0)
		db 0C0h, 3 dup(0), 0C0h, 3 dup(0), 0C0h, 3 dup(0)
		
loc_D93D:		
		db 6, 0Ch
		db 2 dup(0), 30h, 0CCh,	0C0h, 2	dup(0),	3, 0Ch,	2 dup(0CCh)
		db 0, 0Ch, 0, 0C3h, 2 dup(0FFh), 0, 3, 0Ch, 3Fh, 2 dup(0FFh)
		db 0F0h, 0, 0C3h, 2 dup(0FCh), 0FFh, 0FCh, 3, 3Fh, 0CFh
		db 3, 0FCh, 2 dup(0), 0FFh, 0Fh, 0FFh, 0C3h, 0FCh, 3, 2	dup(0C3h)
		db 2 dup(0FFh),	0CCh, 3, 0, 3Fh, 0CFh, 0FFh, 0F0h, 0Ch
		db 0, 3, 0CFh, 0FFh, 4 dup(0), 0F0h, 3Ch, 4 dup(0), 3Ch
		db 0Fh,	0
		
loc_D987:		
		db 6, 0Ch, 2 dup(0), 30h, 0CCh,	0C0h, 2	dup(0)
		db 3, 0Ch, 2 dup(0CCh),	3 dup(0), 0C3h,	2 dup(0FFh), 0
		db 3Ch,	0Ch, 3Fh, 3, 0FFh, 0F0h, 2 dup(3), 0FCh, 30h, 0F0h
		db 3Ch,	0Ch, 0FFh, 0CFh, 3, 0C0h, 0, 3,	0FFh, 0Fh, 0FFh
		db 2 dup(0), 0Fh, 3, 0C3h, 0FFh, 2 dup(0), 3Ch,	0, 3Fh
		db 0CFh, 0C3h, 0F0h, 2 dup(0), 3, 3Fh, 0FFh, 3 dup(0)
		db 0Fh,	3, 0C0h, 3 dup(0), 3Ch,	0Fh, 2 dup(0)
		
loc_D9D1:		
		db 6, 10h
		db 3 dup(0), 30h, 4 dup(0), 3Fh, 0Fh, 0F0h, 4 dup(0), 2	dup(0FFh)
		db 3 dup(0), 0F3h, 2 dup(0FFh),	0C0h, 0, 2 dup(0Fh), 0FFh
		db 0BEh, 2 dup(0FCh), 0, 2 dup(0FFh), 0EBh, 0FFh, 0Fh
		db 0FFh, 0F3h, 3 dup(0FFh), 0, 3Fh, 0CFh, 0FFh,	0FAh, 0ACh
		db 3, 0FFh, 0CFh, 0FAh,	0AFh, 0FCh, 3, 0F0h, 0F3h, 0EFh
		db 0FFh, 3Ch, 0Fh, 0, 0Fh, 0FFh, 2 dup(0F0h), 3Ch, 0, 0F0h
		db 2 dup(0FFh),	0C0h, 30h, 2 dup(0), 0FCh, 0FFh, 4 dup(0)
		db 0F3h, 0FCh, 3 dup(0), 3, 0C0h, 0Ch, 3 dup(0), 3Ch, 0
		db 30h,	0
		
loc_DA33:		
		db 6, 10h, 2 dup(0), 0F0h, 30h,	4 dup(0), 2 dup(0Fh)
		db 0FCh, 0, 3Ch, 2 dup(0), 0FFh, 0EBh, 0C0h, 0Fh, 0, 0F3h
		db 0FFh, 0BEh, 0FCh, 3 dup(0Fh), 0FFh, 0EBh, 0FFh, 3, 0F0h
		db 4 dup(0FFh),	3, 3Fh,	0F3h, 0F0h, 2 dup(50h),	0, 0FFh
		db 0CFh, 0, 2 dup(40h),	0Fh, 0FFh, 0CFh, 3 dup(0), 0FCh
		db 0, 0F3h, 0F0h, 4 dup(0), 0Fh, 0FFh, 0F0h, 3Ch, 0, 3
		db 0F0h, 2 dup(0FFh), 0FCh, 3 dup(0), 2	dup(3Fh), 0F0h
		db 3 dup(0), 0Fh, 3Fh, 4 dup(0), 3, 0C0h, 0F0h,	4 dup(0)
		db 30h,	0
		
		
loc_DA95:
		db 6, 17h, 3 dup(0), 0FFh, 4 dup(0), 0Fh, 14h
		db 0F0h, 0Ch, 2	dup(0),	0F1h, 55h
		db 0Fh,	2 dup(0), 3, 15h, 55h, 51h, 0F0h, 0, 0Ch, 3 dup(55h)
		db 5Ch,	0, 35h,	51h, 40h, 55h, 0, 1, 55h, 54h, 15h, 0
		db 54h,	5, 41h,	3 dup(55h), 50h, 15h, 0, 50h, 2	dup(55h)
		db 0, 14h, 0, 5, 15h, 50h, 0F0h, 14h, 2	dup(0),	55h, 2 dup(0)
		db 14h,	4 dup(0), 0Ch, 14h, 0, 28h, 3 dup(0), 5, 2, 0BEh
		db 80h,	2 dup(0), 1, 50h, 28h, 4 dup(0), 15h, 40h, 3 dup(0)
		db 2, 81h, 54h,	3 dup(0), 2Bh, 0E8h, 5,	3 dup(0), 2, 80h
		db 1, 40h, 4 dup(0), 1,	45h, 4 dup(0), 11h, 50h, 4 dup(0)
		db 5, 40h, 4 dup(0), 1,	50h, 2 dup(0)
		
loc_DB21:
		db 6, 17h, 2 dup(0)
		db 0FFh, 3, 0C0h, 2 dup(0), 0Fh, 15h, 0FDh, 70h, 2 dup(0)
		db 0F1h, 55h, 40h, 1Ch,	0, 3, 15h, 50h,	15h, 2 dup(0)
		db 0Ch,	55h, 45h, 40h, 2 dup(0), 0Ch, 54h, 10h,	3 dup(0)
		db 15h,	55h, 45h, 3 dup(0), 14h, 45h, 51h, 50h,	2 dup(0)
		db 14h,	50h, 55h, 15h, 54h, 0, 14h, 2 dup(5), 45h, 50h
		db 0, 14h, 0, 55h, 54h,	2 dup(0), 5, 5 dup(0), 1, 50h
		db 5 dup(0), 15h, 0, 28h, 3 dup(0), 1, 52h, 0BEh, 80h
		db 2 dup(0), 28h, 14h, 28h, 2 dup(0), 2, 0BEh, 85h, 4 dup(0)
		db 28h,	5, 5 dup(0), 1,	40h, 4 dup(0), 1, 45h, 4 dup(0)
		db 11h,	50h, 4 dup(0), 5, 40h, 4 dup(0), 1, 50h, 2 dup(0)
		
loc_DBAD:		
		db 6, 16h, 5, 0, 0Fh, 3Ch, 2 dup(0), 19h, 4Ch, 2 dup(0FFh)
		db 0C0h, 0, 15h, 43h, 2	dup(0FFh), 2 dup(0), 15h, 43h
		db 0FFh, 0E2h, 0AAh, 0,	5, 0, 0FFh, 2 dup(82h),	80h, 0Ah
		db 83h,	3Fh, 0EBh, 0EAh, 80h, 0Ah, 80h,	2, 0FFh, 0F0h
		db 0, 5, 0A0h, 29h, 0AFh, 0F0h,	2 dup(0), 0A2h,	0AAh, 68h
		db 3Ch,	2 dup(0), 2 dup(0AAh), 6Ah, 3, 2 dup(0), 2Ah, 0Ah
		db 5Ah,	4 dup(0), 0AAh,	58h, 3 dup(0), 1, 69h, 50h, 3 dup(0)
		db 1, 55h, 50h,	3 dup(0), 1, 55h, 50h, 3 dup(0), 6, 95h
		db 0A8h, 3 dup(0), 0Ah,	0A4h, 0AAh, 3 dup(0), 2Ah, 84h
		db 0Ah,	2 dup(80h), 0, 0A8h, 0,	2, 82h,	0A0h, 2, 0A0h
		db 20h,	2, 0AAh, 0A0h, 0Ah, 0AAh, 80h, 0, 0AAh,	0, 0Ah
		db 0AAh, 0A0h, 0, 0A0h,	0
		
loc_DC33:		
		db 6, 16h, 2 dup(0), 3,	0CFh, 3	dup(0)
		db 3, 3Fh, 0FFh, 0F0h, 3 dup(0), 2 dup(0FFh), 0C0h, 3 dup(0)
		db 0FFh, 0F8h, 0AAh, 80h, 2 dup(0), 3Fh, 0E0h, 2 dup(0A0h)
		db 2 dup(0), 0CFh, 2 dup(0FAh),	0A0h, 2	dup(0),	2, 0FFh
		db 0FCh, 3 dup(0), 29h,	3, 0FCh, 3 dup(0), 0AAh, 0A0h
		db 0Fh,	3 dup(0), 2 dup(0AAh), 0, 0C0h,	0, 28h,	0A0h, 2	dup(0AAh)
		db 0, 2, 0A8h, 0AAh, 0Ah, 0AAh,	0A0h, 0, 0A1h, 69h, 50h
		db 0, 0A8h, 2, 21h, 55h, 50h, 0, 82h, 0, 1, 55h, 50h, 3	dup(0)
		db 6, 95h, 0A8h, 3 dup(0), 0Ah,	0A4h, 2Ah, 3 dup(0), 2Ah
		db 84h,	0Ah, 80h, 2 dup(0), 0A8h, 0, 2,	80h, 0,	2, 0A0h
		db 20h,	2, 80h,	20h, 0Ah, 0AAh,	80h, 0Ah, 0AAh,	80h, 0Ah
		db 0AAh, 0A0h, 0Ah, 0AAh, 0A0h
		
loc_DCB9:		
		db	6, 7, 2	dup(0),	15h, 55h
		db 40h,	2 dup(0), 5, 55h, 99h, 55h, 50h, 0, 56h, 55h, 5Ah
		db 55h,	2 dup(5), 55h, 5Ah, 3 dup(55h),	14h, 5,	19h, 54h
		db 95h,	50h, 10h, 0, 54h, 1, 50h, 8, 40h, 0, 50h, 1, 40h
		db 0
		
loc_DCE5:		
		db 6, 7, 50h, 0, 15h, 55h, 40h, 0, 2	dup(5),	55h, 99h
		db 55h,	50h, 1,	56h, 55h, 5Ah, 55h, 5, 0, 55h, 5Ah, 3 dup(55h)
		db 0, 5, 51h, 55h, 85h,	50h, 2 dup(0), 54h, 1, 50h, 3 dup(0)
		db 15h,	0, 54h,	0
		
loc_DD11:		
		db 6, 0Bh, 4 dup(0), 0A0h, 4 dup(0), 2
		db 0A8h, 4 dup(0), 0Ah,	5Ah, 4 dup(0), 0Ah, 0A0h, 3 dup(0)
		db 0Ah,	2, 0A8h, 0, 0Ah, 0, 2Ah, 80h, 28h, 2 dup(0), 80h
		db 2 dup(0A0h),	0Ah, 2 dup(0), 20h, 2 dup(0A0h), 0Ah, 2	dup(0)
		db 20h,	2 dup(0A0h), 2Ah, 2 dup(0), 20h, 0A0h
		db 2Ah,	0A8h, 2	dup(0),	0Ah, 80h, 0Ah, 80h, 0
		
loc_DD55:		
		db 6, 0Bh
		db 4 dup(0), 0Ah, 5 dup(0), 2Ah, 80h, 4	dup(0),	0A5h, 0A0h
		db 4 dup(0), 0AAh, 5 dup(0), 2Ah, 80h, 20h, 3 dup(0), 0Ah
		db 0, 20h, 0, 0A8h, 0, 0Ah, 0, 80h, 2, 0AAh, 0,	2Ah, 0
		db 80h,	2 dup(0Ah), 80h, 0A8h, 0, 20h, 0A0h, 2,	0AAh, 0A0h
		db 0, 0Ah, 2 dup(0), 0AAh, 80h,	0
		