;========================
; PROVISION STATES DATA
;========================

provisionStatePtrs:
;food-water
		dw loc_82CC
		dw loc_82D5
		dw loc_832F
		dw loc_839D
		dw loc_83E8
		dw loc_840D
		dw loc_854E
		dw loc_8585
		dw loc_87FE
		dw loc_87C1
		
stoneStatePtrs:
		dw loc_8350
		dw loc_8479
		dw loc_85B8
		dw loc_879A
		dw loc_89DB
		
;food-water
		dw loc_861D
		dw loc_870F
		dw loc_8853
		dw loc_8918
		
		db 4, 20h
		db 4, 10h
		db 4, 40h
		db 2, 40h
		db 4
		
;========================
